// inertia/pages/organizations/create.svelte
<script lang="ts">
  import AppLayout from '@/layouts/app_layout.svelte'
  import Card from '@/components/ui/card.svelte'
  import CardHeader from '@/components/ui/card_header.svelte'
  import CardTitle from '@/components/ui/card_title.svelte'
  import CardContent from '@/components/ui/card_content.svelte'
  import CardFooter from '@/components/ui/card_footer.svelte'
  import Button from '@/components/ui/button.svelte'
  import Input from '@/components/ui/input.svelte'
  import Label from '@/components/ui/label.svelte'
  import Textarea from '@/components/ui/textarea.svelte'
  import Select from '@/components/ui/select.svelte'
  import SelectTrigger from '@/components/ui/select_trigger.svelte'
  import SelectContent from '@/components/ui/select_content.svelte'
  import SelectItem from '@/components/ui/select_item.svelte'
  import { router } from '@inertiajs/svelte'
  import { useTranslation } from '@/stores/translation.svelte'
  import { Building } from 'lucide-svelte'

  const { t } = useTranslation()

  let formData = $state({
    name: '',
    slug: '',
    description: '',
    website: '',
    plan: 'free',
  })

  let slugManuallyEdited = $state(false)
  let errors = $state<Record<string, string>>({})
  let submitting = $state(false)

  function generateSlug(name: string): string {
    return name
      .toLowerCase()
      .normalize('NFD')
      .replace(/[\u0300-\u036f]/g, '')
      .replace(/đ/g, 'd')
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '')
  }

  function handleNameChange(e: Event) {
    const target = e.target as HTMLInputElement
    formData.name = target.value
    if (!slugManuallyEdited) {
      formData.slug = generateSlug(target.value)
    }
  }

  function handleSlugChange(e: Event) {
    const target = e.target as HTMLInputElement
    formData.slug = target.value
    slugManuallyEdited = true
  }

  function handleChange(e: Event) {
    const target = e.target as HTMLInputElement | HTMLTextAreaElement
    const { name, value } = target
    formData = { ...formData, [name]: value }
  }

  function handleSubmit() {
    const newErrors: Record<string, string> = {}

    if (!formData.name.trim()) {
      newErrors.name = 'Tên tổ chức là bắt buộc'
    }

    if (Object.keys(newErrors).length > 0) {
      errors = newErrors
      return
    }

    submitting = true

    router.post('/organizations', formData, {
      onSuccess: () => {
        submitting = false
      },
      onError: (errorResponse) => {
        submitting = false
        errors = errorResponse
      },
    })
  }

  function handleCancel() {
    router.visit('/organizations')
  }

  const plans = [
    { value: 'free', label: 'Free' },
    { value: 'pro', label: 'Pro' },
    { value: 'enterprise', label: 'Enterprise' },
  ]
</script>

<svelte:head>
  <title>Tạo tổ chức mới</title>
</svelte:head>

<AppLayout title="Tạo tổ chức mới">
  <div class="p-4 sm:p-6 max-w-3xl mx-auto">
    <Card class="border-2 shadow-neo">
      <CardHeader>
        <CardTitle class="flex items-center gap-2">
          <Building class="h-5 w-5" />
          Tạo tổ chức mới
        </CardTitle>
        <p class="text-sm text-muted-foreground">
          Điền thông tin bên dưới để tạo tổ chức mới.
        </p>
      </CardHeader>

      <CardContent>
        <div class="grid gap-6">
          <!-- Name -->
          <div class="grid gap-2">
            <Label for="name" class="font-bold">Tên tổ chức <span class="text-destructive">*</span></Label>
            <Input
              id="name"
              name="name"
              value={formData.name}
              oninput={handleNameChange}
              placeholder="Nhập tên tổ chức"
              class={errors.name ? 'border-destructive' : ''}
              autofocus
            />
            {#if errors.name}
              <p class="text-xs font-bold text-destructive">{errors.name}</p>
            {/if}
          </div>

          <!-- Slug -->
          <div class="grid gap-2">
            <Label for="slug" class="font-bold">Slug</Label>
            <Input
              id="slug"
              name="slug"
              value={formData.slug}
              oninput={handleSlugChange}
              placeholder="ten-to-chuc"
              class={errors.slug ? 'border-destructive' : ''}
            />
            <p class="text-xs text-muted-foreground">Tự động tạo từ tên, có thể chỉnh sửa.</p>
            {#if errors.slug}
              <p class="text-xs font-bold text-destructive">{errors.slug}</p>
            {/if}
          </div>

          <!-- Description -->
          <div class="grid gap-2">
            <Label for="description" class="font-bold">Mô tả</Label>
            <Textarea
              id="description"
              name="description"
              value={formData.description}
              onchange={handleChange}
              placeholder="Mô tả về tổ chức của bạn"
              rows={4}
            />
            {#if errors.description}
              <p class="text-xs font-bold text-destructive">{errors.description}</p>
            {/if}
          </div>

          <!-- Website + Plan -->
          <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div class="grid gap-2">
              <Label for="website" class="font-bold">Website</Label>
              <Input
                id="website"
                name="website"
                type="url"
                value={formData.website}
                onchange={handleChange}
                placeholder="https://example.com"
              />
              {#if errors.website}
                <p class="text-xs font-bold text-destructive">{errors.website}</p>
              {/if}
            </div>

            <div class="grid gap-2">
              <Label for="plan" class="font-bold">Gói dịch vụ</Label>
              <Select
                value={formData.plan}
                onValueChange={(v) => v && (formData.plan = v)}
              >
                <SelectTrigger id="plan">
                  <span>{plans.find(p => p.value === formData.plan)?.label || 'Chọn gói'}</span>
                </SelectTrigger>
                <SelectContent>
                  {#each plans as plan (plan.value)}
                    <SelectItem value={plan.value} label={plan.label}>
                      {plan.label}
                    </SelectItem>
                  {/each}
                </SelectContent>
              </Select>
              {#if errors.plan}
                <p class="text-xs font-bold text-destructive">{errors.plan}</p>
              {/if}
            </div>
          </div>
        </div>
      </CardContent>

      <CardFooter class="flex justify-end gap-3 border-t-2 border-border pt-6">
        <Button
          variant="outline"
          onclick={handleCancel}
          disabled={submitting}
        >
          {t('common.cancel', {}, 'Hủy')}
        </Button>
        <Button
          onclick={handleSubmit}
          disabled={submitting}
        >
          {submitting ? 'Đang tạo...' : 'Tạo tổ chức'}
        </Button>
      </CardFooter>
    </Card>
  </div>
</AppLayout>

// inertia/pages/projects/create.tsx
import React, { useState } from 'react'
import { Head } from '@inertiajs/react'
import { router } from '@inertiajs/react'
import AppLayout from '@/layouts/app_layout'
import { Button } from '@/components/ui/button'
import { Card, CardHeader, CardTitle, CardContent, CardFooter } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Textarea } from '@/components/ui/textarea'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { ProjectCreateProps } from './types'
import useTranslation from '@/hooks/use_translation'
import { CalendarIcon } from 'lucide-react'
import { format } from 'date-fns'
import { vi } from 'date-fns/locale'
import { cn } from '@/lib/utils'
import { Calendar } from '@/components/ui/calendar'
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover'

export default function ProjectCreate({ organizations, statuses, auth }: ProjectCreateProps) {
  const { t } = useTranslation()
  const [formData, setFormData] = useState({
    name: '',
    description: '',
    organization_id: '',
    status_id: '',
    start_date: '',
    end_date: '',
    manager_id: auth.user.id.toString(), // Mặc định người tạo là quản lý
  })
  const [startDate, setStartDate] = useState<Date | undefined>(undefined)
  const [endDate, setEndDate] = useState<Date | undefined>(undefined)
  const [errors, setErrors] = useState<Record<string, string>>({})
  
  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => {
    const { name, value } = e.target
    setFormData(prev => ({ ...prev, [name]: value }))
    
    // Xóa lỗi khi người dùng sửa trường đó
    if (errors[name]) {
      setErrors(prev => {
        const newErrors = { ...prev }
        delete newErrors[name]
        return newErrors
      })
    }
  }
  
  const handleSelectChange = (name: string, value: string) => {
    setFormData(prev => ({ ...prev, [name]: value }))
    
    // Xóa lỗi khi người dùng sửa trường đó
    if (errors[name]) {
      setErrors(prev => {
        const newErrors = { ...prev }
        delete newErrors[name]
        return newErrors
      })
    }
  }
  
  const handleStartDateChange = (date: Date | undefined) => {
    setStartDate(date)
    setFormData(prev => ({ 
      ...prev, 
      start_date: date ? format(date, 'yyyy-MM-dd') : '' 
    }))
    
    // Xóa lỗi khi người dùng sửa trường đó
    if (errors['start_date']) {
      setErrors(prev => {
        const newErrors = { ...prev }
        delete newErrors['start_date']
        return newErrors
      })
    }
  }
  
  const handleEndDateChange = (date: Date | undefined) => {
    setEndDate(date)
    setFormData(prev => ({ 
      ...prev, 
      end_date: date ? format(date, 'yyyy-MM-dd') : '' 
    }))
    
    // Xóa lỗi khi người dùng sửa trường đó
    if (errors['end_date']) {
      setErrors(prev => {
        const newErrors = { ...prev }
        delete newErrors['end_date']
        return newErrors
      })
    }
  }
  
  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()
    
    // Kiểm tra dữ liệu
    const newErrors: Record<string, string> = {}
    
    if (!formData.name.trim()) {
      newErrors.name = t('validator.required', {}, 'Trường này là bắt buộc')
    }
    
    if (!formData.organization_id) {
      newErrors.organization_id = t('validator.required', {}, 'Trường này là bắt buộc')
    }
    
    if (!formData.status_id) {
      newErrors.status_id = t('validator.required', {}, 'Trường này là bắt buộc')
    }
    
    if (Object.keys(newErrors).length > 0) {
      setErrors(newErrors)
      return
    }
    
    // Gửi dữ liệu
    router.post('/projects', formData)
  }
  
  return (
    <AppLayout title={t('project.create_project', {}, 'Tạo dự án mới')}>
      <Head title={t('project.create_project', {}, 'Tạo dự án mới')} />

      <div className="p-4 sm:p-6 space-y-6">
        <div className="flex justify-between items-center">
          <h1 className="text-2xl font-bold">{t('project.create_project', {}, 'Tạo dự án mới')}</h1>
          
          <Button 
            onClick={() => router.visit('/projects')}
            variant="outline"
          >
            {t('common.cancel', {}, 'Hủy')}
          </Button>
        </div>
        
        <Card>
          <form onSubmit={handleSubmit}>
            <CardContent className="pt-6 space-y-4">
              <div className="space-y-2">
                <Label htmlFor="name">
                  {t('project.name', {}, 'Tên dự án')} <span className="text-red-500">*</span>
                </Label>
                <Input
                  id="name"
                  name="name"
                  value={formData.name}
                  onChange={handleChange}
                  className={errors.name ? 'border-red-500' : ''}
                />
                {errors.name && (
                  <p className="text-sm text-red-500">{errors.name}</p>
                )}
              </div>
              
              <div className="space-y-2">
                <Label htmlFor="description">
                  {t('project.description', {}, 'Mô tả')}
                </Label>
                <Textarea
                  id="description"
                  name="description"
                  value={formData.description}
                  onChange={handleChange}
                  rows={4}
                />
              </div>
              
              <div className="space-y-2">
                <Label htmlFor="organization_id">
                  {t('project.organization', {}, 'Tổ chức')} <span className="text-red-500">*</span>
                </Label>
                <Select 
                  value={formData.organization_id} 
                  onValueChange={(value) => handleSelectChange('organization_id', value)}
                >
                  <SelectTrigger className={errors.organization_id ? 'border-red-500' : ''}>
                    <SelectValue placeholder={t('project.select_organization', {}, 'Chọn tổ chức')} />
                  </SelectTrigger>
                  <SelectContent>
                    {organizations.map((org) => (
                      <SelectItem key={org.id} value={org.id.toString()}>
                        {org.name}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
                {errors.organization_id && (
                  <p className="text-sm text-red-500">{errors.organization_id}</p>
                )}
              </div>
              
              <div className="space-y-2">
                <Label htmlFor="status_id">
                  {t('project.status', {}, 'Trạng thái')} <span className="text-red-500">*</span>
                </Label>
                <Select 
                  value={formData.status_id} 
                  onValueChange={(value) => handleSelectChange('status_id', value)}
                >
                  <SelectTrigger className={errors.status_id ? 'border-red-500' : ''}>
                    <SelectValue placeholder={t('project.select_status', {}, 'Chọn trạng thái')} />
                  </SelectTrigger>
                  <SelectContent>
                    {statuses.map((status) => (
                      <SelectItem key={status.id} value={status.id.toString()}>
                        {status.name}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
                {errors.status_id && (
                  <p className="text-sm text-red-500">{errors.status_id}</p>
                )}
              </div>
              
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label htmlFor="start_date">
                    {t('project.start_date', {}, 'Ngày bắt đầu')}
                  </Label>
                  <Popover>
                    <PopoverTrigger asChild>
                      <Button
                        variant="outline"
                        className={cn(
                          "w-full justify-start text-left font-normal",
                          !startDate && "text-muted-foreground"
                        )}
                      >
                        <CalendarIcon className="mr-2 h-4 w-4" />
                        {startDate ? (
                          format(startDate, 'PPP', { locale: vi })
                        ) : (
                          <span>{t('common.pick_date', {}, 'Chọn ngày')}</span>
                        )}
                      </Button>
                    </PopoverTrigger>
                    <PopoverContent className="w-auto p-0">
                      <Calendar
                        mode="single"
                        selected={startDate}
                        onSelect={handleStartDateChange}
                        // Loại bỏ initialFocus vì không tồn tại trong CalendarProps
                      />
                    </PopoverContent>
                  </Popover>
                </div>
                
                <div className="space-y-2">
                  <Label htmlFor="end_date">
                    {t('project.end_date', {}, 'Ngày kết thúc')}
                  </Label>
                  <Popover>
                    <PopoverTrigger asChild>
                      <Button
                        variant="outline"
                        className={cn(
                          "w-full justify-start text-left font-normal",
                          !endDate && "text-muted-foreground"
                        )}
                      >
                        <CalendarIcon className="mr-2 h-4 w-4" />
                        {endDate ? (
                          format(endDate, 'PPP', { locale: vi })
                        ) : (
                          <span>{t('common.pick_date', {}, 'Chọn ngày')}</span>
                        )}
                      </Button>
                    </PopoverTrigger>
                    <PopoverContent className="w-auto p-0">
                      <Calendar
                        mode="single"
                        selected={endDate}
                        onSelect={handleEndDateChange}
                      />
                    </PopoverContent>
                  </Popover>
                </div>
              </div>
            </CardContent>
            
            <CardFooter className="flex justify-end space-x-2">
              <Button 
                type="button" 
                variant="outline" 
                onClick={() => router.visit('/projects')}
              >
                {t('common.cancel', {}, 'Hủy')}
              </Button>
              <Button type="submit">
                {t('common.create', {}, 'Tạo')}
              </Button>
            </CardFooter>
          </form>
        </Card>
      </div>
    </AppLayout>
  )
}
