// inertia/pages/settings/profile.tsx
import React, { useRef, useState } from 'react'
import { Head, useForm, usePage } from '@inertiajs/react'
import { Link } from '@inertiajs/react'
import AppLayout from '@/layouts/app_layout'
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Textarea } from '@/components/ui/textarea'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar'

// Import icons
import { User, CreditCard, Bell, Eye, Palette, Upload } from 'lucide-react'

// Define sidebar item type
interface SidebarItem {
  title: string
  href: string
  icon: React.ElementType
}

// Define các type dữ liệu từ backend
interface UserData {
  id: string
  username: string
  email: string
  user_profile?: {
    bio?: string
  }
  user_urls?: Array<{
    id: number
    url: string
  }>
}

interface PageProps {
  auth?: {
    user?: UserData
  }
  [key: string]: any
}

export default function Profile() {
  // Lấy dữ liệu người dùng từ props với kiểm tra null
  const page = usePage<PageProps>()
  const auth = page.props.auth
  const user = auth?.user || {
    id: '',
    username: '',
    email: '',
    user_profile: { bio: '' },
    user_urls: []
  }

  // Form data
  const form = useForm({
    bio: user.user_profile?.bio || '',
    urls: user.user_urls?.map(item => item.url) || []
  })

  // Avatar upload
  const [isUploading, setIsUploading] = useState(false)
  const [previewUrl, setPreviewUrl] = useState<string | null>(null)
  const fileInputRef = useRef<HTMLInputElement>(null)

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0]
    if (!file) return

    // Tạo preview URL
    const objectUrl = URL.createObjectURL(file)
    setPreviewUrl(objectUrl)

    // Upload file
    const formData = new FormData()
    formData.append('avatar', file)

    setIsUploading(true)

    // Gửi request upload avatar
    fetch('/profile/avatar', {
      method: 'POST',
      body: formData,
      headers: {
        'X-CSRF-TOKEN': document.querySelector('meta[name="csrf-token"]')?.getAttribute('content') || '',
      },
      credentials: 'same-origin',
    })
    .then(response => {
      if (!response.ok) {
        throw new Error('Upload failed')
      }
      return response.json()
    })
    .then(() => {
      // Reload page để hiển thị avatar mới
      window.location.reload()
    })
    .catch(error => {
      console.error('Error uploading avatar:', error)
      // Reset preview
      setPreviewUrl(null)
    })
    .finally(() => {
      setIsUploading(false)
    })
  }

  const triggerFileInput = () => {
    fileInputRef.current?.click()
  }

  // Define sidebar items
  const sidebarItems: SidebarItem[] = [
    { title: 'Hồ sơ', href: '/settings/profile', icon: User },
    { title: 'Tài khoản', href: '/settings/account', icon: CreditCard },
    { title: 'Giao diện', href: '/settings/appearance', icon: Palette },
    { title: 'Thông báo', href: '/settings/notifications', icon: Bell },
    { title: 'Hiển thị', href: '/settings/display', icon: Eye }
  ]

  // Handle form submission
  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()
    form.post('/settings/profile', {
      onSuccess: () => {
        // Hiển thị thông báo thành công
      }
    })
  }

  // Add URL field
  const addUrl = () => {
    form.setData('urls', [...form.data.urls, ''])
  }

  // Remove URL field
  const removeUrl = (index: number) => {
    form.setData('urls', form.data.urls.filter((_, i) => i !== index))
  }

  // Update URL value
  const updateUrl = (index: number, value: string) => {
    const updatedUrls = [...form.data.urls]
    updatedUrls[index] = value
    form.setData('urls', updatedUrls)
  }

  return (
    <>
      <Head title="Hồ sơ cá nhân" />
      <div className="container py-8">
        <div className="grid grid-cols-12 gap-6">
          {/* Sidebar */}
          <div className="col-span-3">
            <nav className="flex flex-col space-y-1">
              {sidebarItems.map((item) => (
                <Link
                  key={item.href}
                  href={item.href}
                  className={`flex items-center rounded-md px-3 py-2 hover:bg-muted ${
                    item.href === '/settings/profile'
                      ? 'bg-muted font-medium text-foreground'
                      : 'text-muted-foreground'
                  }`}
                >
                  <item.icon className="mr-2 h-4 w-4" />
                  {item.title}
                </Link>
              ))}
            </nav>
          </div>

          {/* Content */}
          <div className="col-span-9">
            <Card>
              <CardHeader>
                <CardTitle>Thông tin cá nhân</CardTitle>
                <CardDescription>
                  Đây là cách người khác sẽ nhìn thấy bạn trên trang web.
                </CardDescription>
              </CardHeader>
              <CardContent>
                {/* Avatar section */}
                <div className="mb-6 pb-6 border-b border-border">
                  <Label className="block mb-2">Ảnh đại diện</Label>
                  <div className="flex items-center gap-5">
                    <Avatar className="w-24 h-24">
                      <AvatarImage src={previewUrl || undefined} alt={user.username} />
                      <AvatarFallback>{user.username?.[0]?.toUpperCase()}</AvatarFallback>
                    </Avatar>
                    <div>
                      <input
                        type="file"
                        ref={fileInputRef}
                        onChange={handleFileChange}
                        className="hidden"
                        accept="image/jpeg,image/png,image/jpg"
                      />
                      <Button
                        type="button"
                        variant="outline"
                        onClick={triggerFileInput}
                        disabled={isUploading}
                      >
                        {isUploading ? 'Đang tải lên...' : 'Tải lên ảnh mới'}
                        {!isUploading && <Upload className="ml-2 h-4 w-4" />}
                      </Button>
                      <p className="text-sm text-muted-foreground mt-2">
                        Chấp nhận JPG, PNG. Kích thước tối đa 2MB.
                      </p>
                    </div>
                  </div>
                </div>

                <form onSubmit={handleSubmit} className="space-y-6">
                  {/* Thông tin hiển thị public */}
                  <div className="space-y-2">
                    <p>
                      Đây là tên hiển thị công khai của bạn. Nó có thể là tên thật của bạn hoặc một bút danh. Bạn chỉ có thể thay đổi nội dung này 30 ngày một lần.
                    </p>
                  </div>

                  {/* Chọn email để hiển thị */}
                  <div className="space-y-2">
                    <Label>Email</Label>
                    <Select defaultValue="verified">
                      <SelectTrigger>
                        <SelectValue placeholder="Chọn email đã xác minh để hiển thị" />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="verified">
                          {user.email}
                        </SelectItem>
                      </SelectContent>
                    </Select>
                    <p className="text-sm text-muted-foreground">
                      Bạn có thể quản lý địa chỉ email đã xác minh trong phần cài đặt email.
                    </p>
                  </div>

                  {/* Bio section */}
                  <div className="space-y-2">
                    <Label htmlFor="bio">Giới thiệu</Label>
                    <Textarea
                      id="bio"
                      value={form.data.bio}
                      onChange={(e) => form.setData('bio', e.target.value)}
                      rows={3}
                      placeholder="Viết một vài câu về bản thân"
                    />
                  </div>

                  {/* URLs section */}
                  <div className="space-y-2">
                    <Label>Đường dẫn</Label>
                    <p className="text-sm text-muted-foreground">
                      Thêm liên kết đến website, blog, hoặc mạng xã hội của bạn.
                    </p>

                    <div className="space-y-2">
                      {form.data.urls.map((url, index) => (
                        <div key={index} className="flex gap-2">
                          <Input
                            value={url}
                            onChange={(e) => updateUrl(index, e.target.value)}
                            placeholder="https://example.com"
                            className="flex-1"
                          />
                          <Button
                            type="button"
                            variant="outline"
                            size="sm"
                            onClick={() => removeUrl(index)}
                          >
                            Xóa
                          </Button>
                        </div>
                      ))}
                      <Button
                        type="button"
                        variant="outline"
                        size="sm"
                        onClick={addUrl}
                      >
                        Thêm URL
                      </Button>
                    </div>
                  </div>

                  {/* Mention options */}
                  <div className="space-y-2">
                    <p className="text-sm">
                      Bạn có thể <span className="text-primary">@mention</span> người dùng và tổ chức khác để liên kết đến họ.
                    </p>
                  </div>

                  {/* Submit button */}
                  <div>
                    <Button type="submit">
                      Cập nhật hồ sơ
                    </Button>
                  </div>
                </form>
              </CardContent>
            </Card>
          </div>
        </div>
      </div>
    </>
  )
}

Profile.layout = (page: React.ReactNode) => <AppLayout title="Hồ sơ cá nhân">{page}</AppLayout>

// inertia/pages/settings/profile.svelte
<script lang="ts">
  import { useForm, page } from '@inertiajs/svelte'
  import AppLayout from '@/layouts/app_layout.svelte'
  import Card from '@/components/ui/card.svelte'
  import CardContent from '@/components/ui/card_content.svelte'
  import CardHeader from '@/components/ui/card_header.svelte'
  import CardTitle from '@/components/ui/card_title.svelte'
  import CardDescription from '@/components/ui/card_description.svelte'
  import Button from '@/components/ui/button.svelte'
  import Input from '@/components/ui/input.svelte'
  import Label from '@/components/ui/label.svelte'
  import Textarea from '@/components/ui/textarea.svelte'
  import Select from '@/components/ui/select.svelte'
  import SelectContent from '@/components/ui/select_content.svelte'
  import SelectItem from '@/components/ui/select_item.svelte'
  import SelectTrigger from '@/components/ui/select_trigger.svelte'
  import SelectValue from '@/components/ui/select_value.svelte'
  import Avatar from '@/components/ui/avatar.svelte'
  import AvatarFallback from '@/components/ui/avatar_fallback.svelte'
  import AvatarImage from '@/components/ui/avatar_image.svelte'
  import SettingsSidebar from './components/settings_sidebar.svelte'
  import { Upload } from 'lucide-svelte'

  const user = $derived($page.props.auth?.user || {
    id: '',
    username: '',
    email: '',
    user_profile: { bio: '' },
    user_urls: []
  })

  const form = useForm({
    bio: user.user_profile?.bio || '',
    urls: user.user_urls?.map((item: any) => item.url) || []
  })

  let isUploading = $state(false)
  let previewUrl = $state<string | null>(null)
  let fileInputRef: HTMLInputElement

  function handleFileChange(e: Event) {
    const target = e.target as HTMLInputElement
    const file = target.files?.[0]
    if (!file) return

    const objectUrl = URL.createObjectURL(file)
    previewUrl = objectUrl

    const formData = new FormData()
    formData.append('avatar', file)

    isUploading = true

    fetch('/profile/avatar', {
      method: 'POST',
      body: formData,
      headers: {
        'X-CSRF-TOKEN': document.querySelector('meta[name="csrf-token"]')?.getAttribute('content') || '',
      },
      credentials: 'same-origin',
    })
    .then(response => {
      if (!response.ok) {
        throw new Error('Upload failed')
      }
      return response.json()
    })
    .then(() => {
      window.location.reload()
    })
    .catch(error => {
      console.error('Error uploading avatar:', error)
      previewUrl = null
    })
    .finally(() => {
      isUploading = false
    })
  }

  function triggerFileInput() {
    fileInputRef?.click()
  }

  function handleSubmit(e: Event) {
    e.preventDefault()
    form.post('/settings/profile')
  }

  function addUrl() {
    form.setData('urls', [...form.data.urls, ''])
  }

  function removeUrl(index: number) {
    form.setData('urls', form.data.urls.filter((_: string, i: number) => i !== index))
  }

  function updateUrl(index: number, value: string) {
    const updatedUrls = [...form.data.urls]
    updatedUrls[index] = value
    form.setData('urls', updatedUrls)
  }
</script>

<svelte:head>
  <title>Hồ sơ cá nhân</title>
</svelte:head>

<AppLayout title="Hồ sơ cá nhân">
  <div class="container py-8">
    <div class="grid grid-cols-12 gap-6">
      <div class="col-span-3">
        <SettingsSidebar currentPath="/settings/profile" />
      </div>

      <div class="col-span-9">
        <Card>
          <CardHeader>
            <CardTitle>Thông tin cá nhân</CardTitle>
            <CardDescription>
              Đây là cách người khác sẽ nhìn thấy bạn trên trang web.
            </CardDescription>
          </CardHeader>
          <CardContent>
            <!-- Avatar section -->
            <div class="mb-6 pb-6 border-b border-border">
              <Label class="block mb-2">Ảnh đại diện</Label>
              <div class="flex items-center gap-5">
                <Avatar class="w-24 h-24">
                  <AvatarImage src={previewUrl || undefined} alt={user.username} />
                  <AvatarFallback>{user.username?.[0]?.toUpperCase()}</AvatarFallback>
                </Avatar>
                <div>
                  <input
                    type="file"
                    bind:this={fileInputRef}
                    onchange={handleFileChange}
                    class="hidden"
                    accept="image/jpeg,image/png,image/jpg"
                  />
                  <Button
                    type="button"
                    variant="outline"
                    onclick={triggerFileInput}
                    disabled={isUploading}
                  >
                    {isUploading ? 'Đang tải lên...' : 'Tải lên ảnh mới'}
                    {#if !isUploading}
                      <Upload class="ml-2 h-4 w-4" />
                    {/if}
                  </Button>
                  <p class="text-sm text-muted-foreground mt-2">
                    Chấp nhận JPG, PNG. Kích thước tối đa 2MB.
                  </p>
                </div>
              </div>
            </div>

            <form onsubmit={handleSubmit} class="space-y-6">
              <div class="space-y-2">
                <p>
                  Đây là tên hiển thị công khai của bạn. Nó có thể là tên thật của bạn hoặc một bút danh. Bạn chỉ có thể thay đổi nội dung này 30 ngày một lần.
                </p>
              </div>

              <div class="space-y-2">
                <Label>Email</Label>
                <Select value="verified">
                  <SelectTrigger>
                    <SelectValue placeholder="Chọn email đã xác minh để hiển thị" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="verified">
                      {user.email}
                    </SelectItem>
                  </SelectContent>
                </Select>
                <p class="text-sm text-muted-foreground">
                  Bạn có thể quản lý địa chỉ email đã xác minh trong phần cài đặt email.
                </p>
              </div>

              <div class="space-y-2">
                <Label for="bio">Giới thiệu</Label>
                <Textarea
                  id="bio"
                  value={form.data.bio}
                  oninput={(e) => form.setData('bio', e.currentTarget.value)}
                  rows={3}
                  placeholder="Viết một vài câu về bản thân"
                />
              </div>

              <div class="space-y-2">
                <Label>Đường dẫn</Label>
                <p class="text-sm text-muted-foreground">
                  Thêm liên kết đến website, blog, hoặc mạng xã hội của bạn.
                </p>

                <div class="space-y-2">
                  {#each form.data.urls as url, index}
                    <div class="flex gap-2">
                      <Input
                        value={url}
                        oninput={(e) => { updateUrl(index, e.currentTarget.value); }}
                        placeholder="https://example.com"
                        class="flex-1"
                      />
                      <Button
                        type="button"
                        variant="outline"
                        size="sm"
                        onclick={() => { removeUrl(index); }}
                      >
                        Xóa
                      </Button>
                    </div>
                  {/each}
                  <Button
                    type="button"
                    variant="outline"
                    size="sm"
                    onclick={addUrl}
                  >
                    Thêm URL
                  </Button>
                </div>
              </div>

              <div class="space-y-2">
                <p class="text-sm">
                  Bạn có thể <span class="text-primary">@mention</span> người dùng và tổ chức khác để liên kết đến họ.
                </p>
              </div>

              <div>
                <Button type="submit">
                  Cập nhật hồ sơ
                </Button>
              </div>
            </form>
          </CardContent>
        </Card>
      </div>
    </div>
  </div>
</AppLayout>
