// inertia/pages/admin/organizations/index.svelte
<script lang="ts">
  import { router } from '@inertiajs/svelte'
  import AdminLayout from '@/layouts/admin_layout.svelte'
  import Card from '@/components/ui/card.svelte'
  import CardContent from '@/components/ui/card_content.svelte'
  import CardDescription from '@/components/ui/card_description.svelte'
  import CardHeader from '@/components/ui/card_header.svelte'
  import CardTitle from '@/components/ui/card_title.svelte'
  import Button from '@/components/ui/button.svelte'
  import Input from '@/components/ui/input.svelte'
  import {
    Building2,
    Users,
    FolderKanban,
    Crown,
    Calendar,
    Search
  } from 'lucide-svelte'

  interface Props {
    organizations: {
      id: string
      name: string
      description: string | null
      owner: {
        id: string
        username: string
        email: string
      }
      plan: string | null
      created_at: string
      updated_at: string
      _count: {
        members: number
        projects: number
      }
    }[]
    pagination: {
      total: number
      perPage: number
      currentPage: number
      lastPage: number
    }
    filters: {
      search?: string
      plan?: string
    }
  }

  const props: Props = $props()
  const organizations = $derived(props.organizations)
  const pagination = $derived(props.pagination)
  const filters = $derived(props.filters)

  let searchValue = $state('')

  $effect(() => {
    searchValue = filters.search || ''
  })

  function handleSearch() {
    router.get(
      '/admin/organizations',
      {
        search: searchValue,
        plan: filters.plan,
        page: 1,
      },
      {
        preserveState: true,
        preserveScroll: true,
      }
    )
  }

  function formatDate(dateString: string) {
    return new Date(dateString).toLocaleDateString('vi-VN', {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
    })
  }
</script>

<AdminLayout>
  <div class="space-y-6">
    <div class="flex items-center justify-between">
      <div>
        <h1 class="text-3xl font-bold tracking-tight">Tổ chức</h1>
        <p class="text-muted-foreground">Theo dõi danh sách tổ chức và tín hiệu vận hành ở cấp hệ thống.</p>
      </div>
    </div>

    <!-- Filters -->
    <Card>
      <CardContent class="pt-6">
        <div class="flex gap-4">
          <div class="flex-1 relative">
            <Search class="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
            <Input
              type="search"
              placeholder="Tìm theo tên tổ chức..."
              class="pl-10"
              bind:value={searchValue}
              onkeydown={(e: KeyboardEvent) => {
                if (e.key === 'Enter') handleSearch()
              }}
            />
          </div>
          <Button onclick={handleSearch}>Tìm kiếm</Button>
        </div>
      </CardContent>
    </Card>

    <!-- Organizations Grid -->
    <div class="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
      {#each organizations as org}
        <Card class="hover:shadow-lg transition-shadow">
          <CardHeader>
            <div class="flex items-start justify-between">
              <div class="flex items-center gap-3 flex-1 min-w-0">
                <div class="flex-shrink-0 h-12 w-12 rounded-lg bg-primary/10 flex items-center justify-center">
                  <Building2 class="h-6 w-6 text-primary" />
                </div>
                <div class="min-w-0 flex-1">
                  <CardTitle class="text-lg truncate">{org.name}</CardTitle>
                </div>
              </div>
            </div>
            {#if org.description}
              <CardDescription class="line-clamp-2 mt-2">
                {org.description}
              </CardDescription>
            {/if}
          </CardHeader>
          <CardContent>
            <div class="space-y-3">
              <!-- Owner -->
              <div class="flex items-center gap-2 text-sm">
                <Crown class="h-4 w-4 text-amber-500" />
                <span class="text-muted-foreground">Owner:</span>
                <span class="font-medium">{org.owner.username}</span>
              </div>

              <!-- Stats -->
              <div class="grid grid-cols-2 gap-3 pt-2 border-t">
                <div class="flex items-center gap-2 text-sm">
                  <Users class="h-4 w-4 text-blue-500" />
                  <span class="font-medium">{org._count.members}</span>
                  <span class="text-muted-foreground">thành viên</span>
                </div>
                <div class="flex items-center gap-2 text-sm">
                  <FolderKanban class="h-4 w-4 text-green-500" />
                  <span class="font-medium">{org._count.projects}</span>
                  <span class="text-muted-foreground">dự án</span>
                </div>
              </div>

              <!-- Created Date -->
              <div class="flex items-center gap-2 text-xs text-muted-foreground pt-2 border-t">
                <Calendar class="h-3 w-3" />
                <span>Tạo ngày {formatDate(org.created_at)}</span>
              </div>

              <!-- Actions -->
              <div class="flex gap-2 pt-2">
                <Button
                  variant="outline"
                  size="sm"
                  class="flex-1"
                  onclick={() => {
                    router.visit(`/admin/organizations/${org.id}`)
                  }}
                >
                  Xem chi tiết
                </Button>
              </div>
            </div>
          </CardContent>
        </Card>
      {/each}
    </div>

    <!-- Empty State -->
    {#if organizations.length === 0}
      <Card>
        <CardContent class="py-12 text-center">
          <Building2 class="h-12 w-12 text-muted-foreground mx-auto mb-4" />
          <h3 class="text-lg font-semibold mb-2">Không tìm thấy tổ chức</h3>
          <p class="text-muted-foreground">
            {filters.search ? 'Thử đổi từ khóa tìm kiếm.' : 'Hệ thống chưa có tổ chức nào.'}
          </p>
        </CardContent>
      </Card>
    {/if}

    <!-- Pagination -->
    {#if pagination.lastPage > 1}
      <Card>
        <CardContent class="py-4">
          <div class="flex items-center justify-between">
            <div class="text-sm text-muted-foreground">
              Hiển thị <span class="font-medium">{(pagination.currentPage - 1) * pagination.perPage + 1}</span>
              đến <span class="font-medium">{Math.min(pagination.currentPage * pagination.perPage, pagination.total)}</span>
              trên tổng <span class="font-medium">{pagination.total}</span> tổ chức
            </div>
            <div class="flex gap-2">
              <Button
                variant="outline"
                size="sm"
                disabled={pagination.currentPage === 1}
                onclick={() => {
                  router.visit(`/admin/organizations?page=${pagination.currentPage - 1}`)
                }}
              >
                Trước
              </Button>
              <Button
                variant="outline"
                size="sm"
                disabled={pagination.currentPage === pagination.lastPage}
                onclick={() => {
                  router.visit(`/admin/organizations?page=${pagination.currentPage + 1}`)
                }}
              >
                Sau
              </Button>
            </div>
          </div>
        </CardContent>
      </Card>
    {/if}
  </div>
</AdminLayout>

// inertia/pages/organizations/index.tsx
import React from 'react'
import { Head, Link } from '@inertiajs/react'
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Plus, Users, Building, ArrowRight } from 'lucide-react'
import AppLayout from '@/layouts/app_layout'

interface Organization {
  id: number
  name: string
  description: string | null
  address: string | null
  email: string | null
  phone: string | null
  website: string | null
  logo_url: string | null
  role_id: number
  role_name: string
  created_at: string
  updated_at: string
}

interface Props {
  organizations: Organization[]
  currentOrganizationId: number | null
}

export default function OrganizationsList({ organizations, currentOrganizationId }: Props) {
  return (
    <>
      <Head title="Danh sách tổ chức" />

      <div className="container py-6">
        <div className="flex justify-between items-center mb-6">
          <div>
            <h1 className="text-3xl font-bold tracking-tight">Tổ chức của bạn</h1>
            <p className="text-muted-foreground mt-1">
              Quản lý và tham gia các tổ chức trong hệ thống
            </p>
          </div>
          <Button asChild>
            <Link href="/organizations/create">
              <Plus className="mr-2 h-4 w-4" /> Tạo tổ chức mới
            </Link>
          </Button>
        </div>

        {organizations.length === 0 ? (
          <div className="flex flex-col items-center justify-center py-12 text-center">
            <div className="rounded-full bg-muted p-6 mb-4">
              <Building className="h-12 w-12 text-muted-foreground" />
            </div>
            <h2 className="text-xl font-semibold">Bạn chưa tham gia tổ chức nào</h2>
            <p className="text-muted-foreground mt-2 max-w-md">
              Bạn cần tham gia hoặc tạo một tổ chức mới để sử dụng đầy đủ các tính năng của hệ thống.
            </p>
            <Button className="mt-4" asChild>
              <Link href="/organizations/create">
                <Plus className="mr-2 h-4 w-4" /> Tạo tổ chức mới
              </Link>
            </Button>
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {organizations.map((org) => (
              <Card key={org.id} className={`overflow-hidden transition-all duration-200 ${
                currentOrganizationId === org.id ? 'ring-2 ring-primary' : ''
              }`}>
                <CardHeader className="pb-2">
                  <div className="flex justify-between items-start">
                    <CardTitle className="text-xl">
                      {org.name}
                    </CardTitle>
                    {currentOrganizationId === org.id && (
                      <Badge variant="outline" className="bg-primary/10 text-primary">Hiện tại</Badge>
                    )}
                  </div>
                  <CardDescription className="line-clamp-2">
                    {org.description || 'Chưa có mô tả'}
                  </CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="flex items-center text-sm text-muted-foreground mb-2">
                    <Users className="h-4 w-4 mr-2" />
                    <span>Vai trò: {org.role_name}</span>
                  </div>
                  {org.website && (
                    <div className="text-sm text-muted-foreground truncate">
                      {org.website}
                    </div>
                  )}
                </CardContent>
                <CardFooter className="flex justify-between pt-2">
                  <Button asChild variant="outline">
                    <Link href={`/organizations/${org.id}`}>
                      Xem chi tiết
                    </Link>
                  </Button>
                  {currentOrganizationId !== org.id && (
                    <Button asChild variant="secondary">
                      <Link href={`/organizations/switch/${org.id}`}>
                        Chọn <ArrowRight className="ml-2 h-4 w-4" />
                      </Link>
                    </Button>
                  )}
                </CardFooter>
              </Card>
            ))}
          </div>
        )}
      </div>
    </>
  )
}

OrganizationsList.layout = (page: React.ReactNode) => <AppLayout title="Danh sách tổ chức">{page}</AppLayout>
