// inertia/pages/projects/show.tsx
import React, { useState } from 'react'
import { Head } from '@inertiajs/react'
import { router } from '@inertiajs/react'
import AppLayout from '@/layouts/app_layout'
import { Button } from '@/components/ui/button'
import { Card, CardHeader, CardTitle, CardContent } from '@/components/ui/card'
import { Table, TableHeader, TableBody, TableRow, TableHead, TableCell } from '@/components/ui/table'
import { ProjectShowProps, Task } from './types'
import useTranslation from '@/hooks/use_translation'
import { formatDate } from '@/lib/utils'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar'
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'

export default function ProjectShow({ project, members, tasks, permissions, auth }: ProjectShowProps) {
  const { t } = useTranslation()
  const [addMemberOpen, setAddMemberOpen] = useState(false)
  const [newMemberEmail, setNewMemberEmail] = useState('')
  
  const handleDeleteProject = () => {
    if (confirm(t('common.confirm_delete', {}, 'Bạn có chắc chắn muốn xóa?'))) {
      router.delete(`/projects/${project.id}`)
    }
  }
  
  const handleAddMember = (e: React.FormEvent) => {
    e.preventDefault()
    router.post('/projects/members', {
      project_id: project.id,
      email: newMemberEmail
    })
    setNewMemberEmail('')
    setAddMemberOpen(false)
  }
  
  const getInitials = (name: string) => {
    return name
      .split(' ')
      .map(part => part[0])
      .join('')
      .toUpperCase()
      .substring(0, 2)
  }
  
  return (
    <AppLayout title={project.name}>
      <Head title={project.name} />

      <div className="p-4 sm:p-6 space-y-6">
        <div className="flex justify-between items-center">
          <div>
            <h1 className="text-2xl font-bold">{project.name}</h1>
            <p className="text-muted-foreground">{project.organization_name}</p>
          </div>
          
          <div className="flex items-center gap-2">
            {permissions.isCreator || permissions.isManager ? (
              <Button 
                variant="destructive" 
                onClick={handleDeleteProject}
              >
                {t('common.delete', {}, 'Xóa')}
              </Button>
            ) : null}
            
            <Button 
              onClick={() => router.visit('/projects')}
              variant="outline"
            >
              {t('common.back', {}, 'Quay lại')}
            </Button>
          </div>
        </div>
        
        <Tabs defaultValue="details">
          <TabsList>
            <TabsTrigger value="details">{t('project.details', {}, 'Chi tiết')}</TabsTrigger>
            <TabsTrigger value="members">{t('project.members', {}, 'Thành viên')}</TabsTrigger>
            <TabsTrigger value="tasks">{t('project.tasks', {}, 'Công việc')}</TabsTrigger>
          </TabsList>
          
          <TabsContent value="details" className="mt-4">
            <Card>
              <CardContent className="pt-6">
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  <div>
                    <h3 className="text-sm font-medium text-muted-foreground mb-1">
                      {t('project.description', {}, 'Mô tả')}
                    </h3>
                    <p>{project.description || t('common.not_available', {}, 'Không có')}</p>
                  </div>
                  
                  <div>
                    <h3 className="text-sm font-medium text-muted-foreground mb-1">
                      {t('project.status', {}, 'Trạng thái')}
                    </h3>
                    <div className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-blue-100 text-blue-800">
                      {project.status || t('common.not_available', {}, 'Không có')}
                    </div>
                  </div>
                  
                  <div>
                    <h3 className="text-sm font-medium text-muted-foreground mb-1">
                      {t('project.start_date', {}, 'Ngày bắt đầu')}
                    </h3>
                    <p>{project.start_date ? formatDate(project.start_date) : t('common.not_available', {}, 'Không có')}</p>
                  </div>
                  
                  <div>
                    <h3 className="text-sm font-medium text-muted-foreground mb-1">
                      {t('project.end_date', {}, 'Ngày kết thúc')}
                    </h3>
                    <p>{project.end_date ? formatDate(project.end_date) : t('common.not_available', {}, 'Không có')}</p>
                  </div>
                  
                  <div>
                    <h3 className="text-sm font-medium text-muted-foreground mb-1">
                      {t('project.creator', {}, 'Người tạo')}
                    </h3>
                    <p>{project.creator_name || t('common.not_available', {}, 'Không có')}</p>
                  </div>
                  
                  <div>
                    <h3 className="text-sm font-medium text-muted-foreground mb-1">
                      {t('project.manager', {}, 'Quản lý')}
                    </h3>
                    <p>{project.manager_name || t('common.not_available', {}, 'Không có')}</p>
                  </div>
                </div>
              </CardContent>
            </Card>
          </TabsContent>
          
          <TabsContent value="members" className="mt-4">
            <Card>
              <CardHeader className="flex flex-row items-center justify-between">
                <CardTitle>{t('project.members', {}, 'Thành viên')}</CardTitle>
                {(permissions.isCreator || permissions.isManager) && (
                  <Dialog open={addMemberOpen} onOpenChange={setAddMemberOpen}>
                    <DialogTrigger asChild>
                      <Button size="sm">
                        {t('project.add_member', {}, 'Thêm thành viên')}
                      </Button>
                    </DialogTrigger>
                    <DialogContent>
                      <DialogHeader>
                        <DialogTitle>{t('project.add_member', {}, 'Thêm thành viên')}</DialogTitle>
                      </DialogHeader>
                      <form onSubmit={handleAddMember} className="space-y-4">
                        <div className="space-y-2">
                          <Label htmlFor="email">{t('common.email', {}, 'Email')}</Label>
                          <Input 
                            id="email" 
                            type="email" 
                            value={newMemberEmail}
                            onChange={(e) => setNewMemberEmail(e.target.value)}
                            placeholder="email@example.com"
                            required
                          />
                        </div>
                        <Button type="submit">{t('common.add', {}, 'Thêm')}</Button>
                      </form>
                    </DialogContent>
                  </Dialog>
                )}
              </CardHeader>
              <CardContent>
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                  {members.length === 0 ? (
                    <p className="col-span-full text-center py-4 text-muted-foreground">
                      {t('project.no_members', {}, 'Chưa có thành viên nào')}
                    </p>
                  ) : (
                    members.map((member) => (
                      <div key={member.id} className="flex items-center space-x-3 p-3 border rounded-md">
                        <Avatar>
                          <AvatarImage src={member.avatar_url} />
                          <AvatarFallback>{getInitials(member.full_name)}</AvatarFallback>
                        </Avatar>
                        <div>
                          <p className="font-medium">{member.full_name}</p>
                          <p className="text-sm text-muted-foreground">{member.email}</p>
                          <p className="text-xs text-muted-foreground">{member.role}</p>
                        </div>
                      </div>
                    ))
                  )}
                </div>
              </CardContent>
            </Card>
          </TabsContent>
          
          <TabsContent value="tasks" className="mt-4">
            <Card>
              <CardHeader className="flex flex-row items-center justify-between">
                <CardTitle>{t('project.tasks', {}, 'Công việc')}</CardTitle>
                <Button size="sm" onClick={() => router.visit('/tasks')}>
                  {t('project.view_all_tasks', {}, 'Xem tất cả công việc')}
                </Button>
              </CardHeader>
              <CardContent>
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead>{t('task.title', {}, 'Tiêu đề')}</TableHead>
                      <TableHead>{t('task.status', {}, 'Trạng thái')}</TableHead>
                      <TableHead>{t('task.priority', {}, 'Độ ưu tiên')}</TableHead>
                      <TableHead>{t('task.assignee', {}, 'Người thực hiện')}</TableHead>
                      <TableHead>{t('task.due_date', {}, 'Hạn chót')}</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {tasks.length === 0 ? (
                      <TableRow>
                        <TableCell colSpan={5} className="text-center py-4">
                          {t('project.no_tasks', {}, 'Chưa có công việc nào')}
                        </TableCell>
                      </TableRow>
                    ) : (
                      tasks.map((task: Task) => (
                        <TableRow key={task.id}>
                          <TableCell className="font-medium">{task.title}</TableCell>
                          <TableCell>
                            <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-blue-100 text-blue-800">
                              {task.status}
                            </span>
                          </TableCell>
                          <TableCell>
                            <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-yellow-100 text-yellow-800">
                              {task.priority || '-'}
                            </span>
                          </TableCell>
                          <TableCell>{task.assignee_name || '-'}</TableCell>
                          <TableCell>{task.due_date ? formatDate(task.due_date) : '-'}</TableCell>
                        </TableRow>
                      ))
                    )}
                  </TableBody>
                </Table>
              </CardContent>
            </Card>
          </TabsContent>
        </Tabs>
      </div>
    </AppLayout>
  )
}

// inertia/pages/organizations/show.svelte
<script lang="ts">
  import { Link } from '@inertiajs/svelte'
  import { ArrowLeft, Building, Mail, MapPin, Phone, Globe, Calendar } from 'lucide-svelte'

  import Avatar from '@/components/ui/avatar.svelte'
  import AvatarFallback from '@/components/ui/avatar_fallback.svelte'
  import AvatarImage from '@/components/ui/avatar_image.svelte'
  import Button from '@/components/ui/button.svelte'
  import Card from '@/components/ui/card.svelte'
  import CardContent from '@/components/ui/card_content.svelte'
  import CardDescription from '@/components/ui/card_description.svelte'
  import CardHeader from '@/components/ui/card_header.svelte'
  import CardTitle from '@/components/ui/card_title.svelte'
  import Table from '@/components/ui/table.svelte'
  import TableBody from '@/components/ui/table_body.svelte'
  import TableCell from '@/components/ui/table_cell.svelte'
  import TableHead from '@/components/ui/table_head.svelte'
  import TableHeader from '@/components/ui/table_header.svelte'
  import TableRow from '@/components/ui/table_row.svelte'
  import Tabs from '@/components/ui/tabs.svelte'
  import TabsContent from '@/components/ui/tabs_content.svelte'
  import TabsList from '@/components/ui/tabs_list.svelte'
  import TabsTrigger from '@/components/ui/tabs_trigger.svelte'
  import AppLayout from '@/layouts/app_layout.svelte'
  import { formatDate } from '@/lib/utils'

  interface Organization {
    id: string
    name: string
    description: string | null
    address: string | null
    email: string | null
    phone: string | null
    website: string | null
    logo_url: string | null
    created_at: string
    updated_at: string
  }

  interface Member {
    id: string
    username: string
    email: string
    org_role: string
    role_name: string
  }

  interface Props {
    organization: Organization
    members: Member[]
    userRole: string
  }

  const { organization, members, userRole }: Props = $props()

  // Check if user has admin permissions
  const isAdmin = $derived(userRole === 'org_owner' || userRole === 'org_admin')
  // Kiểm tra nếu người dùng là owner của tổ chức
  const isSuperAdmin = $derived(userRole === 'org_owner')
</script>

<svelte:head>
  <title>{organization.name}</title>
</svelte:head>

<AppLayout title="Chi tiết tổ chức">
  <div class="container py-6">
    <div class="mb-6">
      <Button variant="ghost" class="pl-0">
        <Link href="/organizations">
          <ArrowLeft class="mr-2 h-4 w-4" /> Quay lại danh sách
        </Link>
      </Button>
    </div>

    <div class="grid grid-cols-1 lg:grid-cols-3 gap-6">
      <div class="lg:col-span-1">
        <Card>
          <CardHeader>
            <div class="flex justify-center mb-4">
              {#if organization.logo_url}
                <Avatar class="h-24 w-24">
                  <AvatarImage src={organization.logo_url} alt={organization.name} />
                  <AvatarFallback>{organization.name.substring(0, 2)}</AvatarFallback>
                </Avatar>
              {:else}
                <div class="h-24 w-24 rounded-full bg-muted flex items-center justify-center">
                  <Building class="h-12 w-12 text-muted-foreground" />
                </div>
              {/if}
            </div>
            <CardTitle class="text-center text-2xl">{organization.name}</CardTitle>
            <CardDescription class="text-center">
              {organization.description ?? 'Chưa có mô tả'}
            </CardDescription>
          </CardHeader>

          <CardContent class="space-y-4">
            {#if organization.address}
              <div class="flex items-center">
                <MapPin class="h-4 w-4 mr-2 text-muted-foreground" />
                <span>{organization.address}</span>
              </div>
            {/if}
            {#if organization.email}
              <div class="flex items-center">
                <Mail class="h-4 w-4 mr-2 text-muted-foreground" />
                <span>{organization.email}</span>
              </div>
            {/if}
            {#if organization.phone}
              <div class="flex items-center">
                <Phone class="h-4 w-4 mr-2 text-muted-foreground" />
                <span>{organization.phone}</span>
              </div>
            {/if}
            {#if organization.website}
              <div class="flex items-center">
                <Globe class="h-4 w-4 mr-2 text-muted-foreground" />
                <span>{organization.website}</span>
              </div>
            {/if}
            <div class="flex items-center">
              <Calendar class="h-4 w-4 mr-2 text-muted-foreground" />
              <span>Ngày tạo: {formatDate(organization.created_at)}</span>
            </div>
          </CardContent>
        </Card>
      </div>

      <div class="lg:col-span-2">
        <Tabs value="members" class="w-full">
          <TabsList class="w-full">
            <TabsTrigger value="members" class="flex-1">
              Thành viên ({members.length})
            </TabsTrigger>
            <TabsTrigger value="projects" class="flex-1">
              Dự án
            </TabsTrigger>
          </TabsList>

          <TabsContent value="members">
            <Card>
              <CardHeader>
                <div class="flex justify-between items-center">
                  <CardTitle>Danh sách thành viên</CardTitle>
                  {#if isAdmin}
                    <Link href="/org/invitations/invitations">
                      <Button size="sm">Mời thành viên</Button>
                    </Link>
                  {/if}
                </div>
              </CardHeader>
              <CardContent>
                {#if members.length === 0}
                  <div class="text-center py-6 text-muted-foreground">
                    Tổ chức chưa có thành viên nào
                  </div>
                {:else}
                  <Table>
                    <TableHeader>
                      <TableRow>
                        <TableHead>Tên</TableHead>
                        <TableHead>Email</TableHead>
                        <TableHead>Vai trò</TableHead>
                        {#if isSuperAdmin}
                          <TableHead class="w-[100px]">Thao tác</TableHead>
                        {/if}
                      </TableRow>
                    </TableHeader>
                    <TableBody>
                      {#each members as member (member.id)}
                        <TableRow>
                          <TableCell>
                            <div class="font-medium">{member.username || member.email}</div>
                            <div class="text-sm text-muted-foreground">@{member.username}</div>
                          </TableCell>
                          <TableCell>{member.email}</TableCell>
                          <TableCell>{member.role_name}</TableCell>
                          {#if isSuperAdmin}
                            <TableCell>
                              <Link href="/users/{member.id}">
                                <Button variant="ghost" size="sm">Xem user</Button>
                              </Link>
                            </TableCell>
                          {/if}
                        </TableRow>
                      {/each}
                    </TableBody>
                  </Table>
                {/if}
              </CardContent>
            </Card>
          </TabsContent>

          <TabsContent value="projects">
            <Card>
              <CardHeader>
                <CardTitle>Dự án</CardTitle>
                <CardDescription>
                  Quản lý dự án đã được tách sang namespace mới để đồng nhất với kiến trúc user/admin/org.
                </CardDescription>
              </CardHeader>
              <CardContent>
                <div class="flex flex-col items-center gap-3 py-6 text-center text-muted-foreground">
                  <p>Mở màn dự án mới trong namespace chuẩn để thao tác tiếp.</p>
                  <div class="flex flex-wrap justify-center gap-2">
                    <Link href="/org/projects">
                      <Button variant="outline">Quản trị dự án tổ chức</Button>
                    </Link>
                    <Link href="/projects">
                      <Button variant="outline">Danh sách dự án tổng quát</Button>
                    </Link>
                  </div>
                </div>
              </CardContent>
            </Card>
          </TabsContent>
        </Tabs>
      </div>
    </div>
  </div>
</AppLayout>
