// inertia/apps/user/modules/users/components/users_list.svelte
<script lang="ts">
  import { Link } from '@inertiajs/svelte'

  import Button from '@/apps/user/shared/ui/button.svelte'
  import Table from '@/apps/user/shared/ui/table.svelte'
  import TableBody from '@/apps/user/shared/ui/table_body.svelte'
  import TableCell from '@/apps/user/shared/ui/table_cell.svelte'
  import TableHead from '@/apps/user/shared/ui/table_head.svelte'
  import TableHeader from '@/apps/user/shared/ui/table_header.svelte'
  import TableRow from '@/apps/user/shared/ui/table_row.svelte'
  import UnifiedOffsetPagination from '@/apps/user/shared/ui/unified_offset_pagination.svelte'
  import { useTranslation } from '@/apps/user/shared/stores/translation.svelte'

  import type { UserDirectoryRecord, UsersProps } from '../types'
  import { getUserDisplayName, getUserOrganizationRole } from '../utils/user_utils'

  interface Props {
    users: UsersProps['users']
    pagination: UsersProps['pagination']
    filters: UsersProps['filters']
    currentUserId: string
    isSuperAdmin: boolean
    onEditPermissions: (user: UserDirectoryRecord) => void
    onDeleteUser: (user: UserDirectoryRecord) => void
  }

  const {
    users,
    pagination,
    filters,
    currentUserId,
    isSuperAdmin,
    onEditPermissions,
    onDeleteUser
  }: Props = $props()
  const { t } = useTranslation()
</script>

<div class="rounded-md border">
  <Table>
    <TableHeader>
      <TableRow>
        <TableHead>{t('user.name', {}, 'Name')}</TableHead>
        <TableHead>{t('user.email', {}, 'Email')}</TableHead>
        <TableHead>{t('user.role', {}, 'Role')}</TableHead>
        <TableHead>{t('user.status', {}, 'Status')}</TableHead>
        <TableHead class="text-right">{t('common.actions', {}, 'Actions')}</TableHead>
      </TableRow>
    </TableHeader>
    <TableBody>
      {#each users as user (user.id)}
        <TableRow>
          <TableCell>{getUserDisplayName(user)}</TableCell>
          <TableCell>{user.email}</TableCell>
          <TableCell>{getUserOrganizationRole(user)}</TableCell>
          <TableCell>{t(`user.status_${(user.status || '').toLowerCase()}`, {}, user.status || '')}</TableCell>
          <TableCell class="text-right">
            {#if user.id !== currentUserId}
              {#if isSuperAdmin}
                <Button
                  variant="outline"
                  size="sm"
                  class="mr-2"
                  onclick={() => { onEditPermissions(user) }}
                >
                  {t('user.edit_role', {}, 'Edit role')}
                </Button>
                <Button
                  variant="destructive"
                  size="sm"
                  onclick={() => { onDeleteUser(user) }}
                >
                  {t('user.remove_from_org', {}, 'Remove from organization')}
                </Button>
              {/if}
            {:else}
              <Link href={`/users/${user.id}/edit`}>
                <Button variant="outline" size="sm" class="mr-2">
                  {t('user.my_account', {}, 'My account')}
                </Button>
              </Link>
            {/if}
          </TableCell>
        </TableRow>
      {/each}
    </TableBody>
  </Table>
</div>

{#if true}
  <div class="mt-4">
    <UnifiedOffsetPagination
      {pagination}
      baseUrl="/users"
      queryParams={filters}
    />
  </div>
{/if}

// inertia/pages/users/components/UsersList.tsx

import { Link } from '@inertiajs/react'
import { Button } from '@/components/ui/button'
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow
} from '@/components/ui/table'
import { Pagination } from '@/components/ui/pagination'
import useTranslation from '@/hooks/use_translation'
import  type { User, UsersProps } from '../types'
import { getUserDisplayName, getUserOrganizationRole } from '../utils/user_utils'

type UsersListProps = {
  users: UsersProps['users']
  filters: UsersProps['filters']
  currentUserId: number
  isSuperAdmin: boolean
  onEditPermissions: (user: User) => void
  onDeleteUser: (user: User) => void
}

export default function UsersList({
  users,
  filters,
  currentUserId,
  isSuperAdmin,
  onEditPermissions,
  onDeleteUser
}: UsersListProps) {
  const { t } = useTranslation()

  return (
    <>
      <div className="rounded-md border">
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>{t('user.name', {}, "Tên")}</TableHead>
              <TableHead>{t('user.email', {}, "Email")}</TableHead>
              <TableHead>{t('user.role', {}, "Vai trò")}</TableHead>
              <TableHead>{t('user.status', {}, "Trạng thái")}</TableHead>
              <TableHead className="text-right">{t('common.actions', {}, "Thao tác")}</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {users.data.map((user) => (
              <TableRow key={user.id}>
                <TableCell>{getUserDisplayName(user)}</TableCell>
                <TableCell>{user.email}</TableCell>
                <TableCell>{getUserOrganizationRole(user)}</TableCell>
                <TableCell>{t(`user.status_${user.status?.name.toLowerCase()}`, {}, user.status?.name)}</TableCell>
                <TableCell className="text-right">
                  {/* Chỉ dành cho phát triển */}
                  {import.meta.env.NODE_ENV === 'development' && (
                    <div className="hidden">
                      {/* Không hiển thị debug info trong UI */}
                    </div>
                  )}

                  {user.id !== currentUserId && (
                    <>
                      {/* Kiểm tra vai trò superadmin trong tổ chức */}
                      {isSuperAdmin && (
                        <>
                          <Button
                            variant="outline"
                            size="sm"
                            className="mr-2"
                            onClick={() => { onEditPermissions(user); }}
                          >
                            {t('user.edit_role', {}, "Sửa vai trò")}
                          </Button>
                        </>
                      )}

                      {/* Kiểm tra vai trò superadmin trong tổ chức */}
                      {isSuperAdmin && (
                        <Button
                          variant="destructive"
                          size="sm"
                          onClick={() => { onDeleteUser(user); }}
                        >
                          {t('user.remove_from_org', {}, "Xóa khỏi tổ chức")}
                        </Button>
                      )}
                    </>
                  )}
                  {user.id === currentUserId && (
                    <Link href={`/users/${user.id}/edit`}>
                      <Button variant="outline" size="sm" className="mr-2">
                        {t('user.my_account', {}, "Tài khoản của tôi")}
                      </Button>
                    </Link>
                  )}
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </div>

      {users.meta.last_page > 1 && (
        <div className="mt-4">
          <Pagination
            currentPage={users.meta.current_page}
            totalPages={users.meta.last_page}
            baseUrl="/users"
            queryParams={filters}
          />
        </div>
      )}
    </>
  )
}
