// inertia/pages/users/components/UserSearchForm.tsx
import React from 'react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import useTranslation from '@/hooks/use_translation'

interface UserSearchFormProps {
  search: string
  setSearch: (value: string) => void
  handleSearch: (e: React.FormEvent) => void
}

export default function UserSearchForm({ search, setSearch, handleSearch }: UserSearchFormProps) {
  const { t } = useTranslation()
  
  return (
    <form onSubmit={handleSearch} className="flex items-center gap-4">
      <Input 
        placeholder={t('user.search_users', {}, "Tìm kiếm người dùng...")}
        className="max-w-sm" 
        value={search}
        onChange={(e) => setSearch(e.target.value)}
      />
      <Button variant="outline" type="submit">{t('common.search', {}, "Tìm kiếm")}</Button>
    </form>
  )
}

// inertia/pages/users/components/UserSearchForm.svelte
<script lang="ts">
  import Button from '@/components/ui/button.svelte'
  import Input from '@/components/ui/input.svelte'

  interface Props {
    search: string
    setSearch: (value: string) => void
    handleSearch: (e: Event) => void
  }

  const { search, setSearch, handleSearch }: Props = $props()
</script>

<form onsubmit={handleSearch} class="flex items-center gap-4">
  <Input
    placeholder="Tìm kiếm người dùng..."
    class="max-w-sm"
    value={search}
    oninput={(e) => { setSearch((e.target as HTMLInputElement).value); }}
  />
  <Button variant="outline" type="submit">Tìm kiếm</Button>
</form>
