// inertia/pages/tasks/components/task_list/cells/child/assignee_cell.svelte
<script lang="ts">
  import { User } from 'lucide-svelte'

  interface Props {
    assignee?: {
      id?: string
      username?: string
      email?: string
    }
  }

  const { assignee }: Props = $props()
</script>

<div class="flex items-center gap-1">
  <User class="h-3 w-3 text-muted-foreground flex-shrink-0" />
  {#if assignee}
    <span class="text-[11px] truncate">
      {assignee.username || assignee.email || `User #${assignee.id}`}
    </span>
  {:else}
    <span class="text-[11px] text-muted-foreground">Chưa gán</span>
  {/if}
</div>

// inertia/pages/tasks/components/task_list/cells/child/assignee_cell.tsx
import React from 'react'
import { User } from 'lucide-react'

interface AssigneeCellProps {
  assignee?: any
}

export function AssigneeCell({ assignee }: AssigneeCellProps) {
  return (
    <div className="flex items-center gap-1">
      <User className="h-3 w-3 text-muted-foreground flex-shrink-0" />
      {assignee ? (
        <span className="text-[11px] truncate">
          {assignee.username || assignee.email || 'Chưa gán'}
        </span>
      ) : (
        <span className="text-[11px] text-muted-foreground">Chưa gán</span>
      )}
    </div>
  )
}
