// inertia/pages/tasks/components/task_list/cells/child/date_cell.svelte
<script lang="ts">
  import { Clock } from 'lucide-svelte'

  interface Props {
    createdAt?: string
    formatDate: (dateString: string) => string
  }

  const { createdAt, formatDate }: Props = $props()
</script>

<div class="flex items-center gap-1">
  <Clock class="h-3 w-3 text-muted-foreground flex-shrink-0" />
  {#if createdAt}
    <span class="text-[11px]">{formatDate(createdAt)}</span>
  {:else}
    <span class="text-[11px] text-muted-foreground">-</span>
  {/if}
</div>

// inertia/pages/tasks/components/task_list/cells/child/date_cell.tsx
import React from 'react'
import { Clock } from 'lucide-react'

interface DateCellProps {
  createdAt?: string
  formatDate: (dateString: string) => string
}

export function DateCell({ createdAt, formatDate }: DateCellProps) {
  return (
    <div className="flex items-center gap-1">
      <Clock className="h-3 w-3 text-muted-foreground flex-shrink-0" />
      {createdAt ? (
        <span className="text-[11px]">{formatDate(createdAt)}</span>
      ) : (
        <span className="text-[11px] text-muted-foreground">-</span>
      )}
    </div>
  )
}
