// inertia/pages/tasks/components/task_list/cells/date_cell.tsx

import type { Task } from '../../../types'
import { Clock } from 'lucide-react'

interface TaskDateCellProps {
  task: Task
  formatDate: (dateString: string) => string
}

export function TaskDateCell({ task, formatDate }: TaskDateCellProps) {
  return (
    <div className="flex items-center gap-1">
      <Clock className="h-3 w-3 text-muted-foreground flex-shrink-0" />
      {task.created_at ? (
        <span className="text-[11px]">{formatDate(task.created_at)}</span>
      ) : (
        <span className="text-[11px] text-muted-foreground">-</span>
      )}
    </div>
  )
}

// inertia/pages/tasks/components/task_list/cells/date_cell.svelte
<script lang="ts">
  import { Clock } from 'lucide-svelte'

  import type { Task } from '../../../types.svelte'

  interface Props {
    task: Task
    formatDate: (dateString: string) => string
  }

  const { task, formatDate }: Props = $props()
</script>

<div class="flex items-center gap-1">
  <Clock class="h-3 w-3 text-muted-foreground flex-shrink-0" />
  {#if task.created_at}
    <span class="text-[11px]">{formatDate(task.created_at)}</span>
  {:else}
    <span class="text-[11px] text-muted-foreground">-</span>
  {/if}
</div>
