// inertia/pages/tasks/components/task_list/cells/due_date_cell.svelte
<script lang="ts">
  import type { Task } from '../../../types.svelte'
  import { CalendarIcon } from 'lucide-svelte'

  interface Props {
    task: Task
    formatDate: (dateString: string) => string
  }

  const { task, formatDate }: Props = $props()

  const isOverdue = $derived(task.due_date ? new Date(task.due_date) < new Date() : false)
</script>

<div class="flex items-center gap-1">
  <CalendarIcon class="h-3 w-3 text-muted-foreground shrink-0" />
  {#if task.due_date}
    <span class="text-[11px] font-medium {isOverdue ? 'text-red-600' : 'text-violet-500'}">
      {formatDate(task.due_date)}
    </span>
  {:else}
    <span class="text-[11px] text-slate-500">-</span>
  {/if}
</div>

// inertia/pages/tasks/components/task_list/cells/due_date_cell.tsx

import type { Task } from '../../../types'
import { CalendarIcon } from 'lucide-react'

interface TaskDueDateCellProps {
  task: Task
  formatDate: (dateString: string) => string
}

export function TaskDueDateCell({ task, formatDate }: TaskDueDateCellProps) {
  return (
    <div className="flex items-center gap-1">
      <CalendarIcon className="h-3 w-3 text-muted-foreground flex-shrink-0" />
      {task.due_date ? (
        <span className={`text-[11px] font-medium ${
          // Đơn giản hóa logic màu sắc
          new Date(task.due_date) < new Date() ? 'text-red-600' : // Quá hạn: Đỏ
          'text-violet-500' // Mặc định: Tím
        }`}>{formatDate(task.due_date)}</span>
      ) : (
        <span className="text-[11px] text-slate-500">-</span> // Không có hạn: Xám
      )}
    </div>
  )
}
