// inertia/pages/tasks/components/task_list/cells/label_cell.tsx

import type { Task } from '../../../types'

interface TaskLabelCellProps {
  task: Task
}

export function TaskLabelCell({ task }: TaskLabelCellProps) {
  return (
    <>
      {task.label ? (
        <div className="text-[11px] inline-flex items-center whitespace-nowrap font-medium"
          style={{ color: task.label?.color || 'currentColor' }}>
          <span className="h-1.5 w-1.5 rounded-full mr-1"
            style={{ backgroundColor: task.label?.color || 'currentColor' }}></span>
          {task.label?.name}
        </div>
      ) : (
        <span className="text-[11px] text-muted-foreground">-</span>
      )}
    </>
  )
}

// inertia/pages/tasks/components/task_list/cells/label_cell.svelte
<script lang="ts">
  import type { Task } from '../../../types.svelte'

  interface Props {
    task: Task
  }

  const { task }: Props = $props()
</script>

{#if task.label}
  <div
    class="text-[11px] inline-flex items-center whitespace-nowrap font-medium"
    style:color={task.label?.color || 'currentColor'}
  >
    <span
      class="h-1.5 w-1.5 rounded-full mr-1"
      style:background-color={task.label?.color || 'currentColor'}
    ></span>
    {task.label?.name}
  </div>
{:else}
  <span class="text-[11px] text-muted-foreground">-</span>
{/if}
