// inertia/pages/organizations/components/OrganizationHeader.tsx

import { Button } from '@/components/ui/button'
import { Link } from '@inertiajs/react'
import { Plus } from 'lucide-react'

interface OrganizationHeaderProps {
  title: string
  description: string
  showCreateButton?: boolean
}

export default function OrganizationHeader({
  title,
  description,
  showCreateButton = true,
}: OrganizationHeaderProps) {
  return (
    <div className="flex justify-between items-center mb-6">
      <div>
        <h1 className="text-3xl font-bold tracking-tight">{title}</h1>
        <p className="text-muted-foreground mt-1">
          {description}
        </p>
      </div>
      {showCreateButton && (
        <Button asChild>
          <Link href="/organizations/create">
            <Plus className="mr-2 h-4 w-4" /> Tạo tổ chức mới
          </Link>
        </Button>
      )}
    </div>
  )
}

// inertia/pages/organizations/components/OrganizationHeader.svelte
<script lang="ts">
  import { Link } from '@inertiajs/svelte'
  import { Plus } from 'lucide-svelte'

  import Button from '@/components/ui/button.svelte'

  interface Props {
    title: string
    description: string
    showCreateButton?: boolean
  }

  const {
    title,
    description,
    showCreateButton = true
  }: Props = $props()
</script>

<div class="flex justify-between items-center mb-6">
  <div>
    <h1 class="text-3xl font-bold tracking-tight">{title}</h1>
    <p class="text-muted-foreground mt-1">
      {description}
    </p>
  </div>
  {#if showCreateButton}
    <Button>
      <Link href="/organizations/create">
        <Plus class="mr-2 h-4 w-4" /> Tạo tổ chức mới
      </Link>
    </Button>
  {/if}
</div>
