// inertia/pages/conversations/components/create_conversation_dialog.svelte
<script lang="ts">
  import { router } from '@inertiajs/svelte'
  import Button from '@/components/ui/button.svelte'
  import Dialog from '@/components/ui/dialog.svelte'
  import DialogContent from '@/components/ui/dialog_content.svelte'
  import DialogDescription from '@/components/ui/dialog_description.svelte'
  import DialogFooter from '@/components/ui/dialog_footer.svelte'
  import DialogHeader from '@/components/ui/dialog_header.svelte'
  import DialogTitle from '@/components/ui/dialog_title.svelte'
  import Input from '@/components/ui/input.svelte'
  import Label from '@/components/ui/label.svelte'
  import Avatar from '@/components/ui/avatar.svelte'
  import AvatarFallback from '@/components/ui/avatar_fallback.svelte'
  import { AlertCircle } from 'lucide-svelte'
  import { toast } from 'svelte-sonner'
  import axios from 'axios'

  interface Participant {
    id: string
    username: string
    email: string
  }

  interface Props {
    open: boolean
    children?: any
  }

  let { open = $bindable(false), children }: Props = $props()

  let title = $state('')
  let selectedParticipants = $state<string[]>([])
  let loading = $state(false)
  let users = $state<Participant[]>([])
  let searchTerm = $state('')

  $effect(() => {
    if (open) {
      fetchUsers()
    }
  })

  async function fetchUsers() {
    try {
      const response = await axios.get('/api/users-in-organization')
      if (response.data.success && response.data.users) {
        users = response.data.users
      }
    } catch (error) {
      console.error('Không thể tải danh sách người dùng:', error)
      toast.error('Không thể tải danh sách người dùng')
    }
  }

  function toggleParticipant(userId: string) {
    if (selectedParticipants.includes(userId)) {
      selectedParticipants = selectedParticipants.filter(id => id !== userId)
    } else {
      selectedParticipants = [...selectedParticipants, userId]
    }
  }

  async function handleCreate() {
    if (selectedParticipants.length === 0) {
      toast.error('Vui lòng chọn ít nhất một người tham gia')
      return
    }

    loading = true
    try {
      router.post('/conversations', {
        title: title || undefined,
        participants: selectedParticipants
      }, {
        onSuccess: () => {
          toast.success('Tạo cuộc trò chuyện thành công')
          open = false
          title = ''
          selectedParticipants = []
        },
        onError: () => {
          toast.error('Không thể tạo cuộc trò chuyện')
        }
      })
    } catch (error) {
      console.error('Lỗi khi tạo cuộc trò chuyện:', error)
      toast.error('Đã xảy ra lỗi')
    } finally {
      loading = false
    }
  }

  const filteredUsers = $derived(
    users.filter(user =>
      user.username?.toLowerCase().includes(searchTerm.toLowerCase()) ||
      user.email?.toLowerCase().includes(searchTerm.toLowerCase())
    )
  )
</script>

{#if children}
  {@render children.trigger?.()}
{/if}

<Dialog bind:open>
  <DialogContent class="sm:max-w-[500px]">
    <DialogHeader>
      <DialogTitle>Tạo cuộc trò chuyện mới</DialogTitle>
      <DialogDescription>
        Chọn người tham gia vào cuộc trò chuyện
      </DialogDescription>
    </DialogHeader>

    <div class="space-y-4">
      <div class="space-y-2">
        <Label for="title">Tiêu đề (tùy chọn)</Label>
        <Input
          id="title"
          bind:value={title}
          placeholder="Nhập tiêu đề cuộc trò chuyện..."
        />
      </div>

      <div class="space-y-2">
        <Label>Tìm kiếm người tham gia</Label>
        <Input
          bind:value={searchTerm}
          placeholder="Tìm theo tên hoặc email..."
        />
      </div>

      <div class="space-y-2">
        <Label>Chọn người tham gia ({selectedParticipants.length})</Label>
        <div class="border rounded-md max-h-[300px] overflow-y-auto">
          {#if filteredUsers.length === 0}
            <div class="p-4 text-center text-muted-foreground">
              <AlertCircle class="h-8 w-8 mx-auto mb-2" />
              <p>Không tìm thấy người dùng</p>
            </div>
          {:else}
            {#each filteredUsers as user (user.id)}
              <button
                type="button"
                class="w-full flex items-center gap-3 p-3 hover:bg-muted transition-colors {selectedParticipants.includes(user.id) ? 'bg-muted' : ''}"
                onclick={() => { toggleParticipant(user.id); }}
              >
                <input
                  type="checkbox"
                  checked={selectedParticipants.includes(user.id)}
                  onchange={() => { toggleParticipant(user.id); }}
                  class="h-4 w-4"
                />
                <Avatar class="h-8 w-8">
                  <AvatarFallback>
                    {user.username?.[0]?.toUpperCase() || user.email?.[0]?.toUpperCase()}
                  </AvatarFallback>
                </Avatar>
                <div class="flex-1 text-left">
                  <p class="text-sm font-medium">{user.username || user.email}</p>
                  <p class="text-xs text-muted-foreground">{user.email}</p>
                </div>
              </button>
            {/each}
          {/if}
        </div>
      </div>
    </div>

    <DialogFooter>
      <Button variant="outline" onclick={() => open = false}>
        Hủy
      </Button>
      <Button
        onclick={handleCreate}
        disabled={loading || selectedParticipants.length === 0}
      >
        {loading ? 'Đang tạo...' : 'Tạo cuộc trò chuyện'}
      </Button>
    </DialogFooter>
  </DialogContent>
</Dialog>

// inertia/pages/conversations/components/create_conversation_dialog.tsx
import React, { useState, useEffect } from 'react'
import { router, usePage } from '@inertiajs/react'
import { Button } from '@/components/ui/button'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '@/components/ui/dialog'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar'
import { AlertCircle } from 'lucide-react'
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert'
import useTranslation from '@/hooks/use_translation'
import axios from 'axios'

interface Participant {
  id: string
  full_name: string
  avatar?: string
  email: string
}

interface CreateConversationDialogProps {
  trigger?: React.ReactNode
}

export function CreateConversationDialog({ trigger }: CreateConversationDialogProps) {
  const [open, setOpen] = useState(false)
  const [title, setTitle] = useState('')
  const [selectedParticipants, setSelectedParticipants] = useState<string[]>([])
  const [loading, setLoading] = useState(false)
  const [errors, setErrors] = useState<Record<string, string> | null>(null)
  const [users, setUsers] = useState<Participant[]>([])
  const { t } = useTranslation()
  const page = usePage<{ auth?: { user?: any } }>()

  // Tải danh sách người dùng trong tổ chức khi mở dialog
  useEffect(() => {
    if (open) {
      // Debug thông tin người dùng và tổ chức hiện tại
      console.log('Auth user debug:', {
        user_id: page.props.auth?.user?.id,
        current_organization_id: page.props.auth?.user?.current_organization_id,
      })
      
      fetchOrganizationUsers()
    }
  }, [open])

  const fetchOrganizationUsers = async () => {
    try {
      console.log('Đang tải danh sách người dùng trong tổ chức...')
      
      // Sử dụng API endpoint mới đơn giản hơn
      const response = await axios.get('/api/users-in-organization')
      
      if (response.data.success && response.data.users && Array.isArray(response.data.users)) {
        setUsers(response.data.users)
        console.log('Đã tải', response.data.users.length, 'người dùng trong tổ chức')
      } else {
        console.warn('Định dạng dữ liệu không đúng hoặc không có người dùng:', response.data)
        setUsers([])
      }
    } catch (error) {
      console.error('Không thể tải danh sách người dùng trong tổ chức:', error)
      
      // Hiển thị lỗi trong component thay vì dùng dữ liệu mẫu
      setUsers([])
      setErrors({
        api_error: `Lỗi khi lấy danh sách người dùng: ${error.message || 'Lỗi không xác định'}`
      })
      
      // Nếu là lỗi phản hồi từ API, hiển thị thông tin chi tiết hơn
      if (error.response && error.response.data) {
        console.error('Chi tiết lỗi từ API:', error.response.data)
        if (error.response.data.message) {
          setErrors({
            api_error: error.response.data.message
          })
        }
      }
    }
  }

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()
    setLoading(true)
    setErrors(null)

    router.post('/conversations', {
      title,
      participants: selectedParticipants,
      initial_message: ' ' // Gửi khoảng trắng để tránh lỗi validation nếu cần
    }, {
      onSuccess: () => {
        setOpen(false)
        setTitle('')
        setSelectedParticipants([])
        setLoading(false)
      },
      onError: (errors) => {
        setErrors(errors)
        setLoading(false)
      }
    })
  }

  const toggleParticipant = (id: string) => {
    if (selectedParticipants.includes(id)) {
      setSelectedParticipants(selectedParticipants.filter(pid => pid !== id))
    } else {
      setSelectedParticipants([...selectedParticipants, id])
    }
  }

  const getAvatarInitials = (name: string) => {
    return name
      .split(' ')
      .map(part => part[0])
      .join('')
      .toUpperCase()
      .substring(0, 2)
  }

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>
        {trigger || (
          <Button variant="default">
            {t('conversation.create_new', {}, 'Tạo cuộc trò chuyện mới')}
          </Button>
        )}
      </DialogTrigger>
      <DialogContent className="sm:max-w-[500px]">
        <DialogHeader>
          <DialogTitle>{t('conversation.new_conversation', {}, 'Tạo cuộc trò chuyện mới')}</DialogTitle>
          <DialogDescription>
            {t('conversation.create_description', {}, 'Tạo một cuộc trò chuyện mới và mời những người bạn muốn nói chuyện.')}
          </DialogDescription>
        </DialogHeader>

        {errors && Object.keys(errors).length > 0 && (
          <Alert variant="destructive">
            <AlertCircle className="h-4 w-4" />
            <AlertTitle>{t('common.error', {}, 'Lỗi')}</AlertTitle>
            <AlertDescription>
              {Object.values(errors).map((error, index) => (
                <div key={index}>{error}</div>
              ))}
            </AlertDescription>
          </Alert>
        )}

        <form onSubmit={handleSubmit} className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="title">{t('conversation.title_optional', {}, 'Tiêu đề cuộc trò chuyện (không bắt buộc)')}</Label>
            <Input
              id="title"
              placeholder={t('conversation.title_placeholder', {}, 'Nhập tiêu đề cuộc trò chuyện')}
              value={title}
              onChange={(e) => setTitle(e.target.value)}
            />
            <p className="text-sm text-muted-foreground">
              {t('conversation.title_help', {}, 'Nếu không nhập tiêu đề, tên cuộc trò chuyện sẽ là tên của những người tham gia.')}
            </p>
          </div>

          <div className="space-y-2">
            <Label>{t('conversation.participants', {}, 'Người tham gia')}</Label>
            <div className="border rounded-md p-2 max-h-48 overflow-y-auto">
              {users && users.length > 0 ? (
                <div className="space-y-1">
                  {users.map((user) => (
                    <div 
                      key={user.id} 
                      className={`flex items-center space-x-2 p-2 rounded cursor-pointer ${
                        selectedParticipants.includes(user.id) ? 'bg-accent' : 'hover:bg-accent/50'
                      }`}
                      onClick={() => toggleParticipant(user.id)}
                    >
                      <div className="flex items-center gap-2 flex-1">
                        <Avatar className="h-8 w-8">
                          <AvatarImage src={user.avatar || ''} alt={user.full_name} />
                          <AvatarFallback>{getAvatarInitials(user.full_name)}</AvatarFallback>
                        </Avatar>
                        <div className="flex-1">
                          <div>{user.full_name}</div>
                          <div className="text-sm text-muted-foreground">{user.email}</div>
                        </div>
                        {selectedParticipants.includes(user.id) && (
                          <div className="flex-shrink-0 ml-auto">
                            <div className="h-2 w-2 rounded-full bg-primary"></div>
                          </div>
                        )}
                      </div>
                    </div>
                  ))}
                </div>
              ) : (
                <p className="text-center text-muted-foreground py-2">
                  {t('conversation.no_users', {}, 'Không tìm thấy người dùng nào để thêm vào cuộc trò chuyện.')}
                </p>
              )}
            </div>
            {errors?.participants && (
              <p className="text-sm text-destructive">{errors.participants}</p>
            )}
            
            {selectedParticipants.length > 0 && (
              <div className="flex flex-wrap gap-1 mt-2">
                {selectedParticipants.map(id => {
                  const user = users.find(u => u.id === id)
                  return user ? (
                    <div key={id} className="bg-accent text-accent-foreground px-2 py-1 rounded-full text-xs flex items-center">
                      {user.full_name}
                      <button 
                        type="button" 
                        className="ml-1 text-muted-foreground hover:text-foreground"
                        onClick={(e) => {
                          e.stopPropagation()
                          toggleParticipant(id)
                        }}
                      >
                        ✕
                      </button>
                    </div>
                  ) : null
                })}
              </div>
            )}
          </div>

          <DialogFooter>
            <Button variant="outline" type="button" onClick={() => setOpen(false)}>
              {t('common.cancel', {}, 'Hủy')}
            </Button>
            <Button type="submit" disabled={selectedParticipants.length === 0 || loading}>
              {loading ? t('common.creating', {}, 'Đang tạo...') : t('conversation.create_button', {}, 'Tạo cuộc trò chuyện')}
            </Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  )
}

export default CreateConversationDialog
