// inertia/pages/settings/index.tsx
import React from 'react'
import { Head, useForm, usePage } from '@inertiajs/react'
import { Link } from '@inertiajs/react'
import AppLayout from '@/layouts/app_layout'
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Textarea } from '@/components/ui/textarea'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'

// Import icons
import { User, CreditCard, Bell, Eye, Palette } from 'lucide-react'

// Define sidebar item type
interface SidebarItem {
  title: string
  href: string
  icon: React.ElementType
}

// Define các type dữ liệu từ backend
interface UserData {
  id: string
  username: string
  email: string
  user_profile?: {
    bio?: string
  }
  user_urls?: Array<{
    id: number
    url: string
  }>
}

interface PageProps {
  auth?: {
    user?: UserData
  }
  [key: string]: any
}

export default function Settings() {
  // Lấy dữ liệu người dùng từ props với kiểm tra null
  const page = usePage<PageProps>()
  const auth = page.props.auth
  const user = auth?.user || {
    id: '',
    username: '',
    email: '',
    user_profile: { bio: '' },
    user_urls: []
  }

  // Khởi tạo form với dữ liệu thực
  const form = useForm({
    bio: user.user_profile?.bio || '',
    urls: user.user_urls?.map(item => item.url) || []
  })

  // Define sidebar items
  const sidebarItems: SidebarItem[] = [
    { title: 'Hồ sơ', href: '/settings/profile', icon: User },
    { title: 'Tài khoản', href: '/settings/account', icon: CreditCard },
    { title: 'Giao diện', href: '/settings/appearance', icon: Palette },
    { title: 'Thông báo', href: '/settings/notifications', icon: Bell },
    { title: 'Hiển thị', href: '/settings/display', icon: Eye }
  ]

  // Detect current active item
  const currentPath = window.location.pathname
  
  // Handle form submission
  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()
    form.post('/settings/profile', {
      onSuccess: () => {
        // Hiển thị thông báo thành công
      }
    })
  }

  // Add URL field
  const addUrl = () => {
    form.setData('urls', [...form.data.urls, ''])
  }

  // Remove URL field
  const removeUrl = (index: number) => {
    form.setData('urls', form.data.urls.filter((_, i) => i !== index))
  }

  // Update URL value
  const updateUrl = (index: number, value: string) => {
    const updatedUrls = [...form.data.urls]
    updatedUrls[index] = value
    form.setData('urls', updatedUrls)
  }

  return (
    <>
      <Head title="Cài đặt" />
      <div className="container py-8">
        <div className="grid grid-cols-12 gap-6">
          {/* Sidebar */}
          <div className="col-span-3">
            <nav className="flex flex-col space-y-1">
              {sidebarItems.map((item) => (
                <Link
                  key={item.href}
                  href={item.href}
                  className={`flex items-center rounded-md px-3 py-2 hover:bg-muted ${
                    currentPath === item.href || (currentPath === '/settings' && item.href === '/settings/profile')
                      ? 'bg-muted font-medium text-foreground'
                      : 'text-muted-foreground'
                  }`}
                >
                  <item.icon className="mr-2 h-4 w-4" />
                  {item.title}
                </Link>
              ))}
            </nav>
          </div>

          {/* Content */}
          <div className="col-span-9">
            <Card>
              <CardHeader>
                <CardTitle>Thông tin cá nhân</CardTitle>
                <CardDescription>
                  Đây là cách người khác sẽ nhìn thấy bạn trên trang web.
                </CardDescription>
              </CardHeader>
              <CardContent>
                <form onSubmit={handleSubmit} className="space-y-6">
                  {/* Thông tin hiển thị public */}
                  <div className="space-y-2">
                    <p>
                      Đây là tên hiển thị công khai của bạn. Nó có thể là tên thật của bạn hoặc một bút danh. Bạn chỉ có thể thay đổi nội dung này 30 ngày một lần.
                    </p>
                  </div>

                  {/* Chọn email để hiển thị */}
                  <div className="space-y-2">
                    <Label>Email</Label>
                    <Select defaultValue="verified">
                      <SelectTrigger>
                        <SelectValue placeholder="Chọn email đã xác minh để hiển thị" />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="verified">
                          {user.email}
                        </SelectItem>
                      </SelectContent>
                    </Select>
                    <p className="text-sm text-muted-foreground">
                      Bạn có thể quản lý địa chỉ email đã xác minh trong phần cài đặt email.
                    </p>
                  </div>
                
                  {/* Bio section */}
                  <div className="space-y-2">
                    <Label htmlFor="bio">Giới thiệu</Label>
                    <Textarea
                      id="bio"
                      value={form.data.bio}
                      onChange={(e) => form.setData('bio', e.target.value)}
                      rows={3}
                      placeholder="Viết một vài câu về bản thân"
                    />
                  </div>

                  {/* URLs section */}
                  <div className="space-y-2">
                    <Label>Đường dẫn</Label>
                    <p className="text-sm text-muted-foreground">
                      Thêm liên kết đến website, blog, hoặc mạng xã hội của bạn.
                    </p>
                    
                    <div className="space-y-2">
                      {form.data.urls.map((url, index) => (
                        <div key={index} className="flex gap-2">
                          <Input
                            value={url}
                            onChange={(e) => updateUrl(index, e.target.value)}
                            placeholder="https://example.com"
                            className="flex-1"
                          />
                          <Button
                            type="button"
                            variant="outline"
                            size="sm"
                            onClick={() => removeUrl(index)}
                          >
                            Xóa
                          </Button>
                        </div>
                      ))}
                      <Button
                        type="button"
                        variant="outline"
                        size="sm"
                        onClick={addUrl}
                      >
                        Thêm URL
                      </Button>
                    </div>
                  </div>

                  {/* Mention options */}
                  <div className="space-y-2">
                    <p className="text-sm">
                      Bạn có thể <span className="text-primary">@mention</span> người dùng và tổ chức khác để liên kết đến họ.
                    </p>
                  </div>

                  {/* Submit button */}
                  <div>
                    <Button type="submit" className="mt-4">
                      Cập nhật hồ sơ
                    </Button>
                  </div>
                </form>
              </CardContent>
            </Card>
          </div>
        </div>
      </div>
    </>
  )
}

Settings.layout = (page: React.ReactNode) => <AppLayout title="Cài đặt">{page}</AppLayout>

// inertia/pages/org/settings/index.svelte
<script lang="ts">
  import { router } from '@inertiajs/svelte'
  import { Settings, Save } from 'lucide-svelte'

  import Button from '@/components/ui/button.svelte'
  import Card from '@/components/ui/card.svelte'
  import CardContent from '@/components/ui/card_content.svelte'
  import CardDescription from '@/components/ui/card_description.svelte'
  import CardHeader from '@/components/ui/card_header.svelte'
  import CardTitle from '@/components/ui/card_title.svelte'
  import Input from '@/components/ui/input.svelte'
  import Label from '@/components/ui/label.svelte'
  import Textarea from '@/components/ui/textarea.svelte'
  import OrganizationLayout from '@/layouts/organization_layout.svelte'


  interface Props {
    organization: {
      id: string
      name: string
      description: string | null
      website: string | null
      email: string | null
    }
  }

  const { organization }: Props = $props()

  let formData = $state({
    name: '',
    description: '',
    website: '',
    email: '',
  })
  let errors = $state<Record<string, string>>({})
  let processing = $state(false)

  $effect(() => {
    formData = {
      name: organization.name,
      description: organization.description ?? '',
      website: organization.website ?? '',
      email: organization.email ?? '',
    }
  })

  function handleSubmit(event: SubmitEvent) {
    event.preventDefault()
    processing = true
    errors = {}

    router.put(`/org/settings`, formData, {
      preserveState: true,
      preserveScroll: true,
      onSuccess: () => {
        processing = false
      },
      onError: (errorBag) => {
        processing = false
        errors = Object.fromEntries(
          Object.entries(errorBag).map(([key, value]) => [
            key,
            typeof value === 'string' ? value : 'Giá trị không hợp lệ',
          ])
        )
      },
    })
  }
</script>

<OrganizationLayout>
  <div class="space-y-6 max-w-3xl">
    <div>
      <p class="font-medium uppercase tracking-wider text-xs text-muted-foreground">Organization / Settings</p>
      <h1 class="text-4xl font-bold tracking-tight">Thông tin tổ chức</h1>
      <p class="mt-2 text-sm text-muted-foreground">Quản lý nhận diện và thông tin liên hệ nội bộ của tổ chức hiện tại.</p>
    </div>

    <form onsubmit={handleSubmit}>
      <Card class="border border-border rounded-lg bg-white shadow-xs">
        <CardHeader>
          <div class="flex items-center gap-2">
            <Settings class="h-5 w-5" />
            <CardTitle>Thông tin cơ bản</CardTitle>
          </div>
          <CardDescription>
            Màn này chỉ quản lý thông tin tổ chức. Subscription sản phẩm hiện là của tài khoản người dùng, không phải package public của organization.
          </CardDescription>
        </CardHeader>
        <CardContent class="space-y-4">
          <div class="space-y-2">
            <Label for="name">Tên tổ chức</Label>
            <Input
              id="name"
              type="text"
              bind:value={formData.name}
              required
            />
            {#if errors.name}
              <p class="text-sm text-destructive">{errors.name}</p>
            {/if}
          </div>

          <div class="space-y-2">
            <Label for="description">Mô tả</Label>
            <Textarea
              id="description"
              bind:value={formData.description}
              rows={4}
              placeholder="Mô tả ngắn về lĩnh vực, cách làm việc hoặc mục tiêu của tổ chức..."
            />
            {#if errors.description}
              <p class="text-sm text-destructive">{errors.description}</p>
            {/if}
          </div>

          <div class="grid grid-cols-2 gap-4">
            <div class="space-y-2">
              <Label for="website">Website</Label>
              <Input
                id="website"
                type="url"
                bind:value={formData.website}
                placeholder="https://example.com"
              />
              {#if errors.website}
                <p class="text-sm text-destructive">{errors.website}</p>
              {/if}
            </div>

            <div class="space-y-2">
              <Label for="email">Email liên hệ</Label>
              <Input
                id="email"
                type="email"
                bind:value={formData.email}
                placeholder="contact@example.com"
              />
              {#if errors.email}
                <p class="text-sm text-destructive">{errors.email}</p>
              {/if}
            </div>
          </div>

          <div class="flex justify-end gap-2 pt-4">
            <Button type="button" variant="outline" onclick={() => { window.history.back(); }}>
              Quay lại
            </Button>
            <Button type="submit" disabled={processing}>
              <Save class="mr-2 h-4 w-4" />
              {processing ? 'Đang lưu...' : 'Lưu thay đổi'}
            </Button>
          </div>
        </CardContent>
      </Card>
    </form>
  </div>
</OrganizationLayout>
