// inertia/components/ui/checkbox.tsx
import * as React from 'react'
import * as CheckboxPrimitive from '@radix-ui/react-checkbox'
import { Check } from 'lucide-react'
import { cn } from '@/lib/utils'

const Checkbox = React.forwardRef<
  React.ElementRef<typeof CheckboxPrimitive.Root>,
  React.ComponentPropsWithoutRef<typeof CheckboxPrimitive.Root>
>(({ className, ...props }, ref) => (
  <CheckboxPrimitive.Root
    ref={ref}
    className={cn(
      'peer h-4 w-4 shrink-0 rounded-sm border border-primary ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50 data-[state=checked]:bg-primary data-[state=checked]:text-primary-foreground',
      className
    )}
    {...props}
  >
    <CheckboxPrimitive.Indicator
      className={cn('flex items-center justify-center text-current')}
    >
      <Check className='h-4 w-4' />
    </CheckboxPrimitive.Indicator>
  </CheckboxPrimitive.Root>
))
Checkbox.displayName = CheckboxPrimitive.Root.displayName

export { Checkbox }

// inertia/components/ui/checkbox.svelte
<!--
  Checkbox Component - Svelte 5

  Port từ shadcn/ui React checkbox.
  Uses Bits UI Checkbox primitive.
-->

<script lang="ts">
  import { cn } from '$lib/utils-svelte'
  import { Checkbox as CheckboxPrimitive } from 'bits-ui'
  import Check from 'lucide-svelte/icons/check'

  type Props = {
    class?: string
    checked?: boolean | 'indeterminate'
    disabled?: boolean
    required?: boolean
    name?: string
    value?: string
    id?: string
    onCheckedChange?: (checked: boolean | 'indeterminate') => void
  }

  const {
    class: className,
    checked,
    onCheckedChange,
    ...restProps
  }: Props = $props()
</script>

<CheckboxPrimitive.Root
  {checked}
  {onCheckedChange}
  class={cn(
    'peer h-4 w-4 shrink-0 rounded-sm border-2 border-border ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50 data-[state=checked]:bg-primary data-[state=checked]:text-primary-foreground',
    className
  )}
  {...restProps}
>
  {#snippet children({ checked })}
    <div class="flex items-center justify-center text-current">
      {#if checked === true}
        <Check class="h-4 w-4" />
      {/if}
    </div>
  {/snippet}
</CheckboxPrimitive.Root>
