// inertia/components/ui/collapsible.svelte
<script lang="ts" module>
  export { default as Collapsible, default as Root } from './collapsible.svelte'
  export { default as CollapsibleTrigger, default as Trigger } from './collapsible_trigger.svelte'
  export { default as CollapsibleContent, default as Content } from './collapsible_content.svelte'
</script>

<script lang="ts">
  import { Collapsible as CollapsiblePrimitive } from 'bits-ui'
  import type { Snippet } from 'svelte'
  import type { ComponentProps } from 'bits-ui'

  type Props = ComponentProps<typeof CollapsiblePrimitive.Root> & {
    children?: Snippet
  }

  const { children, ...restProps }: Props = $props()
</script>

<CollapsiblePrimitive.Root data-slot="collapsible" {...restProps}>
  {@render children?.()}
</CollapsiblePrimitive.Root>

// inertia/components/ui/collapsible.tsx
import React from 'react'
import * as CollapsiblePrimitive from '@radix-ui/react-collapsible'

function Collapsible({
  ...props
}: React.ComponentProps<typeof CollapsiblePrimitive.Root>) {
  return <CollapsiblePrimitive.Root data-slot='collapsible' {...props} />
}

function CollapsibleTrigger({
  ...props
}: React.ComponentProps<typeof CollapsiblePrimitive.CollapsibleTrigger>) {
  return (
    <CollapsiblePrimitive.CollapsibleTrigger
      data-slot='collapsible-trigger'
      {...props}
    />
  )
}

function CollapsibleContent({
  ...props
}: React.ComponentProps<typeof CollapsiblePrimitive.CollapsibleContent>) {
  return (
    <CollapsiblePrimitive.CollapsibleContent
      data-slot='collapsible-content'
      {...props}
    />
  )
}

export { Collapsible, CollapsibleTrigger, CollapsibleContent }
