// inertia/components/ui/input.svelte
<!--
  Input Component - Svelte 5

  Port từ shadcn/ui React input.
-->

<script lang="ts">
  import { cn } from '$lib/utils-svelte'
  import type { HTMLInputAttributes } from 'svelte/elements'

  type Props = HTMLInputAttributes & {
    class?: string
    value?: string
  }

  let {
    class: className,
    type = 'text',
    value = $bindable(''),
    ...restProps
  }: Props = $props()

  // Nếu type là search, chuyển thành text để tránh hiển thị code
  const inputType = $derived(type === 'search' ? 'text' : type)
</script>

<input
  type={inputType}
  class={cn(
    'flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50',
    className
  )}
  bind:value
  {...restProps}
/>

// inertia/components/ui/input.tsx
import * as React from 'react'
import { cn } from '@/lib/utils'

export interface InputProps
  extends React.InputHTMLAttributes<HTMLInputElement> {}

const Input = React.forwardRef<HTMLInputElement, InputProps>(
  ({ className, type, ...props }, ref) => {
    // Nếu type là search, chuyển thành text để tránh hiển thị code
    const inputType = type === 'search' ? 'text' : type
    return (
      <input
        type={inputType}
        className={cn(
          'flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50',
          className
        )}
        ref={ref}
        {...props}
      />
    )
  }
)
Input.displayName = 'Input'

export { Input }
