// inertia/components/ui/language-switcher.tsx
import React from 'react'
import { usePage, router } from '@inertiajs/react'
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuGroup,
  DropdownMenuItem,
  DropdownMenuTrigger
} from './dropdown-menu'
import { Button } from './button'
import { GlobeIcon } from 'lucide-react'
import useTranslation from '@/hooks/use_translation'

interface PageProps {
  locale: string
  supportedLocales: string[]
  translations?: any
  [key: string]: any
}

export function LanguageSwitcher() {
  const props = usePage().props as unknown as PageProps
  const { locale, supportedLocales, translations } = props
  const { t } = useTranslation()

  // Debug log chi tiết

  // Kiểm tra translations có đầy đủ không
  if (translations) {

    // Kiểm tra namespace messages
    if (translations.messages) {
      // Kiểm tra các namespace con trong messages

      // Kiểm tra các key trong user namespace
      if (translations.messages.user) {

      } else {
        // Only log in development
        if (process.env.NODE_ENV === 'development') {
          console.warn('[LanguageSwitcher] Missing user namespace in messages')
        }
      }

      // Kiểm tra các key trong common namespace
      if (translations.messages.common) {

      } else {
        // Only log in development
        if (process.env.NODE_ENV === 'development') {
          console.warn('[LanguageSwitcher] Missing common namespace in messages')
        }
      }
    } else {
      // Only log in development
      if (process.env.NODE_ENV === 'development') {
        console.warn('[LanguageSwitcher] Missing messages namespace in translations')
      }
    }
  }

  const getLanguageName = (code: string) => {
    const languages: Record<string, string> = {
      en: 'English',
      vi: 'Tiếng Việt'
    }
    return languages[code] || code
  }

  const switchLanguage = (newLocale: string) => {

    // Chuyển đổi ngôn ngữ bằng cách tải lại trang với tham số locale mới
    const url = new URL(window.location.href)

    // Xóa tham số locale cũ trước khi thêm tham số mới
    url.searchParams.delete('locale')

    // Thêm tham số locale mới
    url.searchParams.set('locale', newLocale)

    const newUrl = url.toString()

    // Sử dụng window.location.href để tải lại trang hoàn toàn thay vì router.visit
    // Điều này đảm bảo middleware phát hiện ngôn ngữ sẽ được kích hoạt đầy đủ
    window.location.href = newUrl

    // Không sử dụng router.visit vì có thể không tải lại đầy đủ dữ liệu dịch
    // router.visit(newUrl, {
    //   preserveScroll: true,
    //   preserveState: false,
    //   replace: true,
    // })
  }

  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button variant="ghost" size="icon" className="relative">
          <GlobeIcon className="h-4 w-4" />
          <span className="sr-only">{t('settings.language_switcher', {}, 'Chuyển đổi ngôn ngữ')}</span>
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end">
        <DropdownMenuGroup>
          {supportedLocales?.map((code) => (
            <DropdownMenuItem
              key={code}
              onClick={() => switchLanguage(code)}
              className={locale === code ? 'bg-accent' : ''}
            >
              {getLanguageName(code)}
              {locale === code && <span className="ml-2 text-xs">✓</span>}
            </DropdownMenuItem>
          ))}
        </DropdownMenuGroup>
      </DropdownMenuContent>
    </DropdownMenu>
  )
}

// inertia/components/ui/language_switcher.svelte
<script lang="ts">
  import { page } from '@inertiajs/svelte'
  import DropdownMenu from './dropdown_menu.svelte'
  import DropdownMenuTrigger from './dropdown_menu_trigger.svelte'
  import DropdownMenuContent from './dropdown_menu_content.svelte'
  import DropdownMenuGroup from './dropdown_menu_group.svelte'
  import DropdownMenuItem from './dropdown_menu_item.svelte'
  import Button from './button.svelte'
  import { Globe } from 'lucide-svelte'
  import { useTranslation } from '@/stores/translation.svelte'

  interface PageProps {
    locale: string
    supportedLocales: string[]
    translations?: any
    [key: string]: unknown
  }

  const { t } = useTranslation()

  const props = $derived($page.props as unknown as PageProps)
  const locale = $derived(props.locale)
  const supportedLocales = $derived(props.supportedLocales || [])
  const translations = $derived(props.translations)

  // Debug log chi tiết
  $effect(() => {
    if (translations) {
      const hasUser = Boolean(
        (translations.messages && translations.messages.user) ||
          translations.user
      )

      const hasCommon = Boolean(
        (translations.messages && translations.messages.common) || translations.common
      )

      if (!hasUser && import.meta.env.DEV) {
        console.warn('[LanguageSwitcher] Missing user namespace in translations')
      }

      if (!hasCommon && import.meta.env.DEV) {
        console.warn('[LanguageSwitcher] Missing common namespace in translations')
      }
    }
  })

  function getLanguageName(code: string): string {
    const languages: Record<string, string> = {
      en: 'English',
      vi: 'Tiếng Việt'
    }
    return languages[code] || code
  }

  function switchLanguage(newLocale: string) {
    const url = new URL(window.location.href)
    url.searchParams.delete('locale')
    url.searchParams.set('locale', newLocale)
    const newUrl = url.toString()
    window.location.href = newUrl
  }
</script>

<DropdownMenu>
  <DropdownMenuTrigger>
    <Button variant="ghost" size="icon" class="relative">
      <Globe class="h-4 w-4" />
      <span class="sr-only">{t('settings.language_switcher', {}, 'Chuyển đổi ngôn ngữ')}</span>
    </Button>
  </DropdownMenuTrigger>
  <DropdownMenuContent align="end">
    <DropdownMenuGroup>
      {#each supportedLocales as code}
        <DropdownMenuItem
          onclick={() => { switchLanguage(code); }}
          class={locale === code ? 'bg-accent' : ''}
        >
          {getLanguageName(code)}
          {#if locale === code}
            <span class="ml-2 text-xs">✓</span>
          {/if}
        </DropdownMenuItem>
      {/each}
    </DropdownMenuGroup>
  </DropdownMenuContent>
</DropdownMenu>
