// inertia/components/ui/mode_toggle.tsx
import { useEffect } from 'react'
import { Check, Moon, Sun } from 'lucide-react'
import { cn } from '@/lib/utils'
import useTheme from '@/hooks/theme'
import { Button } from '@/components/ui/button'
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown_menu'

export function ModeToggle() {
  const { theme, setTheme } = useTheme()

  /* Update theme-color meta tag
   * when theme is updated */
  useEffect(() => {
    const themeColor = theme === 'dark' ? '#020817' : '#fff'
    const metaThemeColor = document.querySelector("meta[name='theme-color']")
    if (metaThemeColor) metaThemeColor.setAttribute('content', themeColor)
  }, [theme])

  return (
    <DropdownMenu modal={false}>
      <DropdownMenuTrigger asChild>
        <Button variant='ghost' size='icon' className='scale-95 rounded-full'>
          <Sun className='size-[1.2rem] scale-100 rotate-0 transition-all dark:scale-0 dark:-rotate-90' />
          <Moon className='absolute size-[1.2rem] scale-0 rotate-90 transition-all dark:scale-100 dark:rotate-0' />
          <span className='sr-only'>Chuyển đổi giao diện</span>
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent align='end'>
        <DropdownMenuItem onClick={() => { setTheme('light'); }}>
          Sáng{' '}
          <Check
            size={14}
            className={cn('ml-auto', theme !== 'light' && 'hidden')}
          />
        </DropdownMenuItem>
        <DropdownMenuItem onClick={() => { setTheme('dark'); }}>
          Tối
          <Check
            size={14}
            className={cn('ml-auto', theme !== 'dark' && 'hidden')}
          />
        </DropdownMenuItem>
        <DropdownMenuItem onClick={() => { setTheme('system'); }}>
          Hệ thống
          <Check
            size={14}
            className={cn('ml-auto', theme !== 'system' && 'hidden')}
          />
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  )
}

// inertia/components/ui/mode_toggle.svelte
<script lang="ts">
  import { cn } from '@/lib/utils'
  import { theme, type Theme } from '@/stores/theme.svelte'
  import Button from '@/components/ui/button.svelte'
  import DropdownMenu from '@/components/ui/dropdown_menu.svelte'
  import DropdownMenuContent from '@/components/ui/dropdown_menu_content.svelte'
  import DropdownMenuItem from '@/components/ui/dropdown_menu_item.svelte'
  import DropdownMenuTrigger from '@/components/ui/dropdown_menu_trigger.svelte'
  import { Sun, Moon, Check } from 'lucide-svelte'

  let currentTheme = $state<Theme>('light')

  // Subscribe to theme store
  const unsubscribe = theme.subscribe((value) => {
    currentTheme = value
  })

  // Update meta theme-color when theme changes
  $effect(() => {
    const themeColor = currentTheme === 'dark' ? '#020817' : '#fff'
    const metaThemeColor = document.querySelector("meta[name='theme-color']")
    if (metaThemeColor) metaThemeColor.setAttribute('content', themeColor)

    return () => {
      unsubscribe()
    }
  })

  function setTheme(newTheme: Theme) {
    theme.set(newTheme)
  }
</script>

<DropdownMenu>
  <DropdownMenuTrigger>
    {#snippet child({ props })}
      <Button variant="ghost" size="icon" class="scale-95 rounded-full" {...props}>
        <Sun
          class="size-[1.2rem] scale-100 rotate-0 transition-all dark:scale-0 dark:-rotate-90"
        />
        <Moon
          class="absolute size-[1.2rem] scale-0 rotate-90 transition-all dark:scale-100 dark:rotate-0"
        />
        <span class="sr-only">Chuyển đổi giao diện</span>
      </Button>
    {/snippet}
  </DropdownMenuTrigger>
  <DropdownMenuContent align="end">
    <DropdownMenuItem onclick={() => { setTheme('light'); }}>
      Sáng
      <Check size={14} class={cn('ml-auto', currentTheme !== 'light' && 'hidden')} />
    </DropdownMenuItem>
    <DropdownMenuItem onclick={() => { setTheme('dark'); }}>
      Tối
      <Check size={14} class={cn('ml-auto', currentTheme !== 'dark' && 'hidden')} />
    </DropdownMenuItem>
    <DropdownMenuItem onclick={() => { setTheme('system'); }}>
      Hệ thống
      <Check size={14} class={cn('ml-auto', currentTheme !== 'system' && 'hidden')} />
    </DropdownMenuItem>
  </DropdownMenuContent>
</DropdownMenu>
