// inertia/pages/tasks/components/modals/task_detail_info/task_detail_fields.svelte
<script lang="ts">
  import Input from '@/components/ui/input.svelte'
  import Textarea from '@/components/ui/textarea.svelte'
  import Label from '@/components/ui/label.svelte'
  import Select from '@/components/ui/select.svelte'
  import SelectContent from '@/components/ui/select_content.svelte'
  import SelectItem from '@/components/ui/select_item.svelte'
  import SelectTrigger from '@/components/ui/select_trigger.svelte'
  import Button from '@/components/ui/button.svelte'
  import * as Popover from '@/components/ui/popover'
  import Calendar from '@/components/ui/calendar.svelte'
  import { CalendarIcon } from 'lucide-svelte'
  import { cn } from '@/lib/utils'
  import { useTranslation } from '@/stores/translation.svelte'
  import type { Task } from '../../../types.svelte'

  interface Props {
    task: Task
    formData: Partial<Task>
    isEditing: boolean
    errors: Record<string, string>
    statuses: Array<{ id: number; name: string; color: string }>
    priorities: Array<{ id: number; name: string; color: string; value: number }>
    labels: Array<{ id: number; name: string; color: string }>
    users: Array<{ id: number; username: string; email: string }>
    handleChange: (e: Event) => void
    handleSelectChange: (name: string, value: string) => void
    handleDateChange: (date: Date | undefined) => void
  }

  const {
    task,
    formData,
    isEditing,
    errors,
    statuses,
    priorities,
    labels,
    users,
    handleChange,
    handleSelectChange,
    handleDateChange
  }: Props = $props()

  const { t } = useTranslation()

  // Format lại ngày hạn để hiển thị trong DatePicker
  const dueDate = $derived(formData.due_date ? new Date(formData.due_date) : undefined)

  // Lấy ID từ các trường khác nhau (hỗ trợ nhiều định dạng backend)
  const statusId = $derived(formData.status_id || task.status?.id)
  const priorityId = $derived(formData.priority_id || task.priority?.id)
  const labelId = $derived(formData.label_id || task.label?.id)
  const assignedToId = $derived(formData.assigned_to)

  // Tìm các đối tượng hiện tại để hiển thị
  const currentStatus = $derived(statuses.find(s => s.id === statusId) || task.status)
  const currentPriority = $derived(priorities.find(p => p.id === priorityId) || task.priority)
  const currentLabel = $derived(labels.find(l => l.id === labelId) || task.label)
  const currentAssignee = $derived(users.find(u => u.id === assignedToId) || task.assignee)

  // Format ngày hạn để hiển thị khi không ở chế độ chỉnh sửa
  function formatDate(dateString?: string) {
    if (!dateString) return t('task.due_date_not_set', {}, 'Chưa thiết lập')
    try {
      const date = new Date(dateString)
      return date.toLocaleDateString('vi-VN')
    } catch (error) {
      return t('task.due_date_unknown', {}, 'Không xác định')
    }
  }

  // Xử lý giá trị mặc định cho các trường Select
  const statusIdValue = $derived((formData.status_id || task.status?.id || '').toString())
  const priorityIdValue = $derived((formData.priority_id || task.priority?.id || '').toString())
  const labelIdValue = $derived(String(formData.label_id || (task.label ? task.label.id : '')))
  const assignedToValue = $derived(String(formData.assigned_to || ''))

  let datePickerOpen = $state(false)
</script>

<div class="space-y-6">
  <!-- Tiêu đề và mô tả -->
  <section>
    <div class="space-y-2">
      <Label for="title">{t('task.title', {}, 'Tiêu đề')}</Label>
      {#if isEditing}
        <Input
          id="title"
          name="title"
          value={formData.title || ''}
          oninput={handleChange}
          placeholder={t('task.enter_title', {}, 'Nhập tiêu đề nhiệm vụ')}
          class={errors.title ? 'border-red-500' : ''}
        />
        {#if errors.title}
          <p class="text-xs text-red-500">{errors.title}</p>
        {/if}
      {:else}
        <p class="text-sm border px-3 py-2 rounded-md bg-muted/20">{formData.title}</p>
      {/if}
    </div>

    <div class="space-y-2 mt-4">
      <Label for="description">{t('task.description', {}, 'Mô tả')}</Label>
      {#if isEditing}
        <Textarea
          id="description"
          name="description"
          value={formData.description || ''}
          oninput={handleChange}
          placeholder={t('task.enter_description', {}, 'Mô tả chi tiết về nhiệm vụ')}
          rows={3}
        />
      {:else}
        <div class="text-sm border px-3 py-2 rounded-md bg-muted/20 whitespace-pre-wrap min-h-[60px]">
          {formData.description || t('task.no_description', {}, 'Không có mô tả')}
        </div>
      {/if}
    </div>
  </section>

  <!-- Các trường thông tin khác -->
  <section class="grid grid-cols-1 md:grid-cols-2 gap-4">
    <!-- Cột trái -->
    <div class="space-y-4">
      <!-- Status -->
      <div class="space-y-2">
        <Label for="status_id">{t('task.status', {}, 'Trạng thái')}</Label>
        {#if isEditing}
          <Select
            value={statusIdValue}
            onValueChange={(value) => { handleSelectChange('status_id', value) }}
          >
            <SelectTrigger class={errors.status_id ? 'border-red-500' : ''}>
              <span>{currentStatus?.name || t('task.select_status', {}, 'Chọn trạng thái')}</span>
            </SelectTrigger>
            <SelectContent>
              {#each statuses as status (status.id)}
                <SelectItem value={String(status.id)}>
                  <div class="flex items-center gap-2">
                    <div
                      class="h-3 w-3 rounded-full"
                      style:background-color={status.color || '#888'}
                    ></div>
                    {status.name}
                  </div>
                </SelectItem>
              {/each}
            </SelectContent>
          </Select>
          {#if errors.status_id}
            <p class="text-xs text-red-500">{errors.status_id}</p>
          {/if}
        {:else}
          <div class="flex items-center gap-2 border px-3 py-2 rounded-md bg-muted/20">
            {#if currentStatus}
              <div
                class="h-3 w-3 rounded-full"
                style:background-color={currentStatus.color || '#888'}
              ></div>
            {/if}
            <span>{currentStatus?.name || t('task.no_status', {}, 'Không có trạng thái')}</span>
          </div>
        {/if}
      </div>

      <!-- Priority -->
      <div class="space-y-2">
        <Label for="priority_id">{t('task.priority', {}, 'Độ ưu tiên')}</Label>
        {#if isEditing}
          <Select
            value={priorityIdValue}
            onValueChange={(value) => { handleSelectChange('priority_id', value) }}
          >
            <SelectTrigger>
              <span>{currentPriority?.name || t('task.select_priority', {}, 'Chọn độ ưu tiên')}</span>
            </SelectTrigger>
            <SelectContent>
              {#each priorities as priority (priority.id)}
                <SelectItem value={String(priority.id)}>
                  <div class="flex items-center gap-2">
                    <div
                      class="h-3 w-3 rounded-full"
                      style:background-color={priority.color || '#888'}
                    ></div>
                    {priority.name}
                  </div>
                </SelectItem>
              {/each}
            </SelectContent>
          </Select>
        {:else}
          <div class="flex items-center gap-2 border px-3 py-2 rounded-md bg-muted/20">
            {#if currentPriority}
              <div
                class="h-3 w-3 rounded-full"
                style:background-color={currentPriority.color || '#888'}
              ></div>
            {/if}
            <span>{currentPriority?.name || t('task.no_priority', {}, 'Không có độ ưu tiên')}</span>
          </div>
        {/if}
      </div>
    </div>

    <!-- Cột phải -->
    <div class="space-y-4">
      <!-- Label -->
      <div class="space-y-2">
        <Label for="label_id">{t('task.label', {}, 'Nhãn')}</Label>
        {#if isEditing}
          <Select
            value={labelIdValue}
            onValueChange={(value) => { handleSelectChange('label_id', value) }}
          >
            <SelectTrigger>
              <span>{currentLabel?.name || t('task.select_label', {}, 'Chọn nhãn')}</span>
            </SelectTrigger>
            <SelectContent>
              {#each labels as label (label.id)}
                <SelectItem value={String(label.id)}>
                  <div class="flex items-center gap-2">
                    <div
                      class="h-3 w-3 rounded-full"
                      style:background-color={label.color || '#888'}
                    ></div>
                    {label.name}
                  </div>
                </SelectItem>
              {/each}
            </SelectContent>
          </Select>
        {:else}
          <div class="flex items-center gap-2 border px-3 py-2 rounded-md bg-muted/20">
            {#if currentLabel}
              <div
                class="h-3 w-3 rounded-full"
                style:background-color={currentLabel.color || '#888'}
              ></div>
            {/if}
            <span>{currentLabel?.name || t('task.no_label', {}, 'Không có nhãn')}</span>
          </div>
        {/if}
      </div>

      <!-- Assigned To -->
      <div class="space-y-2">
        <Label for="assigned_to">{t('task.assigned_to', {}, 'Giao cho')}</Label>
        {#if isEditing}
          <Select
            value={assignedToValue}
            onValueChange={(value) => { handleSelectChange('assigned_to', value) }}
          >
            <SelectTrigger>
              <span>{currentAssignee ? (currentAssignee.username || currentAssignee.email) : t('task.select_assignee', {}, 'Chọn người thực hiện')}</span>
            </SelectTrigger>
            <SelectContent>
              {#each users as user (user.id)}
                <SelectItem value={String(user.id)}>
                  {user.username || user.email}
                </SelectItem>
              {/each}
            </SelectContent>
          </Select>
        {:else}
          <div class="border px-3 py-2 rounded-md bg-muted/20">
            <span>
              {currentAssignee ?
                (currentAssignee.username || currentAssignee.email)
                : t('task.unassigned', {}, 'Chưa giao')}
            </span>
          </div>
        {/if}
      </div>
    </div>
  </section>

  <!-- Due Date -->
  <section>
    <div class="space-y-2">
      <Label for="due_date">{t('task.due_date', {}, 'Ngày hết hạn')}</Label>
      {#if isEditing}
        <Popover.Root bind:open={datePickerOpen}>
          <Popover.Trigger asChild let:builder>
            <Button
              variant="outline"
              class={cn(
                'w-full justify-start text-left font-normal',
                !dueDate && 'text-muted-foreground'
              )}
              builders={[builder]}
            >
              <CalendarIcon class="mr-2 h-4 w-4" />
              {dueDate ? formatDate(formData.due_date) : t('task.select_due_date', {}, 'Chọn ngày hết hạn')}
            </Button>
          </Popover.Trigger>
          <Popover.Content class="w-auto p-0">
            <Calendar
              value={dueDate}
              onValueChange={(v) => {
                handleDateChange(v?.value)
                datePickerOpen = false
              }}
            />
          </Popover.Content>
        </Popover.Root>
      {:else}
        <div class="border px-3 py-2 rounded-md bg-muted/20">
          {formData.due_date ? formatDate(formData.due_date) : t('task.due_date_not_set', {}, 'Chưa thiết lập')}
        </div>
      {/if}
    </div>
  </section>
</div>

// inertia/pages/tasks/components/modals/task_detail_info/task_detail_fields.tsx
import React from 'react'
import { Input } from '@/components/ui/input'
import { Textarea } from '@/components/ui/textarea'
import { Label } from '@/components/ui/label'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import { Task } from '../../../types'
import { DatePicker } from '@/components/ui/date-picker'
import { cn } from '@/lib/utils'
import useTranslation from '@/hooks/use_translation'

interface TaskDetailFieldsProps {
  task: Task
  formData: Partial<Task>
  isEditing: boolean
  errors: Record<string, string>
  statuses: Array<{ id: number; name: string; color: string }>
  priorities: Array<{ id: number; name: string; color: string; value: number }>
  labels: Array<{ id: number; name: string; color: string }>
  users: Array<{ id: number; username: string; email: string }>
  handleChange: (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => void
  handleSelectChange: (name: string, value: string) => void
  handleDateChange: (date: Date | undefined) => void
}

export function TaskDetailFields({
  task,
  formData,
  isEditing,
  errors,
  statuses,
  priorities,
  labels,
  users,
  handleChange,
  handleSelectChange,
  handleDateChange
}: TaskDetailFieldsProps) {
  const { t } = useTranslation()

  // Format lại ngày hạn để hiển thị trong DatePicker
  const dueDate = formData.due_date ? new Date(formData.due_date) : undefined

  // Lấy ID từ các trường khác nhau (hỗ trợ nhiều định dạng backend)
  const statusId = formData.status_id || formData.statusId || task.status?.id;
  const priorityId = formData.priority_id || formData.priorityId || task.priority?.id;
  const labelId = formData.label_id || formData.labelId || task.label?.id;
  const assignedToId = formData.assigned_to || formData.assignedTo || formData.assignedToId;

  // Tìm các đối tượng hiện tại để hiển thị
  const currentStatus = statuses.find(s => s.id === Number(statusId)) || task.status;
  const currentPriority = priorities.find(p => p.id === Number(priorityId)) || task.priority;
  const currentLabel = labels.find(l => l.id === Number(labelId)) || task.label;
  const currentAssignee = users.find(u => u.id === Number(assignedToId)) || task.assignee;

  // Format ngày hạn để hiển thị khi không ở chế độ chỉnh sửa
  const formatDate = (dateString?: string) => {
    if (!dateString) return t('task.due_date_not_set', {}, 'Chưa thiết lập');
    try {
      const date = new Date(dateString);
      return date.toLocaleDateString('vi-VN');
    } catch (error) {
      return t('task.due_date_unknown', {}, 'Không xác định');
    }
  };

  // Xử lý giá trị mặc định cho các trường Select
  const getStatusIdValue = () => {
    const value = formData.status_id || formData.statusId || (task.status ? task.status.id : '');
    return String(value);
  };

  const getPriorityIdValue = () => {
    const value = formData.priority_id || formData.priorityId || (task.priority ? task.priority.id : '');
    return String(value);
  };

  const getLabelIdValue = () => {
    const value = formData.label_id || formData.labelId || (task.label ? task.label.id : '');
    return String(value);
  };

  const getAssignedToValue = () => {
    const value = formData.assigned_to || formData.assignedTo || formData.assignedToId || '';
    return String(value);
  };

  return (
    <div className="space-y-6">
      {/* Tiêu đề và mô tả */}
      <section>
        <div className="space-y-2">
          <Label htmlFor="title">{t('task.title', {}, 'Tiêu đề')}</Label>
          {isEditing ? (
            <>
              <Input
                id="title"
                name="title"
                value={formData.title || ''}
                onChange={handleChange}
                placeholder={t('task.enter_title', {}, 'Nhập tiêu đề nhiệm vụ')}
                className={errors.title ? 'border-red-500' : ''}
              />
              {errors.title && (
                <p className="text-xs text-red-500">{errors.title}</p>
              )}
            </>
          ) : (
            <p className="text-sm border px-3 py-2 rounded-md bg-muted/20">{formData.title}</p>
          )}
        </div>

        <div className="space-y-2 mt-4">
          <Label htmlFor="description">{t('task.description', {}, 'Mô tả')}</Label>
          {isEditing ? (
            <Textarea
              id="description"
              name="description"
              value={formData.description || ''}
              onChange={handleChange}
              placeholder={t('task.enter_description', {}, 'Mô tả chi tiết về nhiệm vụ')}
              rows={3}
            />
          ) : (
            <div className="text-sm border px-3 py-2 rounded-md bg-muted/20 whitespace-pre-wrap min-h-[60px]">
              {formData.description || t('task.no_description', {}, 'Không có mô tả')}
            </div>
          )}
        </div>
      </section>

      {/* Các trường thông tin khác */}
      <section className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {/* Cột trái */}
        <div className="space-y-4">
          {/* Status */}
          <div className="space-y-2">
            <Label htmlFor="status_id">{t('task.status', {}, 'Trạng thái')}</Label>
            {isEditing ? (
              <>
                <Select
                  value={getStatusIdValue()}
                  onValueChange={(value) => handleSelectChange('status_id', value)}
                >
                  <SelectTrigger id="status_id" className={errors.status_id ? 'border-red-500' : ''}>
                    <SelectValue placeholder={t('task.select_status', {}, 'Chọn trạng thái')} />
                  </SelectTrigger>
                  <SelectContent>
                    {statuses.map((status) => (
                      <SelectItem key={status.id} value={String(status.id)}>
                        <div className="flex items-center gap-2">
                          <div
                            className="h-3 w-3 rounded-full"
                            style={{ backgroundColor: status.color || '#888' }}
                          ></div>
                          {status.name}
                        </div>
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
                {errors.status_id && (
                  <p className="text-xs text-red-500">{errors.status_id}</p>
                )}
              </>
            ) : (
              <div className="flex items-center gap-2 border px-3 py-2 rounded-md bg-muted/20">
                {currentStatus && (
                  <div
                    className="h-3 w-3 rounded-full"
                    style={{ backgroundColor: currentStatus.color || '#888' }}
                  ></div>
                )}
                <span>{currentStatus?.name || t('task.no_status', {}, 'Không có trạng thái')}</span>
              </div>
            )}
          </div>

          {/* Priority */}
          <div className="space-y-2">
            <Label htmlFor="priority_id">{t('task.priority', {}, 'Độ ưu tiên')}</Label>
            {isEditing ? (
              <Select
                value={getPriorityIdValue()}
                onValueChange={(value) => handleSelectChange('priority_id', value)}
              >
                <SelectTrigger id="priority_id">
                  <SelectValue placeholder={t('task.select_priority', {}, 'Chọn độ ưu tiên')} />
                </SelectTrigger>
                <SelectContent>
                  {priorities.map((priority) => (
                    <SelectItem key={priority.id} value={String(priority.id)}>
                      <div className="flex items-center gap-2">
                        <div
                          className="h-3 w-3 rounded-full"
                          style={{ backgroundColor: priority.color || '#888' }}
                        ></div>
                        {priority.name}
                      </div>
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            ) : (
              <div className="flex items-center gap-2 border px-3 py-2 rounded-md bg-muted/20">
                {currentPriority && (
                  <div
                    className="h-3 w-3 rounded-full"
                    style={{ backgroundColor: currentPriority.color || '#888' }}
                  ></div>
                )}
                <span>{currentPriority?.name || t('task.no_priority', {}, 'Không có độ ưu tiên')}</span>
              </div>
            )}
          </div>
        </div>

        {/* Cột phải */}
        <div className="space-y-4">
          {/* Label */}
          <div className="space-y-2">
            <Label htmlFor="label_id">{t('task.label', {}, 'Nhãn')}</Label>
            {isEditing ? (
              <Select
                value={getLabelIdValue()}
                onValueChange={(value) => handleSelectChange('label_id', value)}
              >
                <SelectTrigger id="label_id">
                  <SelectValue placeholder={t('task.select_label', {}, 'Chọn nhãn')} />
                </SelectTrigger>
                <SelectContent>
                  {labels.map((label) => (
                    <SelectItem key={label.id} value={String(label.id)}>
                      <div className="flex items-center gap-2">
                        <div
                          className="h-3 w-3 rounded-full"
                          style={{ backgroundColor: label.color || '#888' }}
                        ></div>
                        {label.name}
                      </div>
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            ) : (
              <div className="flex items-center gap-2 border px-3 py-2 rounded-md bg-muted/20">
                {currentLabel && (
                  <div
                    className="h-3 w-3 rounded-full"
                    style={{ backgroundColor: currentLabel.color || '#888' }}
                  ></div>
                )}
                <span>{currentLabel?.name || t('task.no_label', {}, 'Không có nhãn')}</span>
              </div>
            )}
          </div>

          {/* Assigned To */}
          <div className="space-y-2">
            <Label htmlFor="assigned_to">{t('task.assigned_to', {}, 'Giao cho')}</Label>
            {isEditing ? (
              <Select
                value={getAssignedToValue()}
                onValueChange={(value) => handleSelectChange('assigned_to', value)}
              >
                <SelectTrigger id="assigned_to">
                  <SelectValue placeholder={t('task.select_assignee', {}, 'Chọn người thực hiện')} />
                </SelectTrigger>
                <SelectContent>
                  {users.map((user) => (
                    <SelectItem key={user.id} value={String(user.id)}>
                      {user.username || user.email}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            ) : (
              <div className="border px-3 py-2 rounded-md bg-muted/20">
                <span>
                  {currentAssignee ?
                    (currentAssignee.username || currentAssignee.email)
                    : t('task.unassigned', {}, 'Chưa giao')}
                </span>
              </div>
            )}
          </div>
        </div>
      </section>

      {/* Due Date */}
      <section>
        <div className="space-y-2">
          <Label htmlFor="due_date">{t('task.due_date', {}, 'Ngày hết hạn')}</Label>
          {isEditing ? (
            <DatePicker
              date={dueDate}
              onSelect={handleDateChange}
              placeholder={t('task.select_due_date', {}, 'Chọn ngày hết hạn')}
            />
          ) : (
            <div className="border px-3 py-2 rounded-md bg-muted/20">
              {formData.due_date ? formatDate(formData.due_date) : t('task.due_date_not_set', {}, 'Chưa thiết lập')}
            </div>
          )}
        </div>
      </section>
    </div>
  )
}
