// inertia/pages/users/pending_approval.svelte
<script lang="ts">
  import { router } from '@inertiajs/svelte'
  import AppLayout from '@/layouts/app_layout.svelte'
  import Button from '@/components/ui/button.svelte'
  import UserSearchForm from './components/UserSearchForm.svelte'
  import PendingApprovalTable from './components/PendingApprovalTable.svelte'
  import type { PendingApprovalProps } from './types'
  import { createPendingApproval } from './hooks/use_pending_approval.svelte'

  const { users, filters }: PendingApprovalProps = $props()

  let search = $state(filters.search || '')
  const { approveAllUsers } = createPendingApproval(users)

  function handleSearch(e: Event) {
    e.preventDefault()
    const queryParams = new URLSearchParams()

    if (search) queryParams.append('search', search)

    const queryString = queryParams.toString()
    router.get(`/users/pending-approval${queryString ? `?${queryString}` : ''}`)
  }
</script>

<svelte:head>
  <title>Phê duyệt người dùng</title>
</svelte:head>

<AppLayout title="Phê duyệt người dùng">
  <div class="container py-8">
    <div class="flex items-center justify-between">
      <h1 class="text-3xl font-bold">Phê duyệt người dùng</h1>
      <Button onclick={approveAllUsers} disabled={!users.data.length}>
        Phê duyệt tất cả
      </Button>
    </div>

    <div class="mt-6">
      <UserSearchForm
        {search}
        setSearch={(value) => { search = value }}
        {handleSearch}
      />
    </div>

    <div class="mt-6">
      <PendingApprovalTable
        {users}
        {filters}
      />
    </div>
  </div>
</AppLayout>

// inertia/pages/users/pending_approval.tsx
import React from 'react'
import { Head } from '@inertiajs/react'
import AppLayout from '@/layouts/app_layout'
import { Button } from '@/components/ui/button'
import useTranslation from '@/hooks/use_translation'
import UserSearchForm from './components/UserSearchForm'
import PendingApprovalTable from './components/PendingApprovalTable'
import type { PendingApprovalProps } from './types'
import { usePendingApproval } from './hooks/use_pending_approval'

export default function PendingApproval({ users, filters,  }: PendingApprovalProps) {
  const [search, setSearch] = React.useState(filters.search || '')
  const { t } = useTranslation()
  const { approveAllUsers } = usePendingApproval(users)

  const handleSearch = (e: React.FormEvent) => {
    e.preventDefault()
    const queryParams = new URLSearchParams()

    if (search) queryParams.append('search', search)

    const queryString = queryParams.toString()
    window.location.href = `/users/pending-approval${queryString ? `?${queryString}` : ''}`
  }

  return (
    <>
      <Head title={t('user.pending_approval', {}, "Phê duyệt người dùng")} />
      <div className="container py-8">
        <div className="flex items-center justify-between">
          <h1 className="text-3xl font-bold">{t('user.pending_approval', {}, "Phê duyệt người dùng")}</h1>
          <Button onClick={approveAllUsers} disabled={!users.data.length}>
            {t('user.approve_all', {}, "Phê duyệt tất cả")}
          </Button>
        </div>

        <div className="mt-6">
          <UserSearchForm
            search={search}
            setSearch={setSearch}
            handleSearch={handleSearch}
          />
        </div>

        <div className="mt-6">
          <PendingApprovalTable
            users={users}
            filters={filters}
          />
        </div>
      </div>
    </>
  )
}

PendingApproval.layout = (page: React.ReactNode) => <AppLayout title="Phê duyệt người dùng">{page}</AppLayout>
