// inertia/pages/tasks/components/modals/create_task_form.svelte
<script lang="ts">
  import BasicFields from './create_task_form/basic_fields.svelte'
  import MetadataFields from './create_task_form/metadata_fields.svelte'
  import DueDateField from './create_task_form/due_date_field.svelte'

  interface Props {
    formData: {
      title: string
      description: string
      status: string
      priority: string
      label: string
      assigned_to: string
      due_date: string
    }
    setFormData: (updater: (prev: typeof formData) => typeof formData) => void
    errors: Record<string, string>
    statuses: Array<{ value: string; label: string }>
    priorities: Array<{ value: string; label: string }>
    labels: Array<{ value: string; label: string }>
    users: Array<{ id: string; username: string; email: string }>
  }

  const { formData, setFormData, errors, statuses, priorities, labels, users }: Props = $props()

  const handleChange = (e: Event) => {
    const target = e.target as HTMLInputElement | HTMLTextAreaElement
    const { name, value } = target
    setFormData(prev => ({ ...prev, [name]: value }))
  }

  const handleSelectChange = (name: string, value: string) => {
    setFormData(prev => ({ ...prev, [name]: value }))
  }

  const handleDateChange = (date: Date | undefined) => {
    if (date) {
      setFormData(prev => ({
        ...prev,
        due_date: date.toISOString().split('T')[0]
      }))
    } else {
      setFormData(prev => ({ ...prev, due_date: '' }))
    }
  }
</script>

<div class="grid gap-4 py-4">
  <BasicFields
    {formData}
    {handleChange}
    {errors}
  />

  <MetadataFields
    {formData}
    {handleSelectChange}
    {errors}
    {statuses}
    {priorities}
    {labels}
    {users}
  />

  <DueDateField
    dueDate={formData.due_date ? new Date(formData.due_date) : undefined}
    onDateChange={handleDateChange}
    error={errors.due_date}
  />
</div>

// inertia/pages/tasks/components/modals/create_task_form.tsx
import React from 'react'
import { TaskFormBasicFields } from './create_task_form/basic_fields'
import { TaskFormMetadataFields } from './create_task_form/metadata_fields'
import { TaskFormDueDateField } from './create_task_form/due_date_field'

export interface CreateTaskFormProps {
  formData: {
    title: string
    description: string
    status_id: string
    priority_id: string
    label_id: string
    assigned_to: string
    due_date: string
  }
  setFormData: React.Dispatch<React.SetStateAction<{
    title: string
    description: string
    status_id: string
    priority_id: string
    label_id: string
    assigned_to: string
    due_date: string
  }>>
  errors: Record<string, string>
  statuses: Array<{ id: number; name: string }>
  priorities: Array<{ id: number; name: string }>
  labels: Array<{ id: number; name: string }>
  users: Array<{ id: number; username: string; email: string }>
}

export function CreateTaskForm({
  formData,
  setFormData,
  errors,
  statuses,
  priorities,
  labels,
  users
}: CreateTaskFormProps) {
  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
    const { name, value } = e.target
    setFormData(prev => ({ ...prev, [name]: value }))
  }

  const handleSelectChange = (name: string, value: string) => {
    setFormData(prev => ({ ...prev, [name]: value }))
  }

  const handleDateChange = (date: Date | undefined) => {
    if (date) {
      setFormData(prev => ({
        ...prev,
        due_date: date.toISOString().split('T')[0]
      }))
    } else {
      setFormData(prev => ({ ...prev, due_date: '' }))
    }
  }

  return (
    <div className="grid gap-4 py-4">
      <TaskFormBasicFields
        formData={formData}
        handleChange={handleChange}
        errors={errors}
      />

      <TaskFormMetadataFields
        formData={formData}
        handleSelectChange={handleSelectChange}
        errors={errors}
        statuses={statuses}
        priorities={priorities}
        labels={labels}
        users={users}
      />

      <TaskFormDueDateField
        dueDate={formData.due_date ? new Date(formData.due_date) : undefined}
        onDateChange={handleDateChange}
        error={errors.due_date}
      />
    </div>
  )
}
