// inertia/pages/tasks/components/modals/import_tasks_modal.svelte
<script lang="ts">
  import Dialog from '@/components/ui/dialog.svelte'
  import DialogContent from '@/components/ui/dialog_content.svelte'
  import DialogHeader from '@/components/ui/dialog_header.svelte'
  import DialogFooter from '@/components/ui/dialog_footer.svelte'
  import DialogTitle from '@/components/ui/dialog_title.svelte'
  import DialogDescription from '@/components/ui/dialog_description.svelte'
  import Button from '@/components/ui/button.svelte'
  import { router } from '@inertiajs/svelte'
  import Input from '@/components/ui/input.svelte'
  import Label from '@/components/ui/label.svelte'

  interface Props {
    open: boolean
    onOpenChange: (open: boolean) => void
  }

  let { open = $bindable(false), onOpenChange }: Props = $props()

  let file = $state<File | null>(null)
  let uploading = $state(false)
  let error = $state<string | null>(null)
  let fileInputElement: HTMLInputElement

  const handleFileChange = (e: Event) => {
    const target = e.target as HTMLInputElement
    const selectedFile = target.files?.[0]
    error = null

    if (!selectedFile) {
      file = null
      return
    }

    if (selectedFile.type !== 'text/csv' && !selectedFile.name.endsWith('.csv')) {
      error = 'Vui lòng chọn file CSV'
      file = null
      return
    }

    file = selectedFile
  }

  const handleImport = () => {
    if (!file) {
      error = 'Vui lòng chọn file CSV'
      return
    }

    uploading = true

    const formData = new FormData()
    formData.append('csv_file', file)

    router.post('/tasks/import', formData, {
      onSuccess: () => {
        uploading = false
        onOpenChange(false)
        file = null
        if (fileInputElement) {
          fileInputElement.value = ''
        }
      },
      onError: (errors) => {
        uploading = false
        error = errors.csv_file || 'Đã xảy ra lỗi khi import tasks'
      }
    })
  }

  const handleClose = () => {
    onOpenChange(false)
    file = null
    error = null
    if (fileInputElement) {
      fileInputElement.value = ''
    }
  }
</script>

<Dialog bind:open onOpenChange={onOpenChange}>
  <DialogContent class="sm:max-w-106.25">
    <DialogHeader>
      <DialogTitle>Import Tasks</DialogTitle>
      <DialogDescription>
        Import tasks quickly from a CSV file.
      </DialogDescription>
    </DialogHeader>

    <div class="grid gap-4 py-4">
      <div class="grid gap-2">
        <Label for="csv-file">File</Label>
        <Input
          bind:this={fileInputElement}
          id="csv-file"
          type="file"
          accept=".csv"
          onchange={handleFileChange}
        />
        {#if error}
          <p class="text-xs text-red-500">{error}</p>
        {/if}
      </div>
    </div>

    <DialogFooter>
      <Button
        variant="outline"
        onclick={handleClose}
        disabled={uploading}
      >
        Close
      </Button>
      <Button
        onclick={handleImport}
        disabled={!file || uploading}
      >
        {uploading ? 'Importing...' : 'Import'}
      </Button>
    </DialogFooter>
  </DialogContent>
</Dialog>

// inertia/pages/tasks/components/modals/import_tasks_modal.tsx
import React, { useState, useRef } from 'react'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog'
import { Button } from '@/components/ui/button'
import { router } from '@inertiajs/react'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'

interface ImportTasksModalProps {
  open: boolean
  onOpenChange: (open: boolean) => void
}

export function ImportTasksModal({ open, onOpenChange }: ImportTasksModalProps) {
  const [file, setFile] = useState<File | null>(null)
  const [uploading, setUploading] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const fileInputRef = useRef<HTMLInputElement>(null)

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const selectedFile = e.target.files?.[0]
    setError(null)
    
    if (!selectedFile) {
      setFile(null)
      return
    }
    
    // Kiểm tra loại file
    if (selectedFile.type !== 'text/csv' && !selectedFile.name.endsWith('.csv')) {
      setError('Vui lòng chọn file CSV')
      setFile(null)
      return
    }
    
    setFile(selectedFile)
  }

  const handleImport = () => {
    if (!file) {
      setError('Vui lòng chọn file CSV')
      return
    }
    
    setUploading(true)
    
    // Tạo FormData để upload file
    const formData = new FormData()
    formData.append('csv_file', file)
    
    // Sử dụng Inertia để gửi request
    router.post('/tasks/import', formData, {
      onSuccess: () => {
        setUploading(false)
        onOpenChange(false)
        setFile(null)
        if (fileInputRef.current) {
          fileInputRef.current.value = ''
        }
      },
      onError: (errors) => {
        setUploading(false)
        setError(errors.csv_file || 'Đã xảy ra lỗi khi import tasks')
      }
    })
  }

  const handleClose = () => {
    onOpenChange(false)
    setFile(null)
    setError(null)
    if (fileInputRef.current) {
      fileInputRef.current.value = ''
    }
  }

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-[425px]">
        <DialogHeader>
          <DialogTitle>Import Tasks</DialogTitle>
          <DialogDescription>
            Import tasks quickly from a CSV file.
          </DialogDescription>
        </DialogHeader>
        
        <div className="grid gap-4 py-4">
          <div className="grid gap-2">
            <Label htmlFor="csv-file">File</Label>
            <Input
              ref={fileInputRef}
              id="csv-file"
              type="file"
              accept=".csv"
              onChange={handleFileChange}
            />
            {error && (
              <p className="text-xs text-red-500">{error}</p>
            )}
          </div>
        </div>
        
        <DialogFooter>
          <Button 
            variant="outline" 
            onClick={handleClose}
            disabled={uploading}
          >
            Close
          </Button>
          <Button 
            onClick={handleImport}
            disabled={!file || uploading}
          >
            {uploading ? 'Importing...' : 'Import'}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}
