// inertia/pages/tasks/components/modals/task_detail_modal_footer.svelte
<script lang="ts">
  import DialogFooter from '@/components/ui/dialog_footer.svelte'
  import Button from '@/components/ui/button.svelte'
  import { CheckCircle2 } from 'lucide-svelte'

  interface Props {
    canDelete: boolean
    canMarkAsCompleted: boolean
    canEdit: boolean
    isEditing: boolean
    submitting: boolean
    onSoftDelete: () => void
    onMarkAsCompleted: () => void
    onSubmit: () => void
    onToggleEdit: () => void
    onClose: () => void
  }

  const {
    canDelete,
    canMarkAsCompleted,
    canEdit,
    isEditing,
    submitting,
    onSoftDelete,
    onMarkAsCompleted,
    onSubmit,
    onToggleEdit,
    onClose
  }: Props = $props()
</script>

<DialogFooter class="flex sm:justify-between flex-col sm:flex-row gap-3">
  {#if canDelete}
    <div class="flex gap-2">
      <Button variant="destructive" onclick={onSoftDelete}>
        Xóa
      </Button>
    </div>
  {/if}
  <div class="flex gap-2">
    {#if canMarkAsCompleted && !isEditing}
      <Button variant="secondary" onclick={onMarkAsCompleted}>
        <CheckCircle2 class="mr-2 h-4 w-4" />
        Đánh dấu hoàn thành
      </Button>
    {/if}
    {#if canEdit && isEditing}
      <Button onclick={onSubmit} disabled={submitting}>
        {submitting ? 'Đang lưu...' : 'Lưu thay đổi'}
      </Button>
    {/if}
    {#if canEdit && !isEditing}
      <Button variant="secondary" onclick={onToggleEdit}>
        Sửa
      </Button>
    {/if}
    {#if isEditing}
      <Button variant="outline" onclick={onToggleEdit}>
        Hủy
      </Button>
    {:else}
      <Button variant="outline" onclick={onClose}>
        Đóng
      </Button>
    {/if}
  </div>
</DialogFooter>

// inertia/pages/tasks/components/modals/task_detail_modal_footer.tsx

import { DialogFooter } from '@/components/ui/dialog'
import { Button } from '@/components/ui/button'
import { CheckCircle2 } from 'lucide-react'

type TaskDetailModalFooterProps = {
  canDelete: boolean
  canMarkAsCompleted: boolean
  canEdit: boolean
  isEditing: boolean
  submitting: boolean
  onSoftDelete: () => void
  onMarkAsCompleted: () => void
  onSubmit: () => void
  onToggleEdit: () => void
  onClose: () => void
}

export function TaskDetailModalFooter({
  canDelete,
  canMarkAsCompleted,
  canEdit,
  isEditing,
  submitting,
  onSoftDelete,
  onMarkAsCompleted,
  onSubmit,
  onToggleEdit,
  onClose
}: TaskDetailModalFooterProps) {
  return (
    <DialogFooter className="flex sm:justify-between flex-col sm:flex-row gap-3">
      {canDelete && (
        <div className="flex gap-2">
          <Button variant="destructive" onClick={onSoftDelete}>
            Xóa
          </Button>
        </div>
      )}
      <div className="flex gap-2">
        {canMarkAsCompleted && !isEditing && (
          <Button variant="secondary" onClick={onMarkAsCompleted}>
            <CheckCircle2 className="mr-2 h-4 w-4" />
            Đánh dấu hoàn thành
          </Button>
        )}
        {canEdit && isEditing && (
          <Button onClick={onSubmit} disabled={submitting}>
            {submitting ? 'Đang lưu...' : 'Lưu thay đổi'}
          </Button>
        )}
        {canEdit && !isEditing && (
          <Button variant="secondary" onClick={onToggleEdit}>
            Sửa
          </Button>
        )}
        {isEditing ? (
          <Button variant="outline" onClick={onToggleEdit}>
            Hủy
          </Button>
        ) : (
          <Button variant="outline" onClick={onClose}>
            Đóng
          </Button>
        )}
      </div>
    </DialogFooter>
  )
}
