// inertia/pages/tasks/components/modals/task_detail_modal_header.tsx
import React from 'react'
import { DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { Task } from '../../types'

type TaskDetailModalHeaderProps = {
  task: Task
}

export function TaskDetailModalHeader({ task }: TaskDetailModalHeaderProps) {
  return (
    <DialogHeader className="flex flex-row items-center">
      <div className="flex-1">
        <DialogTitle className="text-xl flex items-center gap-2">
          {task.status && (
            <span 
              className="inline-block w-3 h-3 rounded-full mr-2" 
              style={{ backgroundColor: task.status.color }}
            ></span>
          )}
          {task.id}: {task.title}
        </DialogTitle>
      </div>
    </DialogHeader>
  )
}

// inertia/pages/tasks/components/modals/task_detail_modal_header.svelte
<script lang="ts">
  import DialogHeader from '@/components/ui/dialog_header.svelte'
  import DialogTitle from '@/components/ui/dialog_title.svelte'
  import type { Task } from '../../types.svelte'

  interface Props {
    task: Task
  }

  const { task }: Props = $props()
</script>

<DialogHeader class="flex flex-row items-center">
  <div class="flex-1">
    <DialogTitle class="text-xl flex items-center gap-2">
      {#if task.status}
        <span
          class="inline-block w-3 h-3 rounded-full mr-2"
          style="background-color: {task.status.color}"
        ></span>
      {/if}
      {task.id}: {task.title}
    </DialogTitle>
  </div>
</DialogHeader>
