// inertia/pages/tasks/components/task_list/task_list_header.svelte
<script lang="ts">
  import Checkbox from '@/components/ui/checkbox.svelte'

  interface Props {
    isAllSelected: boolean
    onSelectAll: (checked: boolean) => void
  }

  const { isAllSelected, onSelectAll }: Props = $props()
</script>

<div class="flex items-center justify-between p-2 border-b">
  <div class="flex items-center space-x-2">
    <Checkbox
      checked={isAllSelected}
      onCheckedChange={onSelectAll}
      aria-label="Select all tasks"
    />
    <span class="text-sm font-medium">Tất cả nhiệm vụ</span>
  </div>
</div>

// inertia/pages/tasks/components/task_list/task_list_header.tsx

import { Checkbox } from '@/components/ui/checkbox'

type TaskListHeaderProps = {
  isAllSelected: boolean
  onSelectAll: (checked: boolean) => void
}

export function TaskListHeader({
  isAllSelected,
  onSelectAll
}: TaskListHeaderProps) {
  return (
    <div className="flex items-center justify-between p-2 border-b">
      <div className="flex items-center space-x-2">
        <Checkbox
          checked={isAllSelected}
          onCheckedChange={onSelectAll}
          aria-label="Select all tasks"
        />
        <span className="text-sm font-medium">Tất cả nhiệm vụ</span>
      </div>
    </div>
  )
}
