// inertia/apps/org/modules/tasks/components/task_list/task_item_delete_button.svelte
<script lang="ts">
  import { router } from '@inertiajs/svelte'
  import { Trash2 } from 'lucide-svelte'
  import { buttonVariants } from '@/apps/org/shared/ui/button_variants'

  import AlertDialogRoot from '@/apps/org/shared/ui/alert_dialog.svelte'
  import AlertDialogAction from '@/apps/org/shared/ui/alert_dialog_action.svelte'
  import AlertDialogCancel from '@/apps/org/shared/ui/alert_dialog_cancel.svelte'
  import AlertDialogContent from '@/apps/org/shared/ui/alert_dialog_content.svelte'
  import AlertDialogDescription from '@/apps/org/shared/ui/alert_dialog_description.svelte'
  import AlertDialogFooter from '@/apps/org/shared/ui/alert_dialog_footer.svelte'
  import AlertDialogHeader from '@/apps/org/shared/ui/alert_dialog_header.svelte'
  import AlertDialogTitle from '@/apps/org/shared/ui/alert_dialog_title.svelte'
  import { notificationStore } from '@/apps/org/shared/stores/notification_store.svelte'
  import { useTranslation } from '@/apps/org/shared/stores/translation.svelte'

  import type { TaskDetail } from '@/apps/org/modules/tasks/types/index.svelte'

  interface Props {
    task: TaskDetail
    currentUser: {
      id?: string | number
      role?: string
      organization_id?: string | number
    }
  }

  const { task, currentUser }: Props = $props()
  let deleteDialogOpen = $state(false)
  const { t } = useTranslation()

  // Check whether the current user can delete this task.
  const canDeleteTask = () => {
    if (!currentUser.id) {
      return false
    }

    const isSuperAdmin = currentUser.role === 'superadmin'
    if (isSuperAdmin) {
      return true
    }

    const taskOrgId = task.organization_id
    const userOrgId = currentUser.organization_id

    if (taskOrgId && userOrgId && taskOrgId !== userOrgId) {
      return false
    }

    if (currentUser.role === 'admin') {
      return true
    }

    const creatorId = task.creator_id || (task.creator?.id)
    const isCreator = Boolean(creatorId && creatorId === currentUser.id)

    if (isCreator) {
      return true
    }

    return false
  }

  const openDeleteConfirm = (e: MouseEvent) => {
    e.preventDefault()
    e.stopPropagation()
    deleteDialogOpen = true
  }

  const confirmDeleteTask = () => {
    router.delete(`/tasks/${task.id}`, {
      onSuccess: () => {
        deleteDialogOpen = false
      },
      onError: (errors: unknown) => {
        console.error('Error deleting task:', errors)
        notificationStore.error(
          t('task.delete_error_title', {}, 'Unable to delete task'),
          t('task.delete_error_description', {}, 'Please try again.')
        )
      },
      preserveScroll: true,
      preserveState: true,
      replace: true,
      only: ['tasks']
    })
  }

  const hasPermission = $derived(canDeleteTask())
</script>

{#if hasPermission}
  <button
    class="inline-flex items-center justify-center h-5 w-5 rounded-md hover:bg-accent hover:text-accent-foreground"
    onclick={openDeleteConfirm}
    title={t('task.delete_task', {}, 'Delete task')}
    aria-label={t('task.delete_task', {}, 'Delete task')}
  >
    <Trash2 class="h-3 w-3 text-destructive" />
  </button>

  <AlertDialogRoot bind:open={deleteDialogOpen}>
    <AlertDialogContent>
      <AlertDialogHeader>
        <AlertDialogTitle>{t('task.delete_confirm_title', {}, 'Delete task?')}</AlertDialogTitle>
        <AlertDialogDescription>
          {t('task.delete_confirm_description', { title: task.title }, 'Are you sure you want to delete task ":title"?')}
          {t('task.action_irreversible', {}, 'This action cannot be undone.')}
        </AlertDialogDescription>
      </AlertDialogHeader>
      <AlertDialogFooter>
        <AlertDialogCancel>{t('common.cancel', {}, 'Cancel')}</AlertDialogCancel>
        <AlertDialogAction
          onclick={confirmDeleteTask}
          class={buttonVariants({ variant: 'destructive' })}
        >
          {t('common.delete', {}, 'Delete')}
        </AlertDialogAction>
      </AlertDialogFooter>
    </AlertDialogContent>
  </AlertDialogRoot>
{/if}

// inertia/pages/tasks/components/task_list/task_item_delete_button.tsx
import React, { useState } from 'react'
import { Button } from '@/components/ui/button'
import { Trash2 } from 'lucide-react'
import type { Task } from '../../types'
import { router } from '@inertiajs/react'
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from '@/components/ui/alert_dialog'

type TaskItemDeleteButtonProps = {
  task: Task
  currentUser: {
    id?: string | number
    role?: string
    organization_id?: string | number
  }
}

export function TaskItemDeleteButton({ task, currentUser }: TaskItemDeleteButtonProps) {
  const [deleteDialogOpen, setDeleteDialogOpen] = useState(false);

  // Kiểm tra quyền xóa task
  const canDeleteTask = () => {
    // Không có thông tin người dùng
    if (!currentUser || !currentUser.id) {
      return false
    }

    // Kiểm tra xem người dùng là superadmin không
    const isSuperAdmin = currentUser.role === 'superadmin'

    // Superadmin luôn có quyền xóa task
    if (isSuperAdmin) {
      return true
    }

    // Kiểm tra task và tổ chức
    const taskOrgId = task.organization_id
    const userOrgId = currentUser.organization_id

    // Kiểm tra nếu không cùng tổ chức
    if (taskOrgId && userOrgId && taskOrgId !== userOrgId) {
      return false
    }

    // Là admin trong cùng tổ chức
    if (currentUser.role === 'admin') {
      return true
    }

    // Là người tạo task
    const creatorId = task.creator_id || (task.creator && task.creator.id)
    const isCreator = creatorId && Number(creatorId) === Number(currentUser.id)

    if (isCreator) {
      return true
    }

    return false
  }

  // Mở dialog xác nhận xóa
  const openDeleteConfirm = (e: React.MouseEvent) => {
    e.preventDefault()
    e.stopPropagation()
    setDeleteDialogOpen(true)
  }

  // Xử lý xóa task khi đã xác nhận
  const confirmDeleteTask = () => {
    router.delete(`/tasks/${task.id}`, {
      onSuccess: () => {
        setDeleteDialogOpen(false)
      },
      onError: (errors: unknown) => {
        // Xử lý lỗi
        console.error('Lỗi khi xóa task:', errors)
        alert('Có lỗi xảy ra khi xóa nhiệm vụ. Vui lòng thử lại.')
      },
      preserveScroll: true,
      preserveState: false,
      replace: true,
      only: ['tasks']
    })
  }

  // Kiểm tra quyền và hiển thị nút
  const hasPermission = canDeleteTask()

  // Chỉ hiển thị nút nếu có quyền xóa
  if (!hasPermission) return null

  return (
    <>
      <Button
        variant="ghost"
        size="icon"
        className="h-5 w-5"
        onClick={openDeleteConfirm}
        title="Xóa nhiệm vụ"
      >
        <Trash2 className="h-3 w-3 text-red-500" />
      </Button>

      {/* Dialog xác nhận xóa task */}
      <AlertDialog open={deleteDialogOpen} onOpenChange={setDeleteDialogOpen}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Xác nhận xóa nhiệm vụ</AlertDialogTitle>
            <AlertDialogDescription>
              Bạn có chắc chắn muốn xóa nhiệm vụ "{task.title}"?
              Hành động này không thể hoàn tác.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>Hủy</AlertDialogCancel>
            <AlertDialogAction
              onClick={confirmDeleteTask}
              className="bg-red-500 hover:bg-red-600"
            >
              Xóa
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </>
  )
}
