// inertia/pages/tasks/components/task_list/task_list_pagination.tsx
import React from 'react'
import { Pagination } from '@/components/ui/pagination'

type TaskListPaginationProps = {
  meta: {
    total: number
    per_page: number
    current_page: number
    last_page: number
  }
  rowsPerPage: number
  onRowsPerPageChange: (e: React.ChangeEvent<HTMLSelectElement>) => void
  filters: unknown
}

export function TaskListPagination({
  meta,
  rowsPerPage,
  onRowsPerPageChange,
  filters
}: TaskListPaginationProps) {
  return (
    <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between px-3 py-2 gap-2">
      <div className="flex flex-col sm:flex-row sm:items-center sm:space-x-6 text-sm gap-2">
        <div className="flex items-center space-x-2">
          <span className="text-xs whitespace-nowrap">Rows per page</span>
          <select
            value={rowsPerPage}
            onChange={onRowsPerPageChange}
            className="h-8 w-16 rounded-md border border-input text-xs"
          >
            <option value="5">5</option>
            <option value="10">10</option>
            <option value="20">20</option>
            <option value="50">50</option>
          </select>
        </div>
        <div className="text-xs text-muted-foreground">
          Page {meta.current_page} of {meta.last_page}
        </div>
      </div>

      <Pagination
        baseUrl="/tasks"
        totalPages={meta.last_page}
        currentPage={meta.current_page}
        queryParams={filters}
      />
    </div>
  )
}

// inertia/apps/org/modules/tasks/components/task_list/task_list_pagination.svelte
<script lang="ts">
  import { buildOffsetPagination } from '@/apps/org/shared/lib/pagination'
  import type { OffsetPagePagination } from '@/apps/org/shared/lib/pagination'
  import UnifiedOffsetPagination from '@/apps/org/shared/ui/unified_offset_pagination.svelte'
  import { FRONTEND_ROUTES } from '@/apps/org/shared/constants'
import { TASKS_UI } from '@/apps/org/modules/tasks/constants/tasks'

  interface Props {
    baseRoute?: string
    meta: {
      total: number
      per_page: number
      current_page: number
      last_page: number
    }
    rowsPerPage: number
    onRowsPerPageChange: (e: Event) => void
    filters: Record<string, unknown>
  }

  const { baseRoute = FRONTEND_ROUTES.TASKS, meta, rowsPerPage, onRowsPerPageChange, filters }: Props = $props()
  const rowOptions = TASKS_UI.ROWS_PER_PAGE_OPTIONS
  const pagination = $derived<OffsetPagePagination>(buildOffsetPagination({
    total: meta.total,
    page: meta.current_page,
    perPage: meta.per_page,
    lastPage: meta.last_page,
  }))
</script>

<div class="flex flex-col sm:flex-row sm:items-center sm:justify-between px-3 py-2 gap-2">
  <div class="flex flex-col sm:flex-row sm:items-center sm:space-x-6 text-sm gap-2">
    <div class="flex items-center space-x-2">
      <span class="text-xs whitespace-nowrap">Rows per page</span>
      <select
        value={rowsPerPage}
        onchange={onRowsPerPageChange}
        class="h-8 w-16 rounded-md border border-input text-xs"
      >
        {#each rowOptions as option}
          <option value={option}>{option}</option>
        {/each}
      </select>
    </div>
    <div class="text-xs text-muted-foreground">
      Page {pagination.page} of {pagination.lastPage}
    </div>
  </div>

  <UnifiedOffsetPagination
    {pagination}
    baseUrl={baseRoute}
    queryParams={filters}
  />
</div>
