// inertia/pages/tasks/components/filters/tasks_filters.svelte
<script lang="ts">
  import type { Snippet } from 'svelte'
  import Input from '@/components/ui/input.svelte'
  import Tabs from '@/components/ui/tabs.svelte'
  import TabsContent from '@/components/ui/tabs_content.svelte'
  import TabsList from '@/components/ui/tabs_list.svelte'
  import TabsTrigger from '@/components/ui/tabs_trigger.svelte'
  import Select from '@/components/ui/select.svelte'
  import SelectContent from '@/components/ui/select_content.svelte'
  import SelectItem from '@/components/ui/select_item.svelte'
  import SelectTrigger from '@/components/ui/select_trigger.svelte'
  import { Search } from 'lucide-svelte'
  import { useTranslation } from '@/stores/translation.svelte'

  interface TasksFiltersProps {
    filters: {
      status?: string
      priority?: string
      label?: string
      search?: string
      assigned_to?: string
    }
    metadata: {
      statuses: Array<{ id: number; name: string; color: string }>
      labels: Array<{ id: number; name: string; color: string }>
      priorities: Array<{ id: number; name: string; color: string; value: number }>
    }
    onSearch: (query: string) => void
    onStatusChange: (status: string) => void
    onPriorityChange: (priority: string) => void
    onTabChange: (tab: string) => void
    searchQuery: string
    selectedStatus: string
    selectedPriority: string
    activeTab: string
    children: Snippet
  }

  const {
    metadata,
    onSearch,
    onStatusChange,
    onPriorityChange,
    onTabChange,
    searchQuery,
    selectedStatus,
    selectedPriority,
    activeTab,
    children
  }: TasksFiltersProps = $props()

  const { t } = useTranslation()
  let localSearchQuery = $state(searchQuery)
  let searchTimer: number | null = null

  // Sync với prop searchQuery khi thay đổi từ bên ngoài
  $effect(() => {
    localSearchQuery = searchQuery
  })

  // Xử lý debounce cho search query
  $effect(() => {
    if (searchTimer) clearTimeout(searchTimer)

    searchTimer = setTimeout(() => {
      if (localSearchQuery !== searchQuery) {
        onSearch(localSearchQuery)
      }
    }, 300) as unknown as number

    return () => {
      if (searchTimer) clearTimeout(searchTimer)
    }
  })

  function handleSearchChange(e: Event) {
    const target = e.target as HTMLInputElement
    localSearchQuery = target.value
  }

  function handleKeyPress(e: KeyboardEvent) {
    if (e.key === 'Enter') {
      onSearch(localSearchQuery)
    }
  }

  function handleSearchClick() {
    onSearch(localSearchQuery)
  }
</script>

<div class="flex flex-col space-y-1">
  <Tabs value={activeTab} onValueChange={onTabChange}>
    <div class="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-2 mb-2">
      <div class="flex items-center gap-2">
        <div class="relative">
          <Input
            placeholder={t('task.search', {}, 'Tìm nhiệm vụ...')}
            value={localSearchQuery}
            oninput={handleSearchChange}
            onkeyup={handleKeyPress}
            class="w-full sm:w-70 pl-8 h-7 text-sm"
          />
          <button
            class="absolute left-2 top-1/2 transform -translate-y-1/2 cursor-pointer"
            onclick={handleSearchClick}
            type="button"
            aria-label="Search"
          >
            <Search class="h-4 w-4 text-muted-foreground" />
          </button>
        </div>

        <TabsList class="h-7">
          <TabsTrigger value="all" class="text-xs px-3 py-0.5">{t('common.all', {}, 'Tất cả')}</TabsTrigger>
          <TabsTrigger value="pending" class="text-xs px-3 py-0.5">{t('task.status_todo', {}, 'Đang chờ')}</TabsTrigger>
          <TabsTrigger value="completed" class="text-xs px-3 py-0.5">{t('task.status_done', {}, 'Đã hoàn thành')}</TabsTrigger>
        </TabsList>
      </div>

      <div class="flex gap-2">
        <Select value={selectedStatus} onValueChange={onStatusChange}>
          <SelectTrigger class="w-30 h-7 text-xs" placeholder={t('task.status', {}, 'Trạng thái')} />
          <SelectContent>
            <SelectItem value="all">{t('common.all', {}, 'Tất cả')}</SelectItem>
            {#each metadata.statuses as status}
              <SelectItem value={status.id.toString()}>
                {status.name}
              </SelectItem>
            {/each}
          </SelectContent>
        </Select>

        <Select value={selectedPriority} onValueChange={onPriorityChange}>
          <SelectTrigger class="w-30 h-7 text-xs" placeholder={t('task.priority', {}, 'Ưu tiên')} />
          <SelectContent>
            <SelectItem value="all">{t('common.all', {}, 'Tất cả')}</SelectItem>
            {#each metadata.priorities as priority}
              <SelectItem value={priority.id.toString()}>
                {priority.name}
              </SelectItem>
            {/each}
          </SelectContent>
        </Select>
      </div>
    </div>

    <TabsContent value={activeTab} class="pt-0 mt-0">
      {@render children()}
    </TabsContent>
  </Tabs>
</div>

// inertia/pages/tasks/components/filters/tasks_filters.tsx
import React, { ReactNode, useEffect, useState } from 'react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import { Search } from 'lucide-react'
import useTranslation from '@/hooks/use_translation'

interface TasksFiltersProps {
  filters: {
    status?: string
    priority?: string
    label?: string
    search?: string
    assigned_to?: string
  }
  metadata: {
    statuses: Array<{ id: number; name: string; color: string }>
    labels: Array<{ id: number; name: string; color: string }>
    priorities: Array<{ id: number; name: string; color: string; value: number }>
  }
  onSearch: (query: string) => void
  onStatusChange: (status: string) => void
  onPriorityChange: (priority: string) => void
  onTabChange: (tab: string) => void
  searchQuery: string
  setSearchQuery: (query: string) => void
  selectedStatus: string
  selectedPriority: string
  activeTab: string
  children: ReactNode
}

export function TasksFilters({
  filters,
  metadata,
  onSearch,
  onStatusChange,
  onPriorityChange,
  onTabChange,
  searchQuery,
  setSearchQuery,
  selectedStatus,
  selectedPriority,
  activeTab,
  children
}: TasksFiltersProps) {
  const { t } = useTranslation()
  const [debouncedQuery, setDebouncedQuery] = useState(searchQuery);
  
  // Xử lý debounce cho search query
  useEffect(() => {
    const timer = setTimeout(() => {
      if (debouncedQuery !== searchQuery) {
        onSearch(debouncedQuery);
      }
    }, 300);
    
    return () => clearTimeout(timer);
  }, [debouncedQuery, onSearch]);
  
  // Xử lý thay đổi giá trị tìm kiếm
  const handleSearchChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setDebouncedQuery(e.target.value);
  };
  
  // Xử lý khi nhấn Enter trong ô tìm kiếm
  const handleKeyPress = (e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key === 'Enter') {
      onSearch(debouncedQuery);
    }
  };
  
  // Xử lý khi click vào biểu tượng tìm kiếm
  const handleSearchClick = () => {
    onSearch(debouncedQuery);
  };

  return (
    <div className="flex flex-col space-y-1">
      <Tabs value={activeTab} onValueChange={onTabChange} className="w-full">
        <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-2 mb-2">
          <div className="flex items-center gap-2">
            <div className="relative">
              <Input
                placeholder={t('task.search', {}, 'Tìm nhiệm vụ...')}
                value={debouncedQuery}
                onChange={handleSearchChange}
                onKeyUp={handleKeyPress}
                className="w-full sm:w-[280px] pl-8 h-7 text-sm"
              />
              <div 
                className="absolute left-2 top-1/2 transform -translate-y-1/2 cursor-pointer"
                onClick={handleSearchClick}
              >
                <Search className="h-4 w-4 text-muted-foreground" />
              </div>
            </div>
            
            <TabsList className="h-7">
              <TabsTrigger value="all" className="text-xs px-3 py-0.5">{t('common.all', {}, 'Tất cả')}</TabsTrigger>
              <TabsTrigger value="pending" className="text-xs px-3 py-0.5">{t('task.status_todo', {}, 'Đang chờ')}</TabsTrigger>
              <TabsTrigger value="completed" className="text-xs px-3 py-0.5">{t('task.status_done', {}, 'Đã hoàn thành')}</TabsTrigger>
            </TabsList>
          </div>
          
          <div className="flex gap-2">
            <Select value={selectedStatus} onValueChange={onStatusChange}>
              <SelectTrigger className="w-[120px] h-7 text-xs">
                <SelectValue placeholder={t('task.status', {}, 'Trạng thái')} />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="all">{t('common.all', {}, 'Tất cả')}</SelectItem>
                {metadata.statuses.map((status) => (
                  <SelectItem key={status.id} value={status.id.toString()}>
                    {status.name}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
            
            <Select value={selectedPriority} onValueChange={onPriorityChange}>
              <SelectTrigger className="w-[120px] h-7 text-xs">
                <SelectValue placeholder={t('task.priority', {}, 'Ưu tiên')} />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="all">{t('common.all', {}, 'Tất cả')}</SelectItem>
                {metadata.priorities.map((priority) => (
                  <SelectItem key={priority.id} value={priority.id.toString()}>
                    {priority.name}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
        </div>
        
        <TabsContent value={activeTab} className="pt-0 mt-0">
          {children}
        </TabsContent>
      </Tabs>
    </div>
  )
}
