// inertia/pages/tasks/components/task_list/task_list_row.tsx
import React from 'react'
import {
  TableRow,
  TableCell
} from "@/components/ui/table"
import { Checkbox } from '@/components/ui/checkbox'
import { ChevronDown, ChevronRight } from 'lucide-react'
import { Task } from '../../types'
import { ChildTaskRow } from './child_task_row'
import { TaskItemDeleteButton } from './task_item_delete_button'
import { TaskStatusCell } from './cells/status_cell'
import { TaskLabelCell } from './cells/label_cell'
import { TaskPriorityCell } from './cells/priority_cell'
import { TaskAssigneeCell } from './cells/assignee_cell'
import { TaskDateCell } from './cells/date_cell'
import { TaskDueDateCell } from './cells/due_date_cell'


type TaskListRowProps = {
  task: Task
  isTaskSelected: (taskId: number) => boolean
  handleSelectTask: (taskId: number, checked: boolean) => void
  hasChildTasks: (task: Task) => boolean
  isTaskExpanded: (taskId: number) => boolean
  toggleExpandTask: (taskId: number) => void
  isTaskCompleted: (task: Task) => boolean
  currentUserInfo: {
    id?: string | number
    role?: string
    organization_id?: string | number
  }
  formatDate: (dateString: string) => string
  onToggleStatus: (task: Task, newStatusId: number) => void
  onTaskClick?: (task: Task) => void
}

export function TaskListRow({
  task,
  isTaskSelected,
  handleSelectTask,
  hasChildTasks,
  isTaskExpanded,
  toggleExpandTask,
  isTaskCompleted,
  currentUserInfo,
  formatDate,
  onTaskClick
}: TaskListRowProps) {
  const isCompleted = isTaskCompleted(task);
  const statusName = task.status?.name?.toLowerCase() || '';
  const priorityName = task.priority?.name?.toLowerCase() || '';
  const hasChildren = hasChildTasks(task);
  const isExpanded = isTaskExpanded(task.id);

  // Xác định class và style dựa vào trạng thái
  const titleClass = isCompleted ? 'line-through text-muted-foreground' : '';

  // Hàm xử lý click vào task
  const handleTaskClick = (e: React.MouseEvent) => {
    e.preventDefault();
    e.stopPropagation();

    if (onTaskClick) {
      onTaskClick(task);
    }
  };

  return (
    <React.Fragment>
      <TableRow className="min-h-[44px]">
        <TableCell className="px-2 py-1">
          <Checkbox
            id={`select-task-${task.id}`}
            checked={isTaskSelected(task.id)}
            onCheckedChange={(checked) => handleSelectTask(task.id, !!checked)}
            className="h-4 w-4"
          />
        </TableCell>
        <TableCell className="px-2 py-1 whitespace-nowrap text-xs">
          <div className="flex items-center gap-1">
            {hasChildren && (
              <button
                onClick={(e) => {
                  e.preventDefault();
                  e.stopPropagation();
                  toggleExpandTask(task.id);
                }}
                className="h-4 w-4 rounded hover:bg-muted flex items-center justify-center"
              >
                {isExpanded ? (
                  <ChevronDown className="h-3 w-3" />
                ) : (
                  <ChevronRight className="h-3 w-3" />
                )}
              </button>
            )}
            <span>TASK-{task.id}</span>
          </div>
        </TableCell>
        <TableCell className="px-2 py-1 text-xs" onClick={handleTaskClick} style={{ cursor: 'pointer' }}>
          <div className={`flex flex-col ${titleClass}`}>
            <span className="font-medium">{task.title}</span>
            {task.description && (
              <span className="text-[11px] text-muted-foreground line-clamp-1">{task.description}</span>
            )}
          </div>
        </TableCell>
        <TableCell className="px-2 py-1">
          <TaskStatusCell task={task} statusName={statusName} />
        </TableCell>
        <TableCell className="px-2 py-1">
          <TaskLabelCell task={task} />
        </TableCell>
        <TableCell className="px-2 py-1">
          <TaskPriorityCell task={task} priorityName={priorityName} />
        </TableCell>
        <TableCell className="px-2 py-1 text-xs">
          <TaskAssigneeCell task={task} />
        </TableCell>
        <TableCell className="px-2 py-1 text-xs">
          <TaskDateCell task={task} formatDate={formatDate} />
        </TableCell>
        <TableCell className="px-2 py-1 text-xs">
          <TaskDueDateCell task={task} formatDate={formatDate} />
        </TableCell>
        <TableCell className="px-2 py-1">
          <TaskItemDeleteButton
            task={task}
            currentUser={currentUserInfo}
          />
        </TableCell>
      </TableRow>

      {/* Hiển thị Task con nếu có và đang mở rộng */}
      {isExpanded && hasChildren && task.childTasks && task.childTasks.map(childTask => (
        <ChildTaskRow
          key={`subtask-${childTask.id}`}
          childTask={childTask}
          isTaskSelected={isTaskSelected}
          handleSelectTask={handleSelectTask}
          isTaskCompleted={isTaskCompleted}
          formatDate={formatDate}
          currentUserInfo={currentUserInfo}
          onTaskClick={onTaskClick}
        />
      ))}
    </React.Fragment>
  )
}

// inertia/apps/user/modules/tasks/components/task_list/task_list_row.svelte
<script lang="ts">
  import { ChevronDown, ChevronRight } from 'lucide-svelte'

  import Checkbox from '@/apps/user/shared/ui/checkbox.svelte'
  import TableCell from '@/apps/user/shared/ui/table_cell.svelte'
  import TableRow from '@/apps/user/shared/ui/table_row.svelte'

  import type { TaskDetail } from '@/apps/user/modules/tasks/types/index.svelte'

  import AssigneeCell from '@/apps/user/modules/tasks/components/task_list/cells/assignee_cell.svelte'
  import DateCell from '@/apps/user/modules/tasks/components/task_list/cells/date_cell.svelte'
  import DueDateCell from '@/apps/user/modules/tasks/components/task_list/cells/due_date_cell.svelte'
  import LabelCell from '@/apps/user/modules/tasks/components/task_list/cells/label_cell.svelte'
  import PriorityCell from '@/apps/user/modules/tasks/components/task_list/cells/priority_cell.svelte'
  import StatusCell from '@/apps/user/modules/tasks/components/task_list/cells/status_cell.svelte'
  import ChildTaskRow from '@/apps/user/modules/tasks/components/task_list/child_task_row.svelte'
  import TaskItemDeleteButton from '@/apps/user/modules/tasks/components/task_list/task_item_delete_button.svelte'

  interface Props {
    task: TaskDetail
    isTaskSelected: (taskId: string) => boolean
    handleSelectTask: (taskId: string, checked: boolean) => void
    hasChildTasks: (task: TaskDetail) => boolean
    isTaskExpanded: (taskId: string) => boolean
    toggleExpandTask: (taskId: string) => void
    isTaskCompleted: (task: TaskDetail) => boolean
    currentUserInfo: {
      id?: string
      role?: string
      organization_id?: string
    }
    formatDate: (dateString: string) => string
    onTaskClick?: (task: TaskDetail) => void
  }

  const {
    task,
    isTaskSelected,
    handleSelectTask,
    hasChildTasks,
    isTaskExpanded,
    toggleExpandTask,
    isTaskCompleted,
    currentUserInfo,
    formatDate,
    onTaskClick
  }: Props = $props()

  const isCompleted = $derived(isTaskCompleted(task))
  const statusName = $derived((task.status || '').toLowerCase())
  const priorityName = $derived(task.priority.toLowerCase())
  const hasChildren = $derived(hasChildTasks(task))
  const isExpanded = $derived(isTaskExpanded(task.id))
  const titleClass = $derived(isCompleted ? 'line-through text-muted-foreground' : '')

  const handleTaskClick = (e: MouseEvent) => {
    e.preventDefault()
    e.stopPropagation()

    if (onTaskClick) {
      onTaskClick(task)
    }
  }

  const handleExpandClick = (e: MouseEvent) => {
    e.preventDefault()
    e.stopPropagation()
    toggleExpandTask(task.id)
  }
</script>

<TableRow class="min-h-11">
  <TableCell class="px-2 py-1">
    <Checkbox
      id="select-task-{task.id}"
      checked={isTaskSelected(task.id)}
      onCheckedChange={(checked: boolean | 'indeterminate') => { handleSelectTask(task.id, checked === true) }}
      class="h-4 w-4"
    />
  </TableCell>
  <TableCell class="px-2 py-1 whitespace-nowrap text-xs">
    <div class="flex items-center gap-1">
      {#if hasChildren}
        <button
          onclick={handleExpandClick}
          class="h-4 w-4 rounded hover:bg-muted flex items-center justify-center"
        >
          {#if isExpanded}
            <ChevronDown class="h-3 w-3" />
          {:else}
            <ChevronRight class="h-3 w-3" />
          {/if}
        </button>
      {/if}
      <span>TASK-{task.id}</span>
    </div>
  </TableCell>
  <TableCell class="px-2 py-1 text-xs cursor-pointer" onclick={handleTaskClick}>
    <div class="flex flex-col {titleClass}">
      <span class="font-medium">{task.title}</span>
      {#if task.project}
        <span class="text-[10px] text-muted-foreground/70">
          <span class="inline-flex items-center">
            <svg class="w-3 h-3 mr-1" fill="currentColor" viewBox="0 0 20 20">
              <path d="M9 2a1 1 0 000 2h2a1 1 0 100-2H9z"></path>
              <path fill-rule="evenodd" d="M4 5a2 2 0 012-2 3 3 0 003 3h2a3 3 0 003-3 2 2 0 012 2v11a2 2 0 01-2 2H6a2 2 0 01-2-2V5zm3 4a1 1 0 000 2h.01a1 1 0 100-2H7zm3 0a1 1 0 000 2h3a1 1 0 100-2h-3zm-3 4a1 1 0 100 2h.01a1 1 0 100-2H7zm3 0a1 1 0 100 2h3a1 1 0 100-2h-3z" clip-rule="evenodd"></path>
            </svg>
            {task.project.name}
          </span>
        </span>
      {/if}
      {#if task.description}
        <span class="text-[11px] text-muted-foreground line-clamp-1">{task.description}</span>
      {/if}
    </div>
  </TableCell>
  <TableCell class="px-2 py-1">
    <StatusCell {task} {statusName} />
  </TableCell>
  <TableCell class="px-2 py-1">
    <LabelCell {task} />
  </TableCell>
  <TableCell class="px-2 py-1">
    <PriorityCell {task} {priorityName} />
  </TableCell>
  <TableCell class="px-2 py-1 text-xs">
    <AssigneeCell {task} />
  </TableCell>
  <TableCell class="px-2 py-1 text-xs">
    <DateCell {task} {formatDate} />
  </TableCell>
  <TableCell class="px-2 py-1 text-xs">
    <DueDateCell {task} {formatDate} />
  </TableCell>
  <TableCell class="px-2 py-1">
    <TaskItemDeleteButton
      {task}
      currentUser={currentUserInfo}
    />
  </TableCell>
</TableRow>

{#if isExpanded && hasChildren && task.childTasks}
  {#each task.childTasks as childTask (childTask.id)}
    <ChildTaskRow
      {childTask}
      {isTaskSelected}
      {handleSelectTask}
      {formatDate}
      currentUserInfo={currentUserInfo}
    />
  {/each}
{/if}
