// inertia/components/coming_soon.tsx
import { Plane } from 'lucide-react'

export default function ComingSoon() {
  return (
    <div className='h-svh'>
      <div className='m-auto flex h-full w-full flex-col items-center justify-center gap-2'>
        <Plane size={72} />
        <h1 className='text-4xl leading-tight font-bold'>Coming Soon 👀</h1>
        <p className='text-muted-foreground text-center'>
          This page has not been created yet. <br />
          Stay tuned though!
        </p>
      </div>
    </div>
  )
}

// inertia/components/coming_soon.svelte
<script lang="ts">
  import { Plane } from 'lucide-svelte'
</script>

<div class="h-svh">
  <div class="m-auto flex h-full w-full flex-col items-center justify-center gap-2">
    <Plane size={72} />
    <h1 class="text-4xl leading-tight font-bold">Coming Soon 👀</h1>
    <p class="text-muted-foreground text-center">
      This page has not been created yet. <br />
      Stay tuned though!
    </p>
  </div>
</div>
