// inertia/components/profile_dropdown.svelte
<script lang="ts">
  import { page, router, Link } from '@inertiajs/svelte'
  import Avatar from '@/components/ui/avatar.svelte'
  import AvatarFallback from '@/components/ui/avatar_fallback.svelte'
  import AvatarImage from '@/components/ui/avatar_image.svelte'
  import Button from '@/components/ui/button.svelte'
  import DropdownMenu from '@/components/ui/dropdown_menu.svelte'
  import DropdownMenuContent from '@/components/ui/dropdown_menu_content.svelte'
  import DropdownMenuGroup from '@/components/ui/dropdown_menu_group.svelte'
  import DropdownMenuItem from '@/components/ui/dropdown_menu_item.svelte'
  import DropdownMenuLabel from '@/components/ui/dropdown_menu_label.svelte'
  import DropdownMenuSeparator from '@/components/ui/dropdown_menu_separator.svelte'
  import DropdownMenuShortcut from '@/components/ui/dropdown_menu_shortcut.svelte'
  import DropdownMenuTrigger from '@/components/ui/dropdown_menu_trigger.svelte'

  interface AuthUser {
    id?: string
    username?: string
    email?: string
  }

  interface PageProps {
    auth?: {
      user?: AuthUser
    }
    [key: string]: unknown
  }

  const props = $derived($page.props as unknown as PageProps)
  const user = $derived(props.auth?.user)

  // Tạo tên hiển thị từ thông tin người dùng
  const displayName = $derived(user ? (user.username || user.email || 'User') : '')
  const userEmail = $derived(user?.email || '')
  const avatarUrl = $derived(user ? `/avatars/${user.username || 'unknown'}.jpg` : '')
  const initials = $derived(user ? (user.username?.[0]?.toUpperCase() || user.email?.[0]?.toUpperCase() || 'U') : '!')

  // Di chuyển console.error vào effect
  $effect(() => {
    if (!user && import.meta.env.MODE === 'development') {
      console.error('ProfileDropdown: Không có thông tin người dùng')
    }
  })
</script>

{#if !user}
  <Button variant="ghost" class="relative h-8 w-8 rounded-full" disabled>
    <Avatar class="h-8 w-8">
      <AvatarFallback>!</AvatarFallback>
    </Avatar>
  </Button>
{:else}
  <DropdownMenu>
    <DropdownMenuTrigger>
      <Button variant="ghost" class="relative h-8 w-8 rounded-full">
        <Avatar class="h-8 w-8">
          <AvatarImage src={avatarUrl} alt={displayName} />
          <AvatarFallback>{initials}</AvatarFallback>
        </Avatar>
      </Button>
    </DropdownMenuTrigger>
    <DropdownMenuContent class="w-56" align="end">
      <DropdownMenuLabel class="font-normal">
        <div class="flex flex-col space-y-1">
          <p class="text-sm leading-none font-medium">{displayName}</p>
          <p class="text-muted-foreground text-xs leading-none">
            {userEmail}
          </p>
        </div>
      </DropdownMenuLabel>
      <DropdownMenuSeparator />
      <DropdownMenuGroup>
        <DropdownMenuItem>
          <Link href="/settings">
            Hồ sơ
            <DropdownMenuShortcut>⇧⌘P</DropdownMenuShortcut>
          </Link>
        </DropdownMenuItem>
        <DropdownMenuItem>
          <Link href="/settings">
            Thanh toán
            <DropdownMenuShortcut>⌘B</DropdownMenuShortcut>
          </Link>
        </DropdownMenuItem>
        <DropdownMenuItem>
          <Link href="/settings">
            Cài đặt
            <DropdownMenuShortcut>⌘S</DropdownMenuShortcut>
          </Link>
        </DropdownMenuItem>
        <DropdownMenuItem>Nhóm mới</DropdownMenuItem>
      </DropdownMenuGroup>
      <DropdownMenuSeparator />
      <DropdownMenuItem
        onclick={(e: MouseEvent) => {
          e.preventDefault()
          router.post('/logout', {}, {
            onError: (errors) => { console.error('[ProfileDropdown] Logout error:', errors) },
          })
        }}
      >
        Đăng xuất
        <DropdownMenuShortcut>⇧⌘Q</DropdownMenuShortcut>
      </DropdownMenuItem>
    </DropdownMenuContent>
  </DropdownMenu>
{/if}

// inertia/components/profile_dropdown.tsx
import { useEffect } from 'react'
import { Link, usePage, router } from '@inertiajs/react'
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar'
import { Button } from '@/components/ui/button'
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuGroup,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuShortcut,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown_menu'


export function ProfileDropdown() {
  const { auth } = usePage().props as unknown
  const user = auth?.user

  // Di chuyển console.error vào useEffect
  useEffect(() => {
    if (!user) {
      // Only log in development
      if (import.meta.env.NODE_ENV === 'development') {
        console.error('ProfileDropdown: Không có thông tin người dùng')
      }
    }
  }, [user])

  // Nếu không có người dùng, không hiển thị dropdown
  if (!user) {
    return (
      <Button variant='ghost' className='relative h-8 w-8 rounded-full' disabled>
        <Avatar className='h-8 w-8'>
          <AvatarFallback>!</AvatarFallback>
        </Avatar>
      </Button>
    )
  }

  // Tạo initials từ tên người dùng
  const getInitials = (name: string) => {
    if (!name) return 'NA'
    return name
      .split(' ')
      .map((part) => part[0])
      .join('')
      .toUpperCase()
      .substring(0, 2)
  }

  // Tạo tên hiển thị từ thông tin người dùng
  const displayName = user.username || user.email || 'User'

  const userEmail = user.email || ''
  const avatarUrl = `/avatars/${user.username || 'unknown'}.jpg`
  const initials = user.username?.[0]?.toUpperCase() || user.email?.[0]?.toUpperCase() || 'U'

  return (
    <DropdownMenu modal={false}>
      <DropdownMenuTrigger asChild>
        <Button variant='ghost' className='relative h-8 w-8 rounded-full'>
          <Avatar className='h-8 w-8'>
            <AvatarImage src={avatarUrl} alt={displayName} />
            <AvatarFallback>{initials}</AvatarFallback>
          </Avatar>
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent className='w-56' align='end' forceMount>
        <DropdownMenuLabel className='font-normal'>
          <div className='flex flex-col space-y-1'>
            <p className='text-sm leading-none font-medium'>{displayName}</p>
            <p className='text-muted-foreground text-xs leading-none'>
              {userEmail}
            </p>
          </div>
        </DropdownMenuLabel>
        <DropdownMenuSeparator />
        <DropdownMenuGroup>
          <DropdownMenuItem asChild>
            <Link href='/settings'>
              Hồ sơ
              <DropdownMenuShortcut>⇧⌘P</DropdownMenuShortcut>
            </Link>
          </DropdownMenuItem>
          <DropdownMenuItem asChild>
            <Link href='/settings'>
              Thanh toán
              <DropdownMenuShortcut>⌘B</DropdownMenuShortcut>
            </Link>
          </DropdownMenuItem>
          <DropdownMenuItem asChild>
            <Link href='/settings'>
              Cài đặt
              <DropdownMenuShortcut>⌘S</DropdownMenuShortcut>
            </Link>
          </DropdownMenuItem>
          <DropdownMenuItem>Nhóm mới</DropdownMenuItem>
        </DropdownMenuGroup>
        <DropdownMenuSeparator />
        <DropdownMenuItem
          onClick={(e) => {
            e.preventDefault()
            router.post('/logout', {}, {
              onError: (errors) => { console.error('[ProfileDropdown] Logout error:', errors); },
            })
          }}
        >
          Đăng xuất
          <DropdownMenuShortcut>⇧⌘Q</DropdownMenuShortcut>
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  )
}
