// inertia/components/select_dropdown.svelte
<script lang="ts">
  import { Loader } from 'lucide-svelte'
  import { cn } from '$lib/utils-svelte'
  import FormControl from '@/components/ui/form_control.svelte'
  import Select from '@/components/ui/select.svelte'
  import SelectContent from '@/components/ui/select_content.svelte'
  import SelectItem from '@/components/ui/select_item.svelte'
  import SelectTrigger from '@/components/ui/select_trigger.svelte'
  import SelectValue from '@/components/ui/select_value.svelte'

  interface SelectDropdownProps {
    onValueChange?: (value: string) => void
    defaultValue?: string
    placeholder?: string
    isPending?: boolean
    items?: { label: string; value: string }[]
    disabled?: boolean
    class?: string
    isControlled?: boolean
  }

  const {
    defaultValue,
    onValueChange,
    isPending = false,
    items = [],
    placeholder = 'Select',
    disabled = false,
    class: className = '',
    isControlled = false,
  }: SelectDropdownProps = $props()

  let value = $state(defaultValue)

  function handleValueChange(newValue: string) {
    if (!isControlled) {
      value = newValue
    }
    onValueChange?.(newValue)
  }
</script>

<Select
  value={isControlled ? defaultValue : value}
  onValueChange={handleValueChange}
>
  <FormControl>
    <SelectTrigger {disabled} class={cn(className)}>
      <SelectValue {placeholder} />
    </SelectTrigger>
  </FormControl>
  <SelectContent>
    {#if isPending}
      <SelectItem disabled value="loading" class="h-14">
        <div class="flex items-center justify-center gap-2">
          <Loader class="h-5 w-5 animate-spin" />
          {' '}
          Loading...
        </div>
      </SelectItem>
    {:else}
      {#each items as item}
        <SelectItem value={item.value}>
          {item.label}
        </SelectItem>
      {/each}
    {/if}
  </SelectContent>
</Select>

// inertia/components/select_dropdown.tsx
import { Loader, Loader2 } from 'lucide-react'
import { cn } from '@/lib/utils'
import { FormControl } from '@/components/ui/form'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'

interface SelectDropdownProps {
  onValueChange?: (value: string) => void
  defaultValue: string | undefined
  placeholder?: string
  isPending?: boolean
  items: { label: string; value: string }[] | undefined
  disabled?: boolean
  className?: string
  isControlled?: boolean
}

export function SelectDropdown({
  defaultValue,
  onValueChange,
  isPending,
  items,
  placeholder,
  disabled,
  className = '',
  isControlled = false,
}: SelectDropdownProps) {
  const defaultState = isControlled
    ? { value: defaultValue, onValueChange }
    : { defaultValue, onValueChange }
  return (
    <Select {...defaultState}>
      <FormControl>
        <SelectTrigger disabled={disabled} className={cn(className)}>
          <SelectValue placeholder={placeholder ?? 'Select'} />
        </SelectTrigger>
      </FormControl>
      <SelectContent>
        {isPending ? (
          <SelectItem disabled value='loading' className='h-14'>
            <div className='flex items-center justify-center gap-2'>
              <Loader className='h-5 w-5 animate-spin' />
              {'  '}
              Loading...
            </div>
          </SelectItem>
        ) : (
          items?.map(({ label, value }) => (
            <SelectItem key={value} value={value}>
              {label}
            </SelectItem>
          ))
        )}
      </SelectContent>
    </Select>
  )
}
