// inertia/pages/tasks/components/form_fields/label_field.tsx
import React from 'react'
import type { Task } from '../../types'
import { Label } from '@/components/ui/label'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'

interface LabelFieldProps {
  formData: Partial<Task>
  handleSelectChange: (name: string, value: string) => void
  canEdit: boolean
  labels: Array<{ id: number; name: string; color: string }>
  task: Task
}

export const LabelField: React.FC<LabelFieldProps> = ({
  formData, handleSelectChange, canEdit, labels, task
}) => {
  // Lọc để tìm label hiện tại
  const currentLabel = labels.find(l => l.id === (formData.label_id || task.label_id))

  return (
    <div className="grid gap-2">
      <Label htmlFor="label_id">Nhãn</Label>
      {canEdit ? (
        <Select
          value={String(formData.label_id || '')}
          onValueChange={(value) => handleSelectChange('label_id', value)}
        >
          <SelectTrigger>
            <SelectValue placeholder="Chọn nhãn" />
          </SelectTrigger>
          <SelectContent>
            {labels.map((label) => (
              <SelectItem key={label.id} value={String(label.id)}>
                <div className="flex items-center">
                  <span
                    className="inline-block w-3 h-3 rounded-full mr-2"
                    style={{ backgroundColor: label.color }}
                  ></span>
                  {label.name}
                </div>
              </SelectItem>
            ))}
          </SelectContent>
        </Select>
      ) : (
        <div className="p-2 border rounded-md flex items-center">
          {currentLabel ? (
            <>
              <span
                className="inline-block w-3 h-3 rounded-full mr-2"
                style={{ backgroundColor: currentLabel.color }}
              ></span>
              {currentLabel.name}
            </>
          ) : (
            "Không xác định"
          )}
        </div>
      )}
    </div>
  )
}

// inertia/pages/tasks/components/form_fields/label_field.svelte
<script lang="ts">
  import type { Task } from '../../types'
  import Label from '@/components/ui/label.svelte'
  import Select from '@/components/ui/select.svelte'
  import SelectContent from '@/components/ui/select_content.svelte'
  import SelectItem from '@/components/ui/select_item.svelte'
  import SelectTrigger from '@/components/ui/select_trigger.svelte'
  import SelectValue from '@/components/ui/select_value.svelte'

  interface Props {
    formData: Partial<Task>
    handleSelectChange: (name: string, value: string) => void
    canEdit: boolean
    labels: Array<{ id: number; name: string; color: string }>
    task: Task
  }

  const { formData, handleSelectChange, canEdit, labels, task }: Props = $props()

  const currentLabel = $derived(labels.find(l => l.id === (formData.label_id || task.label_id)))
</script>

<div class="grid gap-2">
  <Label for="label_id">Nhãn</Label>
  {#if canEdit}
    <Select
      value={String(formData.label_id || '')}
      onValueChange={(value) => { handleSelectChange('label_id', value); }}
    >
      <SelectTrigger>
        <SelectValue placeholder="Chọn nhãn" />
      </SelectTrigger>
      <SelectContent>
        {#each labels as label (label.id)}
          <SelectItem value={String(label.id)}>
            <div class="flex items-center">
              <span
                class="inline-block w-3 h-3 rounded-full mr-2"
                style="background-color: {label.color}"
              ></span>
              {label.name}
            </div>
          </SelectItem>
        {/each}
      </SelectContent>
    </Select>
  {:else}
    <div class="p-2 border rounded-md flex items-center">
      {#if currentLabel}
        <span
          class="inline-block w-3 h-3 rounded-full mr-2"
          style="background-color: {currentLabel.color}"
        ></span>
        {currentLabel.name}
      {:else}
        Không xác định
      {/if}
    </div>
  {/if}
</div>
