// inertia/pages/tasks/components/form_fields/priority_field.svelte
<script lang="ts">
  import type { Task } from '../../types'
  import Label from '@/components/ui/label.svelte'
  import Select from '@/components/ui/select.svelte'
  import SelectContent from '@/components/ui/select_content.svelte'
  import SelectItem from '@/components/ui/select_item.svelte'
  import SelectTrigger from '@/components/ui/select_trigger.svelte'
  import SelectValue from '@/components/ui/select_value.svelte'

  interface Props {
    formData: Partial<Task>
    handleSelectChange: (name: string, value: string) => void
    canEdit: boolean
    priorities: Array<{ id: number; name: string; color: string; value: number }>
    task: Task
  }

  const { formData, handleSelectChange, canEdit, priorities, task }: Props = $props()

  const currentPriority = $derived(priorities.find(p => p.id === (formData.priority_id || task.priority_id)))
</script>

<div class="grid gap-2">
  <Label for="priority_id">Độ ưu tiên</Label>
  {#if canEdit}
    <Select
      value={String(formData.priority_id || '')}
      onValueChange={(value) => { handleSelectChange('priority_id', value); }}
    >
      <SelectTrigger>
        <SelectValue placeholder="Chọn độ ưu tiên" />
      </SelectTrigger>
      <SelectContent>
        {#each priorities as priority (priority.id)}
          <SelectItem value={String(priority.id)}>
            <div class="flex items-center">
              <span
                class="inline-block w-3 h-3 rounded-full mr-2"
                style="background-color: {priority.color}"
              ></span>
              {priority.name}
            </div>
          </SelectItem>
        {/each}
      </SelectContent>
    </Select>
  {:else}
    <div class="p-2 border rounded-md flex items-center">
      {#if currentPriority}
        <span
          class="inline-block w-3 h-3 rounded-full mr-2"
          style="background-color: {currentPriority.color}"
        ></span>
        {currentPriority.name}
      {:else}
        Không xác định
      {/if}
    </div>
  {/if}
</div>

// inertia/pages/tasks/components/form_fields/priority_field.tsx
import React from 'react'
import { Task } from '../../types'
import { Label } from '@/components/ui/label'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'

interface PriorityFieldProps {
  formData: Partial<Task>
  handleSelectChange: (name: string, value: string) => void
  canEdit: boolean
  priorities: Array<{ id: number; name: string; color: string; value: number }>
  task: Task
}

export const PriorityField: React.FC<PriorityFieldProps> = ({ 
  formData, handleSelectChange, canEdit, priorities, task 
}) => {
  // Lọc để tìm priority hiện tại
  const currentPriority = priorities.find(p => p.id === (formData.priority_id || task.priority_id))
  
  return (
    <div className="grid gap-2">
      <Label htmlFor="priority_id">Độ ưu tiên</Label>
      {canEdit ? (
        <Select
          value={String(formData.priority_id || '')}
          onValueChange={(value) => handleSelectChange('priority_id', value)}
        >
          <SelectTrigger>
            <SelectValue placeholder="Chọn độ ưu tiên" />
          </SelectTrigger>
          <SelectContent>
            {priorities.map((priority) => (
              <SelectItem key={priority.id} value={String(priority.id)}>
                <div className="flex items-center">
                  <span 
                    className="inline-block w-3 h-3 rounded-full mr-2" 
                    style={{ backgroundColor: priority.color }}
                  ></span>
                  {priority.name}
                </div>
              </SelectItem>
            ))}
          </SelectContent>
        </Select>
      ) : (
        <div className="p-2 border rounded-md flex items-center">
          {currentPriority ? (
            <>
              <span 
                className="inline-block w-3 h-3 rounded-full mr-2" 
                style={{ backgroundColor: currentPriority.color }}
              ></span>
              {currentPriority.name}
            </>
          ) : (
            "Không xác định"
          )}
        </div>
      )}
    </div>
  )
}
