// inertia/apps/org/shared/components/layout/notification_dropdown.svelte
<script lang="ts">
  import { Link, router } from '@inertiajs/svelte'
  import { format } from 'date-fns'
  import { Bell, Check, LoaderCircle, Trash2 } from 'lucide-svelte'

  import Button from '@/apps/org/shared/ui/button.svelte'
  import DropdownMenu from '@/apps/org/shared/ui/dropdown_menu.svelte'
  import DropdownMenuContent from '@/apps/org/shared/ui/dropdown_menu_content.svelte'
  import DropdownMenuItem from '@/apps/org/shared/ui/dropdown_menu_item.svelte'
  import DropdownMenuLabel from '@/apps/org/shared/ui/dropdown_menu_label.svelte'
  import DropdownMenuSeparator from '@/apps/org/shared/ui/dropdown_menu_separator.svelte'
  import DropdownMenuTrigger from '@/apps/org/shared/ui/dropdown_menu_trigger.svelte'
  import { FRONTEND_NOTIFICATION_TYPES } from '@/apps/org/modules/notifications/constants/notifications'
  import { dateFnsLocale, dateTimePattern } from '@/apps/org/shared/lib/date_locale'
  import { postUiTelemetry } from '@/apps/org/shared/lib/ui_telemetry'
  import { useNotifications } from '@/apps/org/modules/notifications/stores/notifications.svelte'
  import {
    notificationInboxUrl,
    resolveNotificationDeepLink,
  } from '@/apps/shared/notifications/notification_deep_links'
  import { useTranslation } from '@/apps/org/shared/hooks/use_translation.svelte'


  interface NotificationDropdownProps {
    class?: string
  }

  const { class: className = '' }: NotificationDropdownProps = $props()
  let open = $state(false)
  let activeDropdownSessionId = $state<string | null>(null)
  const notificationShell = 'org'

  const notificationState = useNotifications()
  const { locale, t } = $derived(useTranslation())

  // Format time with defensive parsing.
  function formatTime(dateString: string): string {
    try {
      if (!dateString) {
        return t('common.unknown_time', {}, 'Unknown time')
      }

      let date: Date

      if (dateString.includes('T') && dateString.includes('Z')) {
        date = new Date(dateString)
      } else {
        date = new Date(dateString)

        if (isNaN(date.getTime())) {
          const parts = /^(\d{4})-(\d{2})-(\d{2})\s+(\d{2}):(\d{2}):(\d{2})$/.exec(dateString)
          if (parts) {
            const [, year, month, day, hour, minute, second] = parts
            if (year && month && day && hour && minute && second) {
              date = new Date(
                parseInt(year),
                parseInt(month) - 1,
                parseInt(day),
                parseInt(hour),
                parseInt(minute),
                parseInt(second)
              )
            }
          }
        }
      }

      if (isNaN(date.getTime())) {
        return t('common.invalid_date', {}, 'Invalid date')
      }

      return format(date, dateTimePattern(locale), { locale: dateFnsLocale(locale) })
    } catch (err) {
      console.error('Failed to format notification time:', err, dateString)
      return t('common.unknown_time', {}, 'Unknown time')
    }
  }

  function getNotificationResolution(notification: typeof notificationState.notifications[number]) {
    return resolveNotificationDeepLink(notification, notificationShell)
  }

  function handleNotificationClick(notification: typeof notificationState.notifications[number]) {
    const dropdownSessionId = activeDropdownSessionId
    void postUiTelemetry({
      eventName: 'notifications.ui.item_clicked',
      module: 'notifications',
      subsystem: 'notification_dropdown',
      workflow: 'notification_dropdown',
      eventFamily: 'ui',
      surface: 'notification_dropdown',
      frontendSubmissionId: dropdownSessionId,
      targetType: notification.relatedEntityType ?? 'notification',
      targetId: notification.relatedEntityId ?? notification.id,
      metadata: {
        notification_id: notification.id,
        notification_type: notification.type,
        is_read: notification.isRead,
      },
      persist: true,
    }).catch(() => {})
    if (!notification.isRead) {
      void notificationState.markAsRead(notification.id)
    }
    const { url } = getNotificationResolution(notification)
    if (url) {
      open = false
      router.visit(url)
    }
  }
</script>

<DropdownMenu
  bind:open
  onOpenChange={(nextOpen: boolean) => {
    open = nextOpen
    if (nextOpen) {
      activeDropdownSessionId = crypto.randomUUID()
      void postUiTelemetry({
        eventName: 'notifications.ui.opened',
        module: 'notifications',
        subsystem: 'notification_dropdown',
        workflow: 'notification_dropdown',
        eventFamily: 'ui',
        surface: 'notification_dropdown',
        frontendSubmissionId: activeDropdownSessionId,
        metadata: {
          unread_count: notificationState.unreadCount,
        },
      }).catch(() => {})
      void notificationState.refresh()
    }
  }}
>
  <DropdownMenuTrigger>
    <div class="relative inline-flex h-9 w-9 cursor-pointer items-center justify-center rounded-md text-muted-foreground hover:bg-accent hover:text-foreground {className}">
      <Bell class="h-5 w-5" />
      {#if notificationState.unreadCount > 0}
        <span class="absolute top-0 right-0 h-2 w-2 rounded-full bg-destructive"></span>
      {/if}
    </div>
  </DropdownMenuTrigger>
  <DropdownMenuContent class="w-80 max-h-[480px] flex flex-col p-0 overflow-hidden" align="end">
    <DropdownMenuLabel class="flex items-center justify-between p-4 pb-2">
      <span>{t('notifications.title', {}, 'Notifications')}</span>
      {#if notificationState.unreadCount > 0}
        <span class="bg-primary text-primary-foreground text-xs font-medium px-2 py-1 rounded-full">
          {notificationState.unreadCount}
        </span>
      {/if}
    </DropdownMenuLabel>

    <DropdownMenuSeparator />

    <!-- Scrollable Notification List Container -->
    <div class="flex-1 overflow-y-auto max-h-[280px]">
      {#if notificationState.loading}
        <div class="flex items-center justify-center py-8">
          <LoaderCircle class="h-6 w-6 animate-spin text-primary" />
        </div>
      {:else if notificationState.error}
        <div class="py-6 text-center text-destructive text-sm px-4">
          {notificationState.error}
        </div>
      {:else if notificationState.notifications.length === 0}
        <div class="py-8 text-center text-muted-foreground text-sm px-4">
          {t('notifications.no_notifications', {}, 'No notifications')}
        </div>
      {:else}
        <div class="divide-y divide-border/40">
          {#each notificationState.notifications as notification}
            <DropdownMenuItem
              class="flex flex-col items-start p-4 cursor-pointer focus:bg-muted/50 {notification.isRead ? 'bg-muted/50' : 'bg-background'}"
              onclick={() => { handleNotificationClick(notification) }}
            >
              <div class="w-full">
                <div class="flex justify-between items-start">
                  <div class="flex-1">
                    <!-- Notification content -->
                    {#if notification.type === FRONTEND_NOTIFICATION_TYPES.TASK_OVERDUE}
                      <div>
                        <p class="font-medium text-destructive">{notification.title || t('notifications.no_title', {}, 'No title')}</p>
                        <p class="text-sm text-muted-foreground mt-1">{notification.message || t('notifications.no_message', {}, 'No message')}</p>
                        {#if getNotificationResolution(notification).unresolvedReason}
                          <p class="text-xs text-muted-foreground mt-2">
                            {getNotificationResolution(notification).unresolvedReason}
                          </p>
                        {/if}
                      </div>
                    {:else}
                      <div>
                        <p class="font-medium">{notification.title || t('notifications.no_title', {}, 'No title')}</p>
                        <p class="text-sm text-muted-foreground mt-1">{notification.message || t('notifications.no_message', {}, 'No message')}</p>
                        {#if getNotificationResolution(notification).unresolvedReason}
                          <p class="text-xs text-muted-foreground mt-2">
                            {getNotificationResolution(notification).unresolvedReason}
                          </p>
                        {/if}
                      </div>
                    {/if}
                  </div>
                  <div class="flex gap-1 ml-2">
                    {#if !notification.isRead}
                        <Button
                          variant="ghost"
                          size="icon"
                          class="h-6 w-6"
                          onclick={(e: MouseEvent) => {
                            e.stopPropagation()
                            void postUiTelemetry({
                              eventName: 'notifications.ui.marked_read',
                              module: 'notifications',
                              subsystem: 'notification_dropdown',
                              workflow: 'notification_dropdown',
                              eventFamily: 'ui',
                              surface: 'notification_dropdown',
                              frontendSubmissionId: activeDropdownSessionId,
                              targetType: 'notification',
                              targetId: notification.id,
                              metadata: {
                                notification_type: notification.type,
                              },
                              persist: true,
                            }).catch(() => {})
                            void notificationState.markAsRead(notification.id)
                          }}
                        >
                        <Check class="h-3 w-3" />
                      </Button>
                    {/if}
                    <Button
                      variant="ghost"
                      size="icon"
                      class="h-6 w-6"
                      onclick={(e: MouseEvent) => {
                        e.stopPropagation()
                        void notificationState.deleteNotification(notification.id)
                      }}
                    >
                      <Trash2 class="h-3 w-3" />
                    </Button>
                  </div>
                </div>
                <div class="text-xs text-muted-foreground mt-2">
                  {formatTime(notification.createdAt)}
                </div>
              </div>
            </DropdownMenuItem>
          {/each}
        </div>
      {/if}
    </div>

    <!-- Actions / View All Footer (always visible unless loading or error) -->
    {#if !notificationState.loading && !notificationState.error}
      <DropdownMenuSeparator />

      <div class="flex justify-between p-2 bg-muted/10">
        <Button
          variant="ghost"
          size="sm"
          onclick={(e: MouseEvent) => {
            e.stopPropagation()
            void postUiTelemetry({
              eventName: 'notifications.ui.marked_all_read',
              module: 'notifications',
              subsystem: 'notification_dropdown',
              workflow: 'notification_dropdown',
              eventFamily: 'ui',
              surface: 'notification_dropdown',
              frontendSubmissionId: activeDropdownSessionId,
              metadata: {
                unread_count: notificationState.unreadCount,
              },
              persist: true,
            }).catch(() => {})
            void notificationState.markAllAsRead()
          }}
          disabled={notificationState.unreadCount === 0}
        >
          {t('notifications.mark_all_read', {}, 'Mark all as read')}
        </Button>
        <Button
          variant="ghost"
          size="sm"
          onclick={(e: MouseEvent) => {
            e.stopPropagation()
            void postUiTelemetry({
              eventName: 'notifications.ui.refreshed',
              module: 'notifications',
              subsystem: 'notification_dropdown',
              workflow: 'notification_dropdown',
              eventFamily: 'ui',
              surface: 'notification_dropdown',
              frontendSubmissionId: activeDropdownSessionId,
            }).catch(() => {})
            void notificationState.refresh()
          }}
        >
          {t('common.refresh', {}, 'Refresh')}
        </Button>
      </div>

      <DropdownMenuSeparator />
      <div class="p-2 text-center bg-accent/40 border-t border-border">
        <Link
          href={notificationInboxUrl(notificationShell)}
          class="inline-flex w-full items-center justify-center text-xs font-bold text-primary hover:underline py-1.5"
          onclick={() => { open = false }}
        >
          {t('notifications.view_all', {}, 'View all notifications')} →
        </Link>
      </div>
    {/if}
  </DropdownMenuContent>
</DropdownMenu>

// inertia/components/layout/notification_dropdown.tsx

import { Bell, Check, Trash2 } from 'lucide-react'
import { Button } from '@/components/ui/button'
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuGroup,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown_menu'
import { useNotifications } from '@/hooks/use_notifications'
import useTranslation from '@/hooks/use_translation'
import { format } from 'date-fns'
import { vi } from 'date-fns/locale'

interface NotificationDropdownProps {
  className?: string
}

export function NotificationDropdown({ className }: NotificationDropdownProps) {
  const {
    notifications,
    unreadCount,
    loading,
    error,
    markAsRead,
    markAllAsRead,
    deleteNotification,
    refresh
  } = useNotifications()
  const { t } = useTranslation()

  // Định dạng thời gian với xử lý lỗi nâng cao
  const formatTime = (dateString: string) => {
    try {
      // Kiểm tra nếu dateString là null, undefined hoặc rỗng
      if (!dateString) {
        return t('common.unknown_time', {}, 'Không xác định')
      }

      // Thử parse với các định dạng khác nhau
      let date: Date;

      // Nếu là chuỗi ISO, parse trực tiếp
      if (dateString.includes('T') && dateString.includes('Z')) {
        date = new Date(dateString);
      } else {
        // Thử parse với Date constructor
        date = new Date(dateString);

        // Nếu không thành công, thử parse theo định dạng MySQL
        if (isNaN(date.getTime())) {
          // Định dạng: YYYY-MM-DD HH:MM:SS
          const parts = dateString.match(/^(\d{4})-(\d{2})-(\d{2})\s+(\d{2}):(\d{2}):(\d{2})$/);
          if (parts) {
            const [, year, month, day, hour, minute, second] = parts;
            date = new Date(
              parseInt(year),
              parseInt(month) - 1, // Tháng trong JS bắt đầu từ 0
              parseInt(day),
              parseInt(hour),
              parseInt(minute),
              parseInt(second)
            );
          }
        }
      }

      // Kiểm tra nếu ngày tháng hợp lệ
      if (isNaN(date.getTime())) {
        return t('common.invalid_date', {}, 'Ngày không hợp lệ')
      }

      return format(date, 'dd/MM/yyyy HH:mm', { locale: vi })
    } catch (error) {
      console.error('Lỗi khi định dạng thời gian:', error, dateString)
      return t('common.unknown_time', {}, 'Không xác định')
    }
  }

  // Hiển thị nội dung thông báo
  const renderNotificationContent = (notification: unknown) => {
    // Xử lý các loại thông báo khác nhau
    switch (notification.type) {
      case 'task_assigned':
        return (
          <div>
            <p className="font-medium">{notification.title || t('notifications.no_title', {}, 'Không có tiêu đề')}</p>
            <p className="text-sm text-muted-foreground mt-1">{notification.message || t('notifications.no_message', {}, 'Không có nội dung')}</p>
          </div>
        )
      case 'task_completed':
        return (
          <div>
            <p className="font-medium">{notification.title || t('notifications.no_title', {}, 'Không có tiêu đề')}</p>
            <p className="text-sm text-muted-foreground mt-1">{notification.message || t('notifications.no_message', {}, 'Không có nội dung')}</p>
          </div>
        )
      case 'task_overdue':
        return (
          <div>
            <p className="font-medium text-red-500">{notification.title || t('notifications.no_title', {}, 'Không có tiêu đề')}</p>
            <p className="text-sm text-muted-foreground mt-1">{notification.message || t('notifications.no_message', {}, 'Không có nội dung')}</p>
          </div>
        )
      default:
        return (
          <div>
            <p className="font-medium">{notification.title || t('notifications.no_title', {}, 'Không có tiêu đề')}</p>
            <p className="text-sm text-muted-foreground mt-1">{notification.message || t('notifications.no_message', {}, 'Không có nội dung')}</p>
          </div>
        )
    }
  }

  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button variant="ghost" size="icon" className={`text-muted-foreground relative ${className}`}>
          <Bell className="h-5 w-5" />
          {unreadCount > 0 && (
            <span className="absolute top-0 right-0 h-2 w-2 rounded-full bg-red-500"></span>
          )}
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent className="w-80" align="end">
        <DropdownMenuLabel className="flex items-center justify-between">
          <span>{t('notifications.title', {}, 'Thông báo')}</span>
          {unreadCount > 0 && (
            <span className="bg-primary text-primary-foreground text-xs font-medium px-2 py-1 rounded-full">
              {unreadCount}
            </span>
          )}
        </DropdownMenuLabel>

        <DropdownMenuSeparator />

        {loading ? (
          <DropdownMenuItem className="flex items-center justify-center py-6">
            <div className="animate-spin rounded-full h-6 w-6 border-b-2 border-primary"></div>
          </DropdownMenuItem>
        ) : error ? (
          <DropdownMenuItem className="py-4 text-center text-destructive">
            {error}
          </DropdownMenuItem>
        ) : notifications.length === 0 ? (
          <DropdownMenuItem className="py-6 text-center text-muted-foreground">
            {t('notifications.no_notifications', {}, 'Không có thông báo nào')}
          </DropdownMenuItem>
        ) : (
          <>
            <DropdownMenuGroup className="max-h-96 overflow-y-auto">
              {notifications.map((notification) => (
                <DropdownMenuItem
                  key={notification.id}
                  className={`flex flex-col items-start p-4 focus:bg-muted/50 ${
                    notification.is_read ? 'bg-muted/50' : 'bg-background'
                  }`}
                  onSelect={(e) => e.preventDefault()}
                >
                  <div className="w-full">
                    <div className="flex justify-between items-start">
                      <div className="flex-1">
                        {renderNotificationContent(notification)}
                      </div>
                      <div className="flex gap-1 ml-2">
                        {!notification.is_read && (
                          <Button
                            variant="ghost"
                            size="icon"
                            className="h-6 w-6"
                            onClick={(e) => {
                              e.stopPropagation();
                              markAsRead(notification.id);
                            }}
                          >
                            <Check className="h-3 w-3" />
                          </Button>
                        )}
                        <Button
                          variant="ghost"
                          size="icon"
                          className="h-6 w-6"
                          onClick={(e) => {
                            e.stopPropagation();
                            deleteNotification(notification.id);
                          }}
                        >
                          <Trash2 className="h-3 w-3" />
                        </Button>
                      </div>
                    </div>
                    <div className="text-xs text-muted-foreground mt-2">
                      {formatTime(notification.created_at)}
                    </div>
                  </div>
                </DropdownMenuItem>
              ))}
            </DropdownMenuGroup>

            <DropdownMenuSeparator />

            <div className="flex justify-between p-2">
              <Button
                variant="ghost"
                size="sm"
                onClick={(e) => {
                  e.stopPropagation();
                  markAllAsRead();
                }}
                disabled={unreadCount === 0}
              >
                {t('notifications.mark_all_read', {}, 'Đánh dấu tất cả đã đọc')}
              </Button>
              <Button
                variant="ghost"
                size="sm"
                onClick={(e) => {
                  e.stopPropagation();
                  refresh();
                }}
              >
                {t('common.refresh', {}, 'Làm mới')}
              </Button>
            </div>
          </>
        )}
      </DropdownMenuContent>
    </DropdownMenu>
  )
}
