// inertia/pages/organizations/members/index.tsx
import React, { useState, useEffect } from 'react'
import { Head, router, useForm } from '@inertiajs/react'
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle
} from '@/components/ui/card'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import { Input } from '@/components/ui/input'
import { Button } from '@/components/ui/button'
import { Label } from '@/components/ui/label'
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow
} from '@/components/ui/table'

import { Badge } from '@/components/ui/badge'
import { Plus,  UserCheck, CheckCircle, XCircle, Mail, Trash2 } from 'lucide-react'
import AppLayout from '@/layouts/app_layout'
import { toast } from 'sonner'

// Định nghĩa các kiểu dữ liệu
interface OrganizationMember {
  id: number
  username: string
  email: string
  role_id: number
  role_name: string
}

interface PendingRequest {
  user_id: number
  username: string
  email: string
  invited_by: number | null
  inviter_name: string | null
  created_at: string
}

interface Organization {
  id: number
  name: string
  description: string | null
  logo: string | null
  website: string | null
}

interface Role {
  id: number
  name: string
  description: string | null
}

interface MembersIndexProps {
  organization: Organization
  members?: OrganizationMember[]
  roles: Role[]
  userRole: number
  pendingRequests?: PendingRequest[]
}

// Form thêm thành viên
const AddMemberForm = ({ organization, roles, onSuccess }: { organization: Organization, roles: Role[], onSuccess?: () => void }) => {
  const { data, setData, post, processing, errors, reset } = useForm({
    email: '',
    roleId: '3', // Mặc định là user thường
  })

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()
    post(`/organizations/${organization.id}/members/add`, {
      onSuccess: () => {
        reset()
        toast.success('Đã thêm thành viên thành công')
        if (onSuccess) onSuccess()
      },
      onError: (errors) => {
        toast.error('Có lỗi xảy ra khi thêm thành viên')
      },
    })
  }

  return (
    <form onSubmit={handleSubmit} className="space-y-4">
      <div className="space-y-2">
        <Label htmlFor="email">Email</Label>
        <Input
          id="email"
          type="email"
          placeholder="Email người dùng cần thêm"
          value={data.email}
          onChange={(e) => setData('email', e.target.value)}
          required
        />
        {errors.email && <div className="text-red-500 text-sm">{errors.email}</div>}
      </div>

      <div className="space-y-2">
        <Label htmlFor="roleId">Vai trò</Label>
        <Select
          value={data.roleId}
          onValueChange={(value) => setData('roleId', value)}
        >
          <SelectTrigger>
            <SelectValue placeholder="Chọn vai trò" />
          </SelectTrigger>
          <SelectContent>
            {roles.map((role) => (
              <SelectItem key={role.id} value={role.id.toString()}>
                {role.name}
              </SelectItem>
            ))}
          </SelectContent>
        </Select>
        {errors.roleId && <div className="text-red-500 text-sm">{errors.roleId}</div>}
      </div>

      <Button type="submit" disabled={processing} className="w-full">
        Thêm thành viên
      </Button>
    </form>
  )
}

// Form mời người dùng
const InviteUserForm = ({ organization, roles, onSuccess }: { organization: Organization, roles: Role[], onSuccess?: () => void }) => {
  const { data, setData, post, processing, errors, reset } = useForm({
    email: '',
    roleId: '3', // Mặc định là user thường
  })

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()
    post(`/organizations/${organization.id}/members/invite`, {
      onSuccess: () => {
        reset()
        toast.success('Đã gửi lời mời thành công')
        if (onSuccess) onSuccess()
      },
      onError: (errors) => {
        toast.error('Có lỗi xảy ra khi gửi lời mời')
      },
    })
  }

  return (
    <form onSubmit={handleSubmit} className="space-y-4">
      <div className="space-y-2">
        <Label htmlFor="email">Email</Label>
        <Input
          id="email"
          type="email"
          placeholder="Email người dùng cần mời"
          value={data.email}
          onChange={(e) => setData('email', e.target.value)}
          required
        />
        {errors.email && <div className="text-red-500 text-sm">{errors.email}</div>}
      </div>

      <div className="space-y-2">
        <Label htmlFor="roleId">Vai trò</Label>
        <Select
          value={data.roleId}
          onValueChange={(value) => setData('roleId', value)}
        >
          <SelectTrigger>
            <SelectValue placeholder="Chọn vai trò" />
          </SelectTrigger>
          <SelectContent>
            {roles.map((role) => (
              <SelectItem key={role.id} value={role.id.toString()}>
                {role.name}
              </SelectItem>
            ))}
          </SelectContent>
        </Select>
        {errors.roleId && <div className="text-red-500 text-sm">{errors.roleId}</div>}
      </div>

      <Button type="submit" disabled={processing} className="w-full">
        Gửi lời mời
      </Button>
    </form>
  )
}

// Component chính cho trang quản lý thành viên
const MembersIndex = ({ organization, members = [], roles, userRole, pendingRequests = [] }: MembersIndexProps) => {
  const [showAddMemberDialog, setShowAddMemberDialog] = useState(false)
  const [showInviteDialog, setShowInviteDialog] = useState(false)
  const [showPendingRequestsDialog, setShowPendingRequestsDialog] = useState(false)
  const [pendingRequestsCount, setPendingRequestsCount] = useState(pendingRequests.length)

  // Cập nhật số lượng yêu cầu chờ duyệt khi prop thay đổi
  useEffect(() => {
    setPendingRequestsCount(pendingRequests.length)
  }, [pendingRequests])

  // Kiểm tra quyền (chỉ superadmin mới có thể phê duyệt thành viên)
  const canManageRequests = userRole === 1 || userRole === 2
  const isSuperAdmin = userRole === 1

  // Gọi lại trang khi có thay đổi về thành viên hoặc yêu cầu
  const refreshPage = () => {
    router.reload({
      only: ['members', 'pendingRequests'],
    })
  }

  // Xử lý duyệt/từ chối yêu cầu
  const handleProcessRequest = (userId: number, action: 'approve' | 'reject') => {
    router.post(`/organizations/${organization.id}/members/process-request/${userId}`, {
      action,
    }, {
      onSuccess: () => {
        toast.success(`Đã ${action === 'approve' ? 'duyệt' : 'từ chối'} yêu cầu thành công`)
        refreshPage()
      },
      onError: () => {
        toast.error(`Có lỗi xảy ra khi ${action === 'approve' ? 'duyệt' : 'từ chối'} yêu cầu`)
      },
    })
  }

  // Xử lý cập nhật vai trò
  const handleUpdateRole = (memberId: number, roleId: string) => {
    router.post(`/organizations/${organization.id}/members/update-role/${memberId}`, {
      roleId,
    }, {
      onSuccess: () => {
        toast.success('Đã cập nhật vai trò thành công')
        refreshPage()
      },
      onError: () => {
        toast.error('Có lỗi xảy ra khi cập nhật vai trò')
      },
    })
  }

  // Xử lý xóa thành viên
  const handleRemoveMember = (memberId: number) => {
    if (confirm('Bạn có chắc chắn muốn xóa thành viên này khỏi tổ chức?')) {
      router.delete(`/organizations/${organization.id}/members/${memberId}`, {
        onSuccess: () => {
          toast.success('Đã xóa thành viên thành công')
          refreshPage()
        },
        onError: () => {
          toast.error('Có lỗi xảy ra khi xóa thành viên')
        },
      })
    }
  }

  // Format thời gian
  const formatDateTime = (dateString: string) => {
    try {
      const date = new Date(dateString)
      return date.toLocaleDateString('vi-VN', {
        day: '2-digit',
        month: '2-digit',
        year: 'numeric',
        hour: '2-digit',
        minute: '2-digit'
      })
    } catch (error) {
      return dateString
    }
  }

  return (
    <AppLayout title={`Quản lý thành viên - ${organization.name}`}>
      <Head title={`Quản lý thành viên - ${organization.name}`} />

      <div className="container py-4 space-y-4">
        <div className="flex justify-between items-center">
          <h1 className="text-2xl font-bold">Quản lý thành viên tổ chức</h1>
          <div className="flex items-center gap-2">
            {/* Nút phê duyệt thành viên chỉ dành cho superadmin */}
            {isSuperAdmin && pendingRequestsCount > 0 && (
              <Button
                variant="destructive"
                onClick={() => setShowPendingRequestsDialog(true)}
                className="font-medium"
              >
                <UserCheck className="h-5 w-5 mr-2" />
                Phê duyệt thành viên
                <Badge className="ml-2 bg-white text-red-600 hover:bg-white">
                  {pendingRequestsCount}
                </Badge>
              </Button>
            )}

            <Button onClick={() => setShowInviteDialog(true)}>
              <Mail className="h-4 w-4 mr-2" />
              Mời người dùng
            </Button>

            <Button onClick={() => setShowAddMemberDialog(true)}>
              <Plus className="h-4 w-4 mr-2" />
              Thêm thành viên
            </Button>
          </div>
        </div>

        {/* Hiển thị danh sách thành viên */}
        <Card>
          <CardHeader className="pb-2">
            <CardTitle>Danh sách thành viên</CardTitle>
            <CardDescription>
              Tổ chức hiện có {members.length} thành viên
            </CardDescription>
          </CardHeader>
          <CardContent>
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Tên</TableHead>
                  <TableHead>Username</TableHead>
                  <TableHead>Email</TableHead>
                  <TableHead>Vai trò</TableHead>
                  <TableHead className="text-right">Thao tác</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {members.map((member) => (
                  <TableRow key={member.id}>
                    <TableCell className="font-medium">{member.username || member.email}</TableCell>
                    <TableCell>{member.username}</TableCell>
                    <TableCell>{member.email}</TableCell>
                    <TableCell>
                      <Select
                        defaultValue={member.role_id.toString()}
                        onValueChange={(value) => handleUpdateRole(member.id, value)}
                        disabled={userRole !== 1} // Chỉ superadmin mới có thể thay đổi vai trò
                      >
                        <SelectTrigger className="w-32">
                          <SelectValue placeholder={member.role_name} />
                        </SelectTrigger>
                        <SelectContent>
                          {roles.map((role) => (
                            <SelectItem
                              key={role.id}
                              value={role.id.toString()}
                              disabled={role.id === 1 && userRole !== 1} // Chỉ superadmin mới có thể đặt vai trò superadmin
                            >
                              {role.name}
                            </SelectItem>
                          ))}
                        </SelectContent>
                      </Select>
                    </TableCell>
                    <TableCell className="text-right">
                      <Button
                        variant="outline"
                        size="sm"
                        onClick={() => handleRemoveMember(member.id)}
                        disabled={userRole !== 1 || member.id === userRole} // Chỉ superadmin mới có thể xóa và không thể tự xóa mình
                      >
                        <Trash2 className="h-4 w-4 mr-2" />
                        Xóa
                      </Button>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </CardContent>
        </Card>
      </div>

      {/* Dialog thêm thành viên */}
      <Dialog open={showAddMemberDialog} onOpenChange={setShowAddMemberDialog}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Thêm thành viên mới</DialogTitle>
            <DialogDescription>
              Thêm thành viên vào tổ chức {organization.name}
            </DialogDescription>
          </DialogHeader>
          <AddMemberForm
            organization={organization}
            roles={roles}
            onSuccess={() => {
              setShowAddMemberDialog(false)
              refreshPage()
            }}
          />
        </DialogContent>
      </Dialog>

      {/* Dialog mời người dùng */}
      <Dialog open={showInviteDialog} onOpenChange={setShowInviteDialog}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Mời người dùng</DialogTitle>
            <DialogDescription>
              Gửi lời mời tham gia tổ chức {organization.name}
            </DialogDescription>
          </DialogHeader>
          <InviteUserForm
            organization={organization}
            roles={roles}
            onSuccess={() => {
              setShowInviteDialog(false)
              refreshPage()
            }}
          />
        </DialogContent>
      </Dialog>

      {/* Modal hiển thị yêu cầu đang chờ duyệt - chỉ hiển thị cho superadmin */}
      {isSuperAdmin && (
        <Dialog open={showPendingRequestsDialog} onOpenChange={setShowPendingRequestsDialog}>
          <DialogContent className="max-w-4xl">
            <DialogHeader>
              <DialogTitle className="flex items-center">
                <UserCheck className="h-5 w-5 mr-2 text-destructive" />
                Phê duyệt yêu cầu tham gia tổ chức
              </DialogTitle>
              <DialogDescription>
                Duyệt hoặc từ chối các yêu cầu tham gia tổ chức {organization.name}
              </DialogDescription>
            </DialogHeader>

            {pendingRequests.length === 0 ? (
              <div className="text-center py-6">
                <p className="text-muted-foreground">Không có yêu cầu tham gia tổ chức nào đang chờ duyệt</p>
              </div>
            ) : (
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Người dùng</TableHead>
                    <TableHead>Email</TableHead>
                    <TableHead>Được mời bởi</TableHead>
                    <TableHead>Thời gian yêu cầu</TableHead>
                    <TableHead className="text-right">Thao tác</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {pendingRequests.map((request) => (
                    <TableRow key={request.user_id}>
                      <TableCell className="font-medium">{request.username || request.email}</TableCell>
                      <TableCell>{request.email}</TableCell>
                      <TableCell>
                        {request.invited_by ? (
                          request.inviter_name
                        ) : (
                          <Badge variant="outline">Tự yêu cầu</Badge>
                        )}
                      </TableCell>
                      <TableCell>{formatDateTime(request.created_at)}</TableCell>
                      <TableCell className="text-right">
                        <div className="flex justify-end space-x-2">
                          <Button
                            variant="outline"
                            size="sm"
                            onClick={() => handleProcessRequest(request.user_id, 'reject')}
                          >
                            <XCircle className="w-4 h-4 mr-2" />
                            Từ chối
                          </Button>
                          <Button
                            size="sm"
                            variant="default"
                            className="bg-green-600 hover:bg-green-700"
                            onClick={() => handleProcessRequest(request.user_id, 'approve')}
                          >
                            <CheckCircle className="w-4 h-4 mr-2" />
                            Phê duyệt
                          </Button>
                        </div>
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            )}

            <DialogFooter>
              <Button variant="outline" onClick={() => setShowPendingRequestsDialog(false)}>Đóng</Button>
            </DialogFooter>
          </DialogContent>
        </Dialog>
      )}
    </AppLayout>
  )
}

export default MembersIndex

// inertia/pages/organizations/members/index.svelte
<script lang="ts">
  import { router, useForm } from '@inertiajs/svelte'
  import Card from '@/components/ui/card.svelte'
  import CardContent from '@/components/ui/card_content.svelte'
  import CardDescription from '@/components/ui/card_description.svelte'
  import CardHeader from '@/components/ui/card_header.svelte'
  import CardTitle from '@/components/ui/card_title.svelte'
  import Dialog from '@/components/ui/dialog.svelte'
  import DialogContent from '@/components/ui/dialog_content.svelte'
  import DialogDescription from '@/components/ui/dialog_description.svelte'
  import DialogFooter from '@/components/ui/dialog_footer.svelte'
  import DialogHeader from '@/components/ui/dialog_header.svelte'
  import DialogTitle from '@/components/ui/dialog_title.svelte'
  import Select from '@/components/ui/select.svelte'
  import SelectContent from '@/components/ui/select_content.svelte'
  import SelectItem from '@/components/ui/select_item.svelte'
  import SelectTrigger from '@/components/ui/select_trigger.svelte'
  import SelectValue from '@/components/ui/select_value.svelte'
  import Input from '@/components/ui/input.svelte'
  import Button from '@/components/ui/button.svelte'
  import Label from '@/components/ui/label.svelte'
  import Table from '@/components/ui/table.svelte'
  import TableBody from '@/components/ui/table_body.svelte'
  import TableCell from '@/components/ui/table_cell.svelte'
  import TableHead from '@/components/ui/table_head.svelte'
  import TableHeader from '@/components/ui/table_header.svelte'
  import TableRow from '@/components/ui/table_row.svelte'
  import Badge from '@/components/ui/badge.svelte'
  import { Plus, UserCheck, CheckCircle, XCircle, Mail, Trash2 } from 'lucide-svelte'
  import AppLayout from '@/layouts/app_layout.svelte'
  import { toast } from 'svelte-sonner'

  // Định nghĩa các kiểu dữ liệu
  interface OrganizationMember {
    id: number
    username: string
    email: string
    role_id: number
    role_name: string
  }

  interface PendingRequest {
    user_id: number
    username: string
    email: string
    invited_by: number | null
    inviter_name: string | null
    created_at: string
  }

  interface Organization {
    id: number
    name: string
    description: string | null
    logo: string | null
    website: string | null
  }

  interface Role {
    id: number
    name: string
    description: string | null
  }

  interface Props {
    organization: Organization
    members?: OrganizationMember[]
    roles: Role[]
    userRole: number
    pendingRequests?: PendingRequest[]
  }

  const { organization, members = [], roles, userRole, pendingRequests = [] }: Props = $props()

  let showAddMemberDialog = $state(false)
  let showInviteDialog = $state(false)
  let showPendingRequestsDialog = $state(false)
  let pendingRequestsCount = $derived(pendingRequests.length)

  // Kiểm tra quyền (chỉ superadmin mới có thể phê duyệt thành viên)
  const canManageRequests = $derived(userRole === 1 || userRole === 2)
  const isSuperAdmin = $derived(userRole === 1)

  // Gọi lại trang khi có thay đổi về thành viên hoặc yêu cầu
  function refreshPage() {
    router.reload({
      only: ['members', 'pendingRequests'],
    })
  }

  // Xử lý duyệt/từ chối yêu cầu
  function handleProcessRequest(userId: number, action: 'approve' | 'reject') {
    router.post(`/organizations/${organization.id}/members/process-request/${userId}`, {
      action,
    }, {
      onSuccess: () => {
        toast.success(`Đã ${action === 'approve' ? 'duyệt' : 'từ chối'} yêu cầu thành công`)
        refreshPage()
      },
      onError: () => {
        toast.error(`Có lỗi xảy ra khi ${action === 'approve' ? 'duyệt' : 'từ chối'} yêu cầu`)
      },
    })
  }

  // Xử lý cập nhật vai trò
  function handleUpdateRole(memberId: number, roleId: string) {
    router.post(`/organizations/${organization.id}/members/update-role/${memberId}`, {
      roleId,
    }, {
      onSuccess: () => {
        toast.success('Đã cập nhật vai trò thành công')
        refreshPage()
      },
      onError: () => {
        toast.error('Có lỗi xảy ra khi cập nhật vai trò')
      },
    })
  }

  // Xử lý xóa thành viên
  function handleRemoveMember(memberId: number) {
    if (confirm('Bạn có chắc chắn muốn xóa thành viên này khỏi tổ chức?')) {
      router.delete(`/organizations/${organization.id}/members/${memberId}`, {
        onSuccess: () => {
          toast.success('Đã xóa thành viên thành công')
          refreshPage()
        },
        onError: () => {
          toast.error('Có lỗi xảy ra khi xóa thành viên')
        },
      })
    }
  }

  // Format thời gian
  function formatDateTime(dateString: string) {
    try {
      const date = new Date(dateString)
      return date.toLocaleDateString('vi-VN', {
        day: '2-digit',
        month: '2-digit',
        year: 'numeric',
        hour: '2-digit',
        minute: '2-digit'
      })
    } catch (error) {
      return dateString
    }
  }

  // Effect để cập nhật count khi props thay đổi
  $effect(() => {
    pendingRequestsCount = pendingRequests.length
  })
</script>

<svelte:head>
  <title>Quản lý thành viên - {organization.name}</title>
</svelte:head>

<AppLayout title={`Quản lý thành viên - ${organization.name}`}>
  <div class="container py-4 space-y-4">
    <div class="flex justify-between items-center">
      <h1 class="text-2xl font-bold">Quản lý thành viên tổ chức</h1>
      <div class="flex items-center gap-2">
        <!-- Nút phê duyệt thành viên chỉ dành cho superadmin -->
        {#if isSuperAdmin && pendingRequestsCount > 0}
          <Button
            variant="destructive"
            onclick={() => { showPendingRequestsDialog = true; }}
            class="font-medium"
          >
            <UserCheck class="h-5 w-5 mr-2" />
            Phê duyệt thành viên
            <Badge class="ml-2 bg-white text-red-600 hover:bg-white">
              {pendingRequestsCount}
            </Badge>
          </Button>
        {/if}

        <Button onclick={() => { showInviteDialog = true; }}>
          <Mail class="h-4 w-4 mr-2" />
          Mời người dùng
        </Button>

        <Button onclick={() => { showAddMemberDialog = true; }}>
          <Plus class="h-4 w-4 mr-2" />
          Thêm thành viên
        </Button>
      </div>
    </div>

    <!-- Hiển thị danh sách thành viên -->
    <Card>
      <CardHeader class="pb-2">
        <CardTitle>Danh sách thành viên</CardTitle>
        <CardDescription>
          Tổ chức hiện có {members.length} thành viên
        </CardDescription>
      </CardHeader>
      <CardContent>
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Tên</TableHead>
              <TableHead>Username</TableHead>
              <TableHead>Email</TableHead>
              <TableHead>Vai trò</TableHead>
              <TableHead class="text-right">Thao tác</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {#each members as member (member.id)}
              <TableRow>
                <TableCell class="font-medium">{member.username || member.email}</TableCell>
                <TableCell>{member.username}</TableCell>
                <TableCell>{member.email}</TableCell>
                <TableCell>
                  <Select
                    value={member.role_id.toString()}
                    onValueChange={(value) => { handleUpdateRole(member.id, value); }}
                    disabled={userRole !== 1}
                  >
                    <SelectTrigger class="w-32">
                      <SelectValue placeholder={member.role_name} />
                    </SelectTrigger>
                    <SelectContent>
                      {#each roles as role (role.id)}
                        <SelectItem
                          value={role.id.toString()}
                          disabled={role.id === 1 && userRole !== 1}
                        >
                          {role.name}
                        </SelectItem>
                      {/each}
                    </SelectContent>
                  </Select>
                </TableCell>
                <TableCell class="text-right">
                  <Button
                    variant="outline"
                    size="sm"
                    onclick={() => { handleRemoveMember(member.id); }}
                    disabled={userRole !== 1 || member.id === userRole}
                  >
                    <Trash2 class="h-4 w-4 mr-2" />
                    Xóa
                  </Button>
                </TableCell>
              </TableRow>
            {/each}
          </TableBody>
        </Table>
      </CardContent>
    </Card>
  </div>

  <!-- Dialog thêm thành viên -->
  <Dialog bind:open={showAddMemberDialog}>
    <DialogContent>
      <DialogHeader>
        <DialogTitle>Thêm thành viên mới</DialogTitle>
        <DialogDescription>
          Thêm thành viên vào tổ chức {organization.name}
        </DialogDescription>
      </DialogHeader>
      <AddMemberForm
        {organization}
        {roles}
        onSuccess={() => {
          showAddMemberDialog = false
          refreshPage()
        }}
      />
    </DialogContent>
  </Dialog>

  <!-- Dialog mời người dùng -->
  <Dialog bind:open={showInviteDialog}>
    <DialogContent>
      <DialogHeader>
        <DialogTitle>Mời người dùng</DialogTitle>
        <DialogDescription>
          Gửi lời mời tham gia tổ chức {organization.name}
        </DialogDescription>
      </DialogHeader>
      <InviteUserForm
        {organization}
        {roles}
        onSuccess={() => {
          showInviteDialog = false
          refreshPage()
        }}
      />
    </DialogContent>
  </Dialog>

  <!-- Modal hiển thị yêu cầu đang chờ duyệt - chỉ hiển thị cho superadmin -->
  {#if isSuperAdmin}
    <Dialog bind:open={showPendingRequestsDialog}>
      <DialogContent class="max-w-4xl">
        <DialogHeader>
          <DialogTitle class="flex items-center">
            <UserCheck class="h-5 w-5 mr-2 text-destructive" />
            Phê duyệt yêu cầu tham gia tổ chức
          </DialogTitle>
          <DialogDescription>
            Duyệt hoặc từ chối các yêu cầu tham gia tổ chức {organization.name}
          </DialogDescription>
        </DialogHeader>

        {#if pendingRequests.length === 0}
          <div class="text-center py-6">
            <p class="text-muted-foreground">Không có yêu cầu tham gia tổ chức nào đang chờ duyệt</p>
          </div>
        {:else}
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Người dùng</TableHead>
                <TableHead>Email</TableHead>
                <TableHead>Được mời bởi</TableHead>
                <TableHead>Thời gian yêu cầu</TableHead>
                <TableHead class="text-right">Thao tác</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {#each pendingRequests as request (request.user_id)}
                <TableRow>
                  <TableCell class="font-medium">{request.username || request.email}</TableCell>
                  <TableCell>{request.email}</TableCell>
                  <TableCell>
                    {#if request.invited_by}
                      {request.inviter_name}
                    {:else}
                      <Badge variant="outline">Tự yêu cầu</Badge>
                    {/if}
                  </TableCell>
                  <TableCell>{formatDateTime(request.created_at)}</TableCell>
                  <TableCell class="text-right">
                    <div class="flex justify-end space-x-2">
                      <Button
                        variant="outline"
                        size="sm"
                        onclick={() => { handleProcessRequest(request.user_id, 'reject'); }}
                      >
                        <XCircle class="w-4 h-4 mr-2" />
                        Từ chối
                      </Button>
                      <Button
                        size="sm"
                        variant="default"
                        class="bg-green-600 hover:bg-green-700"
                        onclick={() => { handleProcessRequest(request.user_id, 'approve'); }}
                      >
                        <CheckCircle class="w-4 h-4 mr-2" />
                        Phê duyệt
                      </Button>
                    </div>
                  </TableCell>
                </TableRow>
              {/each}
            </TableBody>
          </Table>
        {/if}

        <DialogFooter>
          <Button variant="outline" onclick={() => { showPendingRequestsDialog = false; }}>Đóng</Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  {/if}
</AppLayout>

<!-- Form Components -->
{#snippet AddMemberForm({ organization, roles, onSuccess }: { organization: Organization, roles: Role[], onSuccess?: () => void })}
  {@const form = useForm({
    email: '',
    roleId: '3',
  })}

  <form onsubmit={(e) => {
    e.preventDefault()
    form.post(`/organizations/${organization.id}/members/add`, {
      onSuccess: () => {
        form.reset()
        toast.success('Đã thêm thành viên thành công')
        if (onSuccess) onSuccess()
      },
      onError: () => {
        toast.error('Có lỗi xảy ra khi thêm thành viên')
      },
    })
  }} class="space-y-4">
    <div class="space-y-2">
      <Label for="email">Email</Label>
      <Input
        id="email"
        type="email"
        placeholder="Email người dùng cần thêm"
        bind:value={form.data.email}
        required
      />
      {#if form.errors.email}
        <div class="text-red-500 text-sm">{form.errors.email}</div>
      {/if}
    </div>

    <div class="space-y-2">
      <Label for="roleId">Vai trò</Label>
      <Select
        value={form.data.roleId}
        onValueChange={(value) => { form.data.roleId = value; }}
      >
        <SelectTrigger>
          <SelectValue placeholder="Chọn vai trò" />
        </SelectTrigger>
        <SelectContent>
          {#each roles as role (role.id)}
            <SelectItem value={role.id.toString()}>
              {role.name}
            </SelectItem>
          {/each}
        </SelectContent>
      </Select>
      {#if form.errors.roleId}
        <div class="text-red-500 text-sm">{form.errors.roleId}</div>
      {/if}
    </div>

    <Button type="submit" disabled={form.processing} class="w-full">
      Thêm thành viên
    </Button>
  </form>
{/snippet}

{#snippet InviteUserForm({ organization, roles, onSuccess }: { organization: Organization, roles: Role[], onSuccess?: () => void })}
  {@const form = useForm({
    email: '',
    roleId: '3',
  })}

  <form onsubmit={(e) => {
    e.preventDefault()
    form.post(`/organizations/${organization.id}/members/invite`, {
      onSuccess: () => {
        form.reset()
        toast.success('Đã gửi lời mời thành công')
        if (onSuccess) onSuccess()
      },
      onError: () => {
        toast.error('Có lỗi xảy ra khi gửi lời mời')
      },
    })
  }} class="space-y-4">
    <div class="space-y-2">
      <Label for="invite-email">Email</Label>
      <Input
        id="invite-email"
        type="email"
        placeholder="Email người dùng cần mời"
        bind:value={form.data.email}
        required
      />
      {#if form.errors.email}
        <div class="text-red-500 text-sm">{form.errors.email}</div>
      {/if}
    </div>

    <div class="space-y-2">
      <Label for="invite-roleId">Vai trò</Label>
      <Select
        value={form.data.roleId}
        onValueChange={(value) => { form.data.roleId = value; }}
      >
        <SelectTrigger>
          <SelectValue placeholder="Chọn vai trò" />
        </SelectTrigger>
        <SelectContent>
          {#each roles as role (role.id)}
            <SelectItem value={role.id.toString()}>
              {role.name}
            </SelectItem>
          {/each}
        </SelectContent>
      </Select>
      {#if form.errors.roleId}
        <div class="text-red-500 text-sm">{form.errors.roleId}</div>
      {/if}
    </div>

    <Button type="submit" disabled={form.processing} class="w-full">
      Gửi lời mời
    </Button>
  </form>
{/snippet}
