// inertia/pages/tasks/components/task_list/cells/child/due_date_cell.tsx

import { CalendarIcon } from 'lucide-react'

interface DueDateCellProps {
  dueDate?: string
  formatDate: (dateString: string) => string
}

export function DueDateCell({ dueDate, formatDate }: DueDateCellProps) {
  return (
    <div className="flex items-center gap-1">
      <CalendarIcon className="h-3 w-3 text-muted-foreground flex-shrink-0" />
      {dueDate ? (
        <span className={`text-[11px] font-medium ${
          // Đơn giản hóa logic màu sắc
          new Date(dueDate) < new Date() ? 'text-red-600' : // Quá hạn: Đỏ
          'text-violet-500' // Mặc định: Tím
        }`}>{formatDate(dueDate)}</span>
      ) : (
        <span className="text-[11px] text-slate-500">-</span> // Không có hạn: Xám
      )}
    </div>
  )
}

// inertia/apps/org/modules/tasks/components/task_list/cells/child/due_date_cell.svelte
<script lang="ts">
  import { CalendarIcon } from 'lucide-svelte'

  interface Props {
    dueDate?: string
    formatDate: (dateString: string) => string
  }

  const { dueDate, formatDate }: Props = $props()

  const isOverdue = $derived(dueDate ? new Date(dueDate) < new Date() : false)
</script>

<div class="flex items-center gap-1">
  <CalendarIcon class="h-3 w-3 text-muted-foreground flex-shrink-0" />
  {#if dueDate}
    <span class="text-[11px] font-medium {isOverdue ? 'text-destructive' : 'text-violet-500'}">
      {formatDate(dueDate)}
    </span>
  {:else}
    <span class="text-[11px] text-muted-foreground">-</span>
  {/if}
</div>
