// inertia/pages/users/pending_approval.tsx
import React from 'react'
import { Head } from '@inertiajs/react'
import AppLayout from '@/layouts/app_layout'
import { Button } from '@/components/ui/button'
import useTranslation from '@/hooks/use_translation'
import UserSearchForm from './components/UserSearchForm'
import PendingApprovalTable from './components/PendingApprovalTable'
import type { PendingApprovalProps } from './types'
import { usePendingApproval } from './hooks/use_pending_approval'

export default function PendingApproval({ users, filters,  }: PendingApprovalProps) {
  const [search, setSearch] = React.useState(filters.search || '')
  const { t } = useTranslation()
  const { approveAllUsers } = usePendingApproval(users)

  const handleSearch = (e: React.FormEvent) => {
    e.preventDefault()
    const queryParams = new URLSearchParams()

    if (search) queryParams.append('search', search)

    const queryString = queryParams.toString()
    window.location.href = `/users/pending-approval${queryString ? `?${queryString}` : ''}`
  }

  return (
    <>
      <Head title={t('user.pending_approval', {}, "Phê duyệt người dùng")} />
      <div className="container py-8">
        <div className="flex items-center justify-between">
          <h1 className="text-3xl font-bold">{t('user.pending_approval', {}, "Phê duyệt người dùng")}</h1>
          <Button onClick={approveAllUsers} disabled={!users.data.length}>
            {t('user.approve_all', {}, "Phê duyệt tất cả")}
          </Button>
        </div>

        <div className="mt-6">
          <UserSearchForm
            search={search}
            setSearch={setSearch}
            handleSearch={handleSearch}
          />
        </div>

        <div className="mt-6">
          <PendingApprovalTable
            users={users}
            filters={filters}
          />
        </div>
      </div>
    </>
  )
}

PendingApproval.layout = (page: React.ReactNode) => <AppLayout title="Phê duyệt người dùng">{page}</AppLayout>

// inertia/apps/org/modules/users/pending_approval.svelte
<script lang="ts">
  
  import Button from '@/apps/org/shared/ui/button.svelte'
  import OrganizationLayout from '@/apps/org/shared/layouts/organization_layout.svelte'
  import { useTranslation } from '@/apps/org/shared/stores/translation.svelte'

  import PendingApprovalTable from './components/pending_approval_table.svelte'
  import { createPendingApproval } from './hooks/use_pending_approval.svelte'
  import type { PendingApprovalProps } from './types'

  const { users, pagination, filters }: PendingApprovalProps = $props()

  const { approveAllUsers } = createPendingApproval(() => users)
  const { t } = useTranslation()

  
</script>

<svelte:head>
  <title>{t('user.approve_users', {}, 'Approve Users')}</title>
</svelte:head>

<OrganizationLayout title={t('user.approve_users', {}, 'Approve Users')}>
  <div class="container py-8">
    <div class="flex items-center justify-between">
      <h1 class="text-3xl font-bold">{t('user.approve_users', {}, 'Approve Users')}</h1>
      <Button onclick={approveAllUsers} disabled={!users.length}>
        {t('user.approve_all', {}, 'Approve All')}
      </Button>
    </div>

    <div class="mt-6">
      <PendingApprovalTable
        {users}
        {pagination}
        {filters}
      />
    </div>
  </div>
</OrganizationLayout>
